### DISCUSSION TITLE
How to properly parse OTEL-format logs collected by Datadog Agent?

### DISCUSSION THREAD

**Discussion by julealgon** [DataDog/datadog-agent#12701] [Q&A]
I'm using the Datadog Agent as an intermediate to push logs written in OTEL Protocol format to Datadog. This is a workaround to the problem described here:
- https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/2651

This is the configuration I'm using in the DD Agent right now:
```yml
logs:
  - type: file
    path: "C:\\otelcol-contrib_0.49.0_windows_amd64\\data.json"
    service: "MyService"
    source: "MySource"
```

And this is my OTEL collector setup:
```yml
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 10s

exporters:
  file:
    path: ./data.json
    
  datadog/api:
    host_metadata:
      tags:
        - env:dev
    api:
      key: {my_key_here}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog/api]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog/api]
    logs:
      receivers: [otlp]
      processors: [logstransform]
      exporters: [file]
```

After configuring my OTEL Collector to output logs to a local file, then installing DD agent in the same server and pulling logs from that file, I was able to see log entries flowing through to Datadog, however they are "posted as-is": meaning all I see are raw JSON batches of OTEL-formatted json logs, and not the actual log entries themselves:

![image](https://user-images.githubusercontent.com/461579/178291308-ae3cc97c-4a74-4439-8f7d-3db12f1bb795.png)

Each "entry" above is actually a 5 second OTEL batch of logs each containing several log entries inside.

I was expecting Datadog to be "smart enough" to recognize that the data being pushed is OTEL Protocol logs data and properly parse the json and create all the necessary individual log events with their specific services, messages, etc.

Am I missing something? Both in the original issue above, as well as in this other question:
- https://github.com/vectordotdev/vector/discussions/13388

I was led to believe that it was possible to use the DD agent to overcome the current lack of a proper OTEL log exporter in the OpenTelemetry Collector, but if all it can do right now is post the raw batch json objects, then that's a fairly poor integration in my opinion and will make finding log entries later a nightmare.

Is there a way to set this up so that actual log entries are posted instead of the raw batch Json? Maybe something I can do either in the DD agent setup, or a Datadog ingestion pipeline to properly "parse" the OTEL Json object an split it into the actual log events, or even a configuration I could do in the collector itself that would allow for this?

@binarylogic and @jszwedko if you can help with this it would be much appreciated. Let me know if switching to Vector would be the sensible option here as well (assuming Vector can resolve this issue)
