### DISCUSSION TITLE
Journald multi-line aggregation support

### DISCUSSION THREAD

**Discussion by joshprice88** [DataDog/datadog-agent#15037] [General]
Hi,

I'm trying to consolidate multiple line stack trace errors into a single log entry for a container that is writing to journald.  My config looks like:
```
logs:
  - type: journald
     config_id: journald
     path: /var/log/journal
     exclude_units:
       - datadog-agent.service
     exclude_matches:
       - CONTAINER_NAME=myapp
   - type: journald
      config_id: myapp
      source: docker
      service: myapp
      path: /var/log/journal
      include_matches:
        - CONTAINER_NAME=myapp
      log_processing_rules:
        - type: multi-line
           name: new_log_start_with_date
           pattern: \d{4}\-(0?[1-9]|1[012])\-(0?[1-9]|[12][0-9]|3[01])
```

Although logs are collected from myapp, the multi-line processing rule does not seem to be taking effect.  Is multi-line processing supported for multiple journald configs?
