### DISCUSSION TITLE
Converting OpenTelemetry Resource Attributes to Host Tags when sending resources to the Datadog Agent OTLP Receiver

### DISCUSSION THREAD

**Discussion by NassimBtk** [DataDog/datadog-agent#30071] [Q&A]
### Description:

I am currently working with the OpenTelemetry Collector, sending several Host resources and metrics to the Datadog Agent via the OTLP receiver. I need to attach resource attributes (e.g., `env`, `service`) as host tags in Datadog.
![image](https://github.com/user-attachments/assets/02b761c8-086e-49de-bc58-e48182d65f35)

**DataDog Agent Config:**
```yaml
otlp_config:
  receiver:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
   metrics:
    resource_attributes_as_tags: true
```

**OpenTelemetry Collector Config:**
```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
processors:
  transform:
    metric_statements:
      - context: resource
        statements:
          - set(attributes["datadog.host.use_as_metadata"], true)
 # ...
 exporters:
  otlphttp/datadog-agent:
    endpoint: http://localhost:4318

service:
  telemetry:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [transform, memory_limiter, batch]
      exporters: [otlphttp/datadog-agent] # Datadog listed here
```

Is there a way to configure the Datadog Agent to automatically convert OpenTelemetry each resource attributes into host-level tags that can be applied to the infrastructure hosts? If so, what configuration changes are needed in either the OpenTelemetry Collector or the Datadog Agent?

Thanks!

**Comment by pablo-spinelli** [comment]
Hi there! Happy new year! qq, were you able to fix that because I have the same problem.... thank you!!

**Reply by NassimBtk** [reply]
Hello! Happy new year!
Yes, we were able to get OTEL resource attributes populated in Datadog as host tags. Here’s what worked for us:

* We populate host tags by setting **resource attributes prefixed with** `datadog.host.tag.` (e.g., `datadog.host.tag.env`).
  Datadog documents this here: **[OTLP resource attributes](https://docs.datadoghq.com/opentelemetry/config/hostname_tagging/?tab=host#as-otlp-resource-attributes)**.

  If you can’t set these attributes from the app/source, you can add or rewrite them in the Collector using a `resource` processor, or use the `transform` processor with OTTL for more advanced logic.

* We set `datadog.host.use_as_metadata` to `true` on all payloads that represent host resources (so Datadog treats them as host metadata):

  ```yaml
  processors:
    transform:
      metric_statements:
        - context: resource
          statements:
            - set(attributes["datadog.host.use_as_metadata"], true)
  ```
  Datadog documents this here: **[Host metadata](https://docs.datadoghq.com/opentelemetry/mapping/host_metadata/#opting-in-to-the-feature)**.
* We send the metrics using the **[Datadog Exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/datadogexporter)** instead of sending OTLP directly to the Agent.

  ```yaml
  exporters:
    datadog/api:
      api:
        key: "********" # Datadog API Key
        # site: datadoghq.eu # Uncomment and update if required
      host_metadata:
        enabled: true
        reporter_period: 5m # should be >= 5 minutes
      metrics:
        resource_attributes_as_tags: true
  ```

  We enable `host_metadata` with a `reporter_period` of **5 minutes** so that metadata (including host tags) are reported periodically to Datadog.

<img width="1430" height="865" alt="image" src="https://github.com/user-attachments/assets/ca8f99ad-6330-4f29-ba25-76d441224d6f" />
