### ISSUE TITLE
Can't Access Dogstatsd Nonlocally on k8s cluster

### ISSUE THREAD

**Issue by kellanburket** [DataDog/datadog-agent#10186]
I'm following [these setup instructions to transmit dogstatsd metrics to non-local pods](https://www.datadoghq.com/blog/monitor-kubernetes-docker/#send-custom-metrics-to-dogstatsd). My daemonset looks roughly like this:

  ```
    containers:
        - name: agent
          image: "gcr.io/datadoghq/agent:7.32.1"
          imagePullPolicy: IfNotPresent
          command: ["agent", "run"]
          resources: {}
          ports:
            - containerPort: 8125
              hostPort: 8125
              name: dogstatsdport
              protocol: UDP
          env:
            - name: GODEBUG
              value: x509ignoreCN=0
            - name: DD_SITE
              value: "datadoghq.com"
            - name: DD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: "datadog-agent"
                  key: api-key
            - name: DD_KUBERNETES_KUBELET_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: KUBERNETES
              value: "yes"
            - name: DD_LOG_LEVEL
              value: "INFO"
            - name: DD_DOGSTATSD_PORT
              value: "8125"
            - name: DD_DOGSTATSD_NON_LOCAL_TRAFFIC
              value: "true"
            - name: DD_DOGSTATSD_STATS_ENABLE
              value: "true"
            - name: DD_LEADER_ELECTION
              value: "true"
            - name: DD_COLLECT_KUBERNETES_EVENTS
              value: "true"
            - name: DD_APM_ENABLED
              value: "false"
            - name: DD_LOGS_ENABLED
              value: "false"
            - name: DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL
              value: "false"
            - name: DD_LOGS_CONFIG_K8S_CONTAINER_USE_FILE
              value: "true"
            - name: DD_HEALTH_PORT
              value: "5555"
            - name: DD_DOGSTATSD_SOCKET
              value: "/var/run/datadog/dsd.socket"
```

When I run this simple Python script locally it works fine, so I know that the agent is working:

```
from datadog import initialize, statsd
initialize({"statsd_host": "127.0.0.1", "statsd_port": 8125})
statsd.increment("testing123")
```

I have a pod that has the host ip set up as per instructions:

```
          env:
            - name: DATADOG_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
```

When I try to run the python script on the new pod, nothing is transmitted:

```
import os
from datadog import initialize, statsd
initialize({"statsd_host": os.getenv("DATADOG_HOST"), "statsd_port": 8125})
statsd.increment("testing456")
```

I can see that the host is reachable on the new pod, because I can connect to the trace agent: `curl $DATADOG_HOST:8126`

Not sure if I'm missing something, or if this `DD_DOGSTATSD_NON_LOCAL_TRAFFIC` isn't working like it should. 

My /etc/datadog-agent/datadog.yaml looks like this, not sure if it matters:

```
## Provides autodetected defaults, for kubernetes environments,
## please see datadog.yaml.example for all supported options

apm_config:
  apm_non_local_traffic: true
  max_memory: 0
  max_cpu_percent: 0

# Use java container support
jmx_use_container_support: true
```
