### ISSUE TITLE
Use `%` for MySQL integration setup document

### ISSUE THREAD

**Issue by kei6u** [DataDog/datadog-agent#10226]
**Describe what happened:**

I've tried Agent based MySQL integration according to this [setup guide](https://docs.datadoghq.com/integrations/mysql/?tab=host#setup).
I could not create the connection between Agent and MySQL when I use `'datadog'@'localhost'` or `'datadog'@'127.0.0.1'`.

Therefore, I want to suggest to use `'datadog'@'%'` to prevent the connection error.

**Describe what you expected:**

No one faces the connection error when reading the [setup guide](https://docs.datadoghq.com/integrations/mysql/?tab=host#setup).

**Steps to reproduce the issue:**

Execute `docker compose up` after preparing following files.

`docker-compose.yaml`

```yaml
version: "3.8"
services:
  agent:
    image: gcr.io/datadoghq/agent:7
    environment:
      DD_API_KEY: "" # TODO: set your api key
    volumes:
      - ./conf.yaml:/conf.d/mysql.d/conf.yaml
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /proc/:/host/proc/:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default
    depends_on:
      - mysql
  mysql:
    image: bitnami/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default
```

`conf.yaml`

```yaml
init_config:

instances:
  - server: mysql
    user: datadog
    pass: "password"
    port: "3306"
    options:
      replication: false
      galera_cluster: true
      extra_status_metrics: true
      extra_innodb_metrics: true
      extra_performance_metrics: true
      schema_size_metrics: false
      disable_innodb_metrics: false
```

`init.sql`

use `localhost`  (This is going to fail)

```sql
CREATE USER 'datadog'@'localhost' IDENTIFIED BY 'password';
GRANT REPLICATION CLIENT ON *.* TO 'datadog'@'localhost';
ALTER USER 'datadog'@'localhost'
WITH MAX_USER_CONNECTIONS 5;
GRANT PROCESS ON * . * TO 'datadog'@'localhost';
```

use `127.0.0.1` according to [MySQL Localhost Error - Localhost VS 127.0.0.1](https://docs.datadoghq.com/integrations/faq/mysql-localhost-error-localhost-vs-127-0-0-1/)  (This is going to fail)

```sql
CREATE USER 'datadog'@'127.0.0.1' IDENTIFIED BY 'password';
GRANT REPLICATION CLIENT ON *.* TO 'datadog'@'127.0.0.1';
ALTER USER 'datadog'@'127.0.0.1'
WITH MAX_USER_CONNECTIONS 5;
GRANT PROCESS ON * . * TO 'datadog'@'127.0.0.1';
```

use `%` (This is going to success)

```sql
CREATE USER 'datadog'@'%' IDENTIFIED BY 'password';
GRANT REPLICATION CLIENT ON *.* TO 'datadog'@'%';
ALTER USER 'datadog'@'%'
WITH MAX_USER_CONNECTIONS 5;
GRANT PROCESS ON * . * TO 'datadog'@'%';
```

**Additional environment details (Operating System, Cloud provider, etc):**
