### ISSUE TITLE
Issue with kubernetes metrics tags per pod

### ISSUE THREAD

**Issue by gabbueno** [DataDog/datadog-agent#10259]
I'm trying to tag metrics from pods with:

```
spec:
  template:
    metadata:
      labels:
        com.datadoghq.ad.tags: '[{"scope:k8s-staging", "env:k8s-staging"}]'
```

But when I try to deploy to kubernetes with kubectl, I got this error:
```
The Deployment "app01" is invalid: spec.template.labels: Invalid value: "[{\"scope:k8s-staging\", \"env:k8s-staging\"}]": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

What is the right format to add labels and get that labels as metric tags?
