### ISSUE TITLE
K8S resource labels as dd tags via labelsAsTags variable seems not to work

### ISSUE THREAD

**Issue by BlauerPulli** [DataDog/datadog-agent#10340]
Hey, is anyone successfully using the `datadog.kubeStateMetricsCore.labelsAsTags` value to export labels from a k8s resource as datadog tag? This doesn't work for me though i respect the label transformation done by kube-state-metrics.
Introduced with: https://github.com/DataDog/helm-charts/commit/20748841652b085e12df9b85fc7f0cfbf9f4b16b

**Steps to reproduce the issue:**
Existing label is: `helm.sh/chart: datadog-2.27.8`
Add the following to your values.yaml file:

```
datadog:
  kubeStateMetricsCore:
    labelsAsTags:
      deployment:
        label_helm_sh_chart: label_helm_sh_chart
```

**Additional environment details (Operating System, Cloud provider, etc):**
datadog chart version: 2.28.7
aks: 1.20.7
