### ISSUE TITLE
Using a CamelCase key in Redis breaks DatadogMetric

### ISSUE THREAD

**Issue by bgounon** [DataDog/datadog-agent#10615]
Hi, I am currently trying to configure DatadogMetric-based HPA autoscaling inside a Kubernetes cluster.
The goal is to scale a deployment based on the length of a Redis key named "**testKey**" using [Datadog Redis integration](https://docs.datadoghq.com/integrations/redisdb/?tab=kubernetes).

Annotations on the Redis pod are set like so:
```
podAnnotations:
      ad.datadoghq.com/redis.check_names: '["redisdb"]'
      ad.datadoghq.com/redis.init_configs: '[{}]'
      ad.datadoghq.com/redis.instances: |
        [
          {
            "host": "%%host%%",
            "port":"6379",
            "password":"ENC[redis-password]",
            "keys": ["testKey"]
          }
        ] 
```

Then we have the following DatadogMetric set up:
```
apiVersion: datadoghq.com/v1alpha1
kind: DatadogMetric
metadata:
  name: number-of-jobs
spec:
  query: max:redis.key.length{key:testKey}
```

And finally, the HPA:
```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: myhpa
spec:
  maxReplicas: 20
  minReplicas: 1
  metrics:
  - type: External
    external:
      metricName: datadogmetric@mynamespace:number-of-jobs
      targetAverageValue: 1
```

With this setup, Datadog fails to retrieve the key length and we see the following error logs in cluster agent:
```
2022-01-20 17:11:47 UTC | CLUSTER | ERROR | (pkg/clusteragent/externalmetrics/provider.go:103 in GetExternalMetric) | ExternalMetric query failed with error: DatadogMetric is invalid, err: Invalid metric (from backend), query: max:redis.key.length{key:testKey}
2022-01-20 17:11:47 UTC | CLUSTER | ERROR | (pkg/util/kubernetes/autoscalers/datadogexternal.go:157 in queryDatadogExternal) | Returned series slice empty
```

And the DatadogMetric is invalid:
```
    Message:               Invalid metric (from backend), query: max:redis.key.length{key:testKey}
    Reason:                Unable to fetch data from Datadog
    Status:                True
    Type:                  Error
```

The twist is, when we switch to using "**testkey**" instead of "**testKey**" in Redis and DatadogMetric configuration, everything works like a charm.

I suspect this is related to the fact that [Datadog enforces lowercase tags](https://docs.datadoghq.com/getting_started/tagging/#defining-tags), but this is definitely an issue because it prevents us from using camel-cased keys that are stored within our Redis database as metrics for our HPA.
