### ISSUE TITLE
Unknown environment variable: DD_INSIDE_CI

### ISSUE THREAD

**Issue by gurchik** [DataDog/datadog-agent#10969]
**Describe what happened:**

I'm following [these instructions](https://docs.datadoghq.com/continuous_integration/setup_tests/agent/) to set up CI Test instrumentation, and it says to set up the following environment variable:

```
DD_INSIDE_CI (Required)
Disables the monitoring of the Datadog Agent container, as the underlying host is not accessible.
Default: false
Required value: true
```

But this doesn't seem to do anything:

```
2022-02-16 19:02:13 UTC | TRACE | WARN | (pkg/util/log/log.go:640 in func1) | Unknown environment variable: DD_INSIDE_CI
```

**Describe what you expected:**
I expected to not receive this log message because the documentation says it's a required variable. So either the documentation is wrong about which environment variable to set or it's wrong that setting this environment variable is "required" and leaving it unset is acceptable.

**Steps to reproduce the issue:**
Use the following docker compose:

```
version: '3.7'
services:
  dd-agent-ci:
    image: "gcr.io/datadoghq/agent:latest"
    environment:
      - DD_API_KEY
      - DD_INSIDE_CI=true
      - DD_HOSTNAME=none
    ports:
      - 8126/tcp
```

And run it with:

```
DD_API_KEY=<your api key> docker-compose up dd-agent-ci
```

**Additional environment details (Operating System, Cloud provider, etc):**
N/A
