### ISSUE TITLE
data-agent(trace-agent) panic

### ISSUE THREAD

**Issue by tttoad** [DataDog/datadog-agent#11297]
(Deployed in k8s)
The link for data export is as follows.
app(jaeger-client: 2.29.1)->opentelemetry(0.46.0,using otlp reporter) -> datadog-agent 
![image](https://user-images.githubusercontent.com/14021602/158381807-5d383350-6c19-4a01-b4f3-eb8c582573d3.png)
I set the environment DD_OTLP_GRPC_PORT=4317, but it doesn't work?
![image](https://user-images.githubusercontent.com/14021602/158382488-a4468709-0a01-4475-a5a5-c4eb16eda8d8.png)
So I used port 5003.
opentelemetry-config.yaml
```
receivers:
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_http:
        endpoint: 0.0.0.0:14268
      thrift_compact:
        endpoint: 0.0.0.0:6831
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 100
    send_batch_max_size: 1000
    timeout: 10s
  resourcedetection:
    detectors: [ env ]
    timeout: 5s
    override: false
  k8sattributes:
    auth_type: "serviceAccount"

exporters:
  otlp:
    sending_queue:
      queue_size: 20000
      num_consumers: 300
    endpoint: otlp-agent.datadog.svc:5003
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [ jaeger , otlp ]
      processors: [ batch ,  resourcedetection, k8sattributes ]
      exporters: [ otlp ]
```
Then, the datadog-agent  panic....
![image](https://user-images.githubusercontent.com/14021602/158383056-c3c6b33a-d56a-4e25-a040-afa2f5bae3e8.png)
