### ISSUE TITLE
Template Variables %%env_<var>%% not working for postgres integration

### ISSUE THREAD

**Issue by zabaat** [DataDog/datadog-agent#12065]
**Describe what happened:**
1) created env var in host OS of `DATADOG_PGPASSWORD`
2) Created `/etc/datadog-agent/conf.d/postgres.d/conf.yaml` with following:
```
## All options defined here are available to all instances.
      #
      init_config:
  
          ## @param service - string - optional
          ## Attach the tag `service:<SERVICE>` to every metric, event, and service check emitted by this integration.
          ##
          ## Additionally, this sets the default `service` for every log source.
          #
          # service: <SERVICE>
  
      ## Every instance is scheduled independent of the others.
      #
      instances:
  
          ## @param host - string - required
          ## The hostname to connect to.
          ## NOTE: Even if the server name is `localhost`, the Agent connects to PostgreSQL using TCP/IP unless you also
          ## provide a value for the sock key.
          #
        - host: psql-masterytrack-production.cyspzu9k3jsf.us-west-2.rds.amazonaws.com
  
          ## @param port - integer - optional - default: 5432
          ## The port to use when connecting to PostgreSQL.
          #
          # port: 5432
  
          ## @param username - string - required
          ## The Datadog username created to connect to PostgreSQL.
          #
          username: datadog
  
          ## @param password - string - optional
          ## The password associated with the Datadog user.
          #
          password: "%%env_DATADOG_PGPASSWORD%%"
```

outputs password for user datadog is invalid

**Describe what you expected:**
Inject that password into this conf file and login correctly. 

When I hardcode password this works.
Much like this issue, we are automating deploying this and can't have the password in our configs
https://github.com/DataDog/datadog-agent/issues/3167

**Steps to reproduce the issue:**
The first thing I said?

**Additional environment details (Operating System, Cloud provider, etc):**
AWS, Elastic beanstalk, ubuntu

**Comment by lucasmari** [comment]
Hey, @zabaat! Are you creating the env variable as env_DATADOG_PGPASSWORD? If yes, you just have to remove the prefix "env_".

**Comment by sjohnsonsf** [comment]
+1 - Would like to use %%env_ to update Postgres password via task definition for ECS Fargate. PW works fine when hardcoded. Agent running Redis integration works fine with env vars.

**Comment by matsudamper** [comment]
Same with JMX integration.

**Comment by btsuhako** [comment]
I believe that this is still a problem. I tried to use the following with `7.52.1` of the Datadog Agent:

```yaml
init_config:
instances:
  - dbm: true
    host: "%%env_POSTGRES_HOST%%"
    port: 5432
    username: "%%env_POSTGRES_USERNAME%%"
    password: "%%env_POSTGRES_PASSWORD%%"
```

and the agent won't template out the environment variables correctly

I tried the above with `7.36.1`, and the integration config works as expected

**Comment by ThisIsQasim** [comment]
In case anyone else faces the same issue. You have to add the env vars to the cluster agent for the node agents to work
```
spec:
   override:
     clusterAgent:
       env:
       - name: POSTGRES_PASSWORD
         valueFrom:
           secretKeyRef:
             name: database-credentials
             key: password
      extraConfd:
         configDataMap:
           postgres.yaml: |-
             cluster_check: true
             init_config:
             instances:
               - dbm: true
                 host: asfasfasf.rds.amazonaws.com
                 port: 3306
                 username: "datadog"
                 password: "%%env_ POSTGRES_PASSWORD%%"
```
