### ISSUE TITLE
Datadog Cluster Agent errors after release 7.35.0

### ISSUE THREAD

**Issue by michelzanini** [DataDog/datadog-agent#12110]
Hi,

After the release of 2.33.4 version of the Datadog Helm Chart for Kubernetes we started to get this error on the logs:

```
Error from the agent http API server: http: TLS handshake error from 10.0.XXX.XXX:XXXX: EOF
```

This happened around 45.000 times in the space of one week.
The call itself relates to port 5005 of the cluster agent, when the agent communicates with the cluster agent over TLS.

This is printed by the `datadog-cluster-agent`. However, after doing some tests of changing the image tag names for both the agent and the cluster agent, it seems that the problem occurs only on 7.35.+ version of the standard agent image.

Cluster Agent is on 1.19.0 and agent on 7.35.2.

It might be some sort of regression issue?
Thanks.

**Comment by th0masb** [comment]
I also observe this behaviour with cluster-agent 1.19.0 and agent 7.35.2 with a GKE cluster on 1.22.8. My helm config looks like

 ```yaml
# Helm values for datadog agent chart
# Source: https://github.com/DataDog/helm-charts/blob/main/charts/datadog/values.yaml
datadog:
  apiKey: ${api_key}
  site: datadoghq.eu
  clusterName: ${cluster_name}
  logLevel: critical
  # kube-state-metrics don't seem to play nicely with 1.22
  # and is considered a legacy service which is not needed
  # going forward
  # https://docs.datadoghq.com/integrations/kubernetes_state_core
  kubeStateMetricsEnabled: false
  kubeStateMetricsCore:
    enabled: true
  logs:
    enabled: true
    containerCollectAll: true
  kubelet:
    tlsVerify: false
  env:
    # The logs from gke system pods can be noisy and contain lots of errors.
    # We don't really care about them as we trust gke will work.
    - name: DD_CONTAINER_EXCLUDE
      value: "kube_namespace:kube-system"
```

**Comment by sharonx** [comment]
I'm seeing this issue too that started about 4 days ago. Any quick remediation steps?

**Comment by michelzanini** [comment]
> I'm seeing this as well, is it causing your pods to crashloop?

It's not crashing the pods or anything like that, just printing the error on logs. I am not sure on the impact the error causes. I have not noticed any differences so far.

**Comment by sharonx** [comment]
>I'm seeing this as well, is it causing your pods to crashloop?

We have 1 pod that's in crashloop which is caused by the trace-agent error
```
  - containerID: docker://d5cfac4026a0279810700b165d5d9f8601ed2025f724d536cef25760e29b140d
    image: gcr.io/datadoghq/agent:7.32.3
    imageID: docker-pullable://gcr.io/datadoghq/agent@sha256:706a9e65a8c82872e8f8165830387c0af5d9785774cebf44dd29121a5907e3ea
    lastState:
      terminated:
        containerID: docker://d5cfac4026a0279810700b165d5d9f8601ed2025f724d536cef25760e29b140d
        exitCode: 143
        finishedAt: "2022-05-24T17:16:46Z"
        reason: Error
        startedAt: "2022-05-24T17:15:52Z"
    name: trace-agent
    ready: false
    restartCount: 11
    started: false
    state:
      waiting:
        message: back-off 5m0s restarting failed container=trace-agent pod=datadog-agent-m7ljq_datadog(ae681201-11fb-4a75-9f3c-558c2f8d5c05)
        reason: CrashLoopBackOff
```
