### ISSUE TITLE
prometheus_scrape.checks fails to parse metrics list

### ISSUE THREAD

**Issue by sschepens** [DataDog/datadog-agent#12317]
**Describe what happened:**
According to documentation, Prometheus checks allow to specify metrics as:
- list of strings
- list of key-value pairs for renaming metrics
- list of key -> object, specifying name, type and other properties to further customize metrics

But when configuring checks with Helm using `prometheusScrape.additionalConfigs` (which translates to `DD_PROMETHEUS_SCRAPE_CHECKS` env variable in the agents) , the parsing fails and only allows a list of strings.

Example:
```yaml
      prometheusScrape:
        enabled: true
        additionalConfigs:
        - configurations:
            metrics:
            - foo: bar
           autodiscovery:
             kubernetes_container_names:
             - foo
```
Or:
`DD_PROMETHEUS_SCRAPE_CHECKS=[{"autodiscovery":{"kubernetes_container_names":["foo"]},"configurations":[{"metrics":[{"foo":"bar"}]}]}]`

In `agent config` we can see this is forced as a list of strings and ends up as an empty string:
```
  - configurations:
    - metrics:
      - ""
    autodiscovery:
      kubernetes_container_names:
      - foo
```

I think this is because Metrics si defined as a []string in [this struct](https://github.com/DataDog/datadog-agent/blob/main/pkg/autodiscovery/common/types/prometheus.go#L68).

From what I understand, there's no actual reason why we want to even parse Metrics, since this prometheus instances are later transformed to JSON again [here](https://github.com/DataDog/datadog-agent/blob/main/pkg/autodiscovery/common/utils/prometheus.go#L52) for usage in the Agent.

If my understanding is correct, we could migrate Metrics to type `json.RawMessage` to just skip parsing this, and delegate this to the prometheus check.
Another approach would be to have multiple structs with different possible types and try to parse every possible case, but this is not ideal.
