### ISSUE TITLE
Could not set source in Kubernetes yaml

### ISSUE THREAD

**Issue by rsun-thoughtworks** [DataDog/datadog-agent#12754]
Datadog Agent version: 7.32.4
Cluster: Azure AKS

What happen:

Try to assign source to csharp by

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxx-deployment
  namespace: dev
  labels:
    app: DemoManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DemoManagement
  template:
    metadata:
      labels:
        app: DemoManagement
        tags.datadoghq.com/env: "dev"
        tags.datadoghq.com/service: "demo-service"
        tags.datadoghq.com/version: "xxxx"
        tags.datadoghq.com/source: "csharp"
xxxxxxxxxxxxxxxxxxxxxxx
```

But what we found in datadog logs is that
Source: demo_management

Expected Behavior:

Source: csharp
