### ISSUE TITLE
prometheusScrape autodiscovery with additionalConfigs of send_monotonic_counter: false does not work with prometheusScrape version 2

### ISSUE THREAD

**Issue by harold-kfuse** [DataDog/datadog-agent#12775]
**Output of the info page (if this is a bug)**
```
(Paste the output of the info page here)
```

**Describe what happened:**

I installed datadog agent thru helm chart. I enabled prometheusScrape in my helm values.yaml:

```
prometheusScrape:
    enabled: true
    additionalConfigs:
      - configurations:
        - send_monotonic_counter: false
          send_distribution_counts_as_monotonic: false
          send_distribution_sums_as_monotonic: false
          send_histograms_buckets: true
          max_returned_metrics: 999999
          min_collection_interval: 15
```

I noticed that the prometheus counters are still sent as datadog counters (so they are sent as "deltas") instead of gauge type even when I added `send_monotonic_counter: false` in the helm values.

This is what I see when I run `agent configcheck`

```
=== openmetrics check ===
Configuration provider: prometheus-pods
Configuration source: prometheus_pods:docker://db1b3dcaabca6348dd79f62af4f2920b86789352b1c9a31c19d9272717be7e95
Instance ID: openmetrics:358db823feb4e495
max_returned_metrics: 999999
metrics:
- .*
min_collection_interval: 15
namespace: ""
openmetrics_endpoint: http://10.40.2.125:8090/metrics
send_histograms_buckets: true
send_monotonic_counter: false
tags:
<snipped>
```

As I was playing with the configs, when I explicitly specify the prometheusScrape.version = 1, I do see the prom counters sent as gauge.

```
prometheusScrape:
    enabled: true
    version: 1
    additionalConfigs:
      - configurations:
        - send_monotonic_counter: false
          send_distribution_counts_as_monotonic: false
          send_distribution_sums_as_monotonic: false
          send_histograms_buckets: true
          max_returned_metrics: 999999
          min_collection_interval: 15
```

**Describe what you expected:**

I expected prometheus counter to be sent as gauge type.

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**
