### ISSUE TITLE
Im using the daemonset deployed with the official helm chart. Why am I seeing "Reached the limit on the maximum number of files in use: 100" errors?

### ISSUE THREAD

**Issue by red8888** [DataDog/datadog-agent#12862]
When I look at the agent daemonset logs I see this:
` | CORE | WARN | (pkg/logs/internal/launchers/file/file_provider.go:87 in filesToTail) | Reached the limit on the maximum number of files in use: 100`

Is that a problem? It should be reading from stdout right? Why is the daemonset throwing this error?

**Additional environment details (Operating System, Cloud provider, etc):**
```
  labels:
    app.kubernetes.io/component: agent
    app.kubernetes.io/instance: datadog-agent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: datadog-agent
    app.kubernetes.io/version: "7"
    helm.sh/chart: datadog-2.35.6
```
