### ISSUE TITLE
helm DD_SITE vs site config inconsistant behavior

### ISSUE THREAD

**Issue by iampluque** [DataDog/datadog-agent#12996]
I'm posting the issue here since we are using a fixed helm chart version.

Since yesterday (august 3th, 2022) around 10 am (EST), logs ingestion stop working with only the DD_SITE env variable set in helm chart version 2.34.2 with the following error ...

`2022-08-03 20:31:12 UTC | CLUSTER | ERROR | (pkg/forwarder/transaction/transaction.go:348 in internalProcess) | API Key invalid, dropping transaction for https://orchestrator.datadoghq.com/api/v2/orch`

Our account is configured on `us5`
Our api key is still valid

When we add `site: us5.datadoghq.com` it starts processing logs 

**failing config**
```yaml
env:
  - name: DD_SITE
    value: us5.datadoghq.com
```

**working config**
```yaml
site: us5.datadoghq.com
env:
  - name: DD_SITE
    value: us5.datadoghq.com
```

maybe related #6066
