### ISSUE TITLE
Apply DD_TAG to kube-state-metrics v2

### ISSUE THREAD

**Issue by kteague-tasktop** [DataDog/datadog-agent#13045]
When collecting metrics from kube-state-metrics v2 with the datadog agent, the DD_TAG does not seem to apply to those metrics.

Something like this:

```
datadog:
  kubeStateMetricsEnabled: false
  tags:
    - test:foo
  kubeStateMetricsCore:
    enabled: true
```

Which sets the `DD_TAG: test:foo` can be seen tagged in various metrics datadog collects, is not applied to the collected kube-state-metrics v2.
