### ISSUE TITLE
configure datadog logs with docker labels

### ISSUE THREAD

**Issue by mathroc** [DataDog/datadog-agent#1320]
>>> this part is not relevant anymore:

I upgraded to datadog agent 6, in order to give a try to the datadog logs beta and since then I’m not able to use docker labels to configure the agent:

I used to have this config in docker-compose.yml:

```yaml
  db:
    image: postgres:10
    volumes:
      - db:/var/lib/postgresql/data:rw
    labels:
      com.datadoghq.ad.check_names: '["postgres"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: '[{"host": "ws_db", "port": 5432, "username": "$DATADOG_POSTGRES_USER", "password": "$DATADOG_POSTGRES_PASSWORD", "tags": ["app:ws"]}]'
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - datadog
      - default
```

but this does not work anymore. I guess this is a feature not yet ported to this agent but can anyone confirm this ? or has the configuration format change ?

bonus:

>>> this part is still relevant:

should that kind of configuration work for datadog logs ? (once implemented)

```yaml
  db:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
    volumes:
      - db:/var/lib/postgresql/data:rw
      - logs:/logs:rw
    labels:
      com.datadoghq.ad.check_names: '["postgres"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: '[{"host": "ws_db", "port": 5432, "username": "$DATADOG_POSTGRES_USER", "password": "$DATADOG_POSTGRES_PASSWORD", "tags": ["app:ws"]}]'
      com.datadoghq.ad.logs: '{"type": "file", "path": "/logs/beesquad/*-ws.db.log", "tags": ["app:ws"], "source": "postgresql", "service": "ws", "sourcecategory": "database", "log_processing_rules": {"type": "multi_line", "pattern": "\d{4}\-(0?[1-9]|1[012])\-(0?[1-9]|[12][0-9]|3[01])", "name": "new_log_start_with_date"}}'
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    command: >
      -c logging_collector=on
      -c log_directory=/logs/beesquad/
      -c log_filename='%Y-%m-%d-ws.db.log'
      -c log_statement=all
      -c log_line_prefix='%m [%p] %d %a %u %h %c '
      -c log_file_mode=0664
    networks:
      - datadog
      - default
```

thank you
