### ISSUE TITLE
Kubernetes tags are missing in custom events through Unix Domain Socket from pods

### ISSUE THREAD

**Issue by duncan-xfers** [DataDog/datadog-agent#13254]
We have datadog installed using helm with version=2.37.4 and the `values.yaml` below. 
```
# Check the GitHub to know what the attributes mean
# https://github.com/DataDog/helm-charts/tree/main/charts/datadog
datadog:
  apiKeyExistingSecret: datadog-credential
  appKeyExistingSecret:  datadog-credential

  nodeLabelsAsTags:
    beta.kubernetes.io/instance-type: aws-instance-type

  collectEvents: true

  prometheusScrape:
    enabled: true

  leaderElection: true

  logs:
    enabled: true
    containerCollectAll: true

  processAgent:
    enabled: true

  dogstatsd:
    useHostPort: true
    nonLocalTraffic: true

  apm:
    portEnabled: true

  confd:
    docker.yaml: |-
      init_config:
      instances:
        - # Collect disk usage per container with docker.container.size_rw and docker.container.size_rootfs metrics.
          # Default to false.
          #
          collect_container_size: true
          #
          # Set the frequency of collection of disk container size
          collect_container_size_frequency: 60

  # ref: https://docs.datadoghq.com/agent/docker/?tab=standard#environment-variables
  # ref: https://docs.datadoghq.com/containers/kubernetes/configuration#environment-variables
  env:
    - name: DD_CONTAINER_EXCLUDE_LOGS
      value: "image:datadog/agent"
    - name: DD_PROCESS_AGENT_ENABLED
      value: "true"
    - name: DD_CLUSTER_NAME
      value: "playground"

  # Needed for K8s version >= 1.22
  # https://github.com/DataDog/helm-charts/issues/415
  kubeStateMetricsEnabled: false # to avoid deploying kube-state-metrics chart
  kubeStateMetricsCore:
    enabled: true

agents:
  enabled: true
  containers:
    initContainers:
      resources:
        requests:
          cpu: 120m
          memory: 140Mi
        limits:
          cpu: 120m
          memory: 140Mi
    agent:
      resources:
        requests:
          cpu: 150m
          memory: 250Mi
        limits:
          cpu: 150m
          memory: 250Mi
    traceAgent:
      resources:
        requests:
          cpu: 100m
          memory: 130Mi
        limits:
          cpu: 100m
          memory: 130Mi
    processAgent:
      resources:
        requests:
          cpu: 22m
          memory: 95Mi
        limits:
          cpu: 22m
          memory: 95Mi

clusterAgent:
  enabled: true
  metricsProvider:
    enabled: true
    useDatadogMetrics: true
  admissionController:
    enabled: true
    mutateUnlabelled: true
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 256Mi

```

Then I run a pod with the manifest below.
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: playground-custom-event
    tags.datadoghq.com/env: "playground"
    tags.datadoghq.com/service: "playground-custom-event"
    tags.datadoghq.com/version: "0.1.0"
  name: playground-custom-event
  namespace: default
spec:
  volumes:
    - name: dsdsocket
      hostPath:
        path: /var/run/datadog/
  containers:
    - name: ubuntu
      image: ubuntu
      command:
        - sleep
      args:
        - infinity
      volumeMounts:
        - name: dsdsocket
          mountPath: /var/run/datadog
      env:
        - name: DD_API_KEY
          valueFrom:
            secretKeyRef:
              name: datadog-credential
              key: api-key
  restartPolicy: Never

```

And then I run the commands below to send a custom event from the pod.
```
k exec -it -n=default playground-custom-event -- bash

apt-get update && apt-get install -y ncat

title="Test Event from the shell"
text="This was sent from sh"

echo "_e{${#title},${#text}}:$title|$text|s:kubernetes|t:error|#entity_id:$DD_ENTITY_ID" \
  | nc -U -u -w1 /var/run/datadog/dsd.socket
```

The event had been successfully sent but Kubernetes tags were missing. I expect to see in tags like `image_name`, `env`, `version`, `service`, `kube_namespace`, `kube_container_name`, `pod_phase` listed in [Kubernetes Tag Extraction](https://docs.datadoghq.com/containers/kubernetes/tag/?tab=containerizedagent#out-of-the-box-tags)
![image](https://user-images.githubusercontent.com/84693630/186897113-fd9bd02e-a76d-4d3c-93fb-ef6d430dc43c.png)

Is it a bug or my misconfiguration and how do I make Kubernetes tags added to the event?

Thanks~

**Comment by duncan-xfers** [comment]
It's the misconfiguration in the DataDog helm chart. The following values need to be set to true.
```
datadog:
  dogstatsd:
    originDetection: true
    useHostPID: true
```
