### ISSUE TITLE
[BUG] Are Windows File shares mounts supported for Datadog Linux container?

### ISSUE THREAD

**Issue by edisga** [DataDog/datadog-agent#13278]
**Describe what happened:**
Mounting to Windows File shares using Docker Windows WSL is failing with this configuration:

```
 volumes:
     - C:/temp1:/host/proc
     - C:/temp2:/var/run/docker.sock
     - C:/temp3:/host/sys/fs/cgroup
     - C:/temp4:/sys/kernel/debug
     - C:/temp5:/var/lib/docker/containers
```
It is not finding this file, which it is not in the Windows Host mounting point. 
`(pkg/metadata/host/host_notwin.go:85 in getHostInfo) | failed to retrieve host info: open /host/proc/stat: no such file or directory`

**Describe what you expected:**
This is working on a Linux Host mounting Linux path. Is this supported to work with Linux containers and using Windows File shares as volumes? 

**Steps to reproduce the issue:**

```
version: "3.7"
services:
  test-service:
    image: testimage:tag
    ports:
     - "3000:3000"
    environment:
     - DD_AGENT_HOST=datadog-agent 

  datadog-agent:
    image: datadog/agent:latest
    ports:
     - "8126:8126"
    environment:
     - DD_API_KEY=xxxx
     - DD_APM_ENABLED=true
     - DD_SITE=xxx
     - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
     - DD_APM_NON_LOCAL_TRAFFIC=true
     - DD_TRACE_ENABLED=true
     - DD_LOGS_INJECTION=true
     - DD_LOGS_ENABLED=true
    volumes:
     - C:/temp1:/host/proc
     - C:/temp2:/var/run/docker.sock
     - C:/temp3:/host/sys/fs/cgroup
     - C:/temp4:/sys/kernel/debug
     - C:/temp5:/var/lib/docker/containers
```

**Additional environment details (Operating System, Cloud provider, etc):**
Docker Windows + Windows File Share
