### ISSUE TITLE
/conf.d is not used for logging

### ISSUE THREAD

**Issue by mattwilliamson** [DataDog/datadog-agent#1333]
https://github.com/DataDog/datadog-agent/tree/master/Dockerfiles/agent is saying to mount a volume to `/conf.d/` but when trying to start the `datadog/agent:latest` docker image, I see the following output:

```
[ AGENT ] 2018-02-22 17:06:35 UTC | ERROR | (start.go:220 in StartAgent) | Could not start logs-agent: could not find any valid logs configuration file in /etc/datadog-agent/conf.d
```

**Comment by xvello** [comment]
Hi @mattwilliamson ,

Indeed, *.yaml files are copied, see https://github.com/DataDog/datadog-agent/blob/master/Dockerfiles/agent/entrypoint/89-copy-customfiles.sh

Could you please post the yaml file you exposed in the container, so @NBParis can have a look at its syntax?

**Comment by AGutan** [comment]
Getting the same error.

docker-compose
```
  datadog:
    container_name: dd-agent
    image: datadog/agent:latest
    links:
     - kafka
     - zookeeper
     - influxdb
     - grafana
    environment:
     - DD_HOSTNAME=ddhostname
     - DD_API_KEY=<<secret key>>
     - NON_LOCAL_TRAFFIC=true
     - DD_APM_ENABLED=true
     - DD_LOGS_ENABLED=true
     - DD_PROCESS_AGENT_ENABLED=true
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
     - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
     - /opt/datadog-agent/conf.d:/conf.d:ro
```

/opt/datadog-agent/conf.d/docker.d/conf.yaml
```
logs:
    - type: docker
      service: docker
```
Anything I'm missing?
