### ISSUE TITLE
[BUG] Injecting multiple language tracers into one container does not work

### ISSUE THREAD

**Issue by nilushancosta** [DataDog/datadog-agent#14182]
**Agent Environment**
Datadog Cluster Agent (v7.40.0)

**Describe what happened:**
I followed the document in https://docs.datadoghq.com/tracing/trace_collection/admission_controller/#annotate-your-pods to add multiple language tracers into one container in Kubernetes.

The pod definition I used is as follows
```
apiVersion: v1
kind: Pod
metadata:
  name: datadog-apm-test
  annotations:
    admission.datadoghq.com/js-lib.version: "latest"
    admission.datadoghq.com/java-lib.version: "latest"
    admission.datadoghq.com/python-lib.version: "latest"
  labels:
    admission.datadoghq.com/enabled: "true"
    tags.datadoghq.com/env: "dev"
    tags.datadoghq.com/service: "apmtest"
    tags.datadoghq.com/version: "1.0.0"
spec:
  containers:
  - name: service-container
    image: <image>
    ports:
    - containerPort: 8080
```

When I created a Pod using this, the admission controller added an init-container named `datadog-lib-init` which uses the image `datadoghq/dd-lib-java-init` to the pod. 

When I Exec'ed into the container and checked the contents of `/datadog-lib`, only `dd-java-agent.jar` was there in it. 
Although I added 3 annotations, there were no language tracers for other languages in this directory.

I also noticed that this doesn't seem to be an issue where tracer injection for the other languages are not working.
I modified the Pod defintion to only have the `admission.datadoghq.com/python-lib.version: "latest"` annotation. When I created a Pod from this, an init-container using the `datadoghq/dd-lib-python-init` image was created.
Then when I checked the contents of `/datadog-lib` mount, `sitecustomize.py` was there.

So it seems that the admission controller is taking into account only 1 annotation. 

**Describe what you expected:**
I expected to see multiple language tracers in the container 

**Steps to reproduce the issue:**
1. Use the above pod definition and create a pod

**Additional environment details (Operating System, Cloud provider, etc):**
I installed the Datadog agent using Helm. The chart version is `datadog-3.2.0`
