### ISSUE TITLE
Custom file logging not working when logs come from a non integration source file

### ISSUE THREAD

**Issue by adragoset** [DataDog/datadog-agent#1471]
https://docs.datadoghq.com/logs/#custom-log-collection

Under the custom file section the user is instructed to create a config.yaml and place it in 

custom-integration-name.d/conf.yaml 

```
init_config:

instances:
    [{}]

logs:
  - type: file
    path: some/file/path
    service: custom-integration-name
    source: custom-integration-name
```

However folders placed into conf.d and mounted do not get copied into /etc/datadog-agent/conf.d/

If the user names the config file custom-integration-name.yaml and places it into /conf.d thats mounted datadog then throws an error 

```
Datadog's nomad_forwarder integration is reporting:
Instance #initialization[ERROR]:{"Core Check Loader":"Check custom-integration-name not found in Catalog","JMX Check Loader":"check is not a jmx check, or unable to determine if it's so","Python Check Loader":"No module named custom-integration-name"}
```

If the user is not using an existing integration and just wants to tail the file  it does not look like this is possible.
