### ISSUE TITLE
DD metric reports are too slow when defining roll up() function

### ISSUE THREAD

**Issue by karl18** [DataDog/datadog-agent#14751]
Hi

We're using AKS, and we define Datadog external metric as the following:
`p90:trace.aspnet_core.request{env:ENV,service:SERVICE_NAME}.rollup(300)`

we tackled all the errors which I have been getting before by defining in the Cluster Agent the following envs: 
```           
- name: DD_EXTERNAL_METRICS_PROVIDER_MAX_AGE
   value: '1200'
- name: DD_EXTERNAL_METRICS_PROVIDER_BUCKET_SIZE
   value: "1200"
 ```

seems to remove any errors we saw before, however we see the update of the latency value logs are reporting too slow, and even is directly proportional with the number of seconds we define in roll-up(number_in_seconds)

so for example, if we put rollup(15) we get a reported value of the metric in AKS after 15 seconds, If we put some huge number like roll up(600) we get the update after 10 mins , etc ..

Our Datadog metric:

```
kind: DatadogMetric
metadata:
  name: $SERVICE_NAME
  namespace: $CLUSTER_NAMESPACE
spec:
  query: p90:trace.aspnet_core.request{env:ENV, service:SERVICE_NAME}.rollup(300)
```

Our HPA:

```
kind: HorizontalPodAutoscaler
metadata:
  name: $SERVICE_NAME
  namespace: $CLUSTER_NAMESPACE
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  $SERVICE_NAME
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: External
    external:
      metricName: datadogmetric@$CLUSTER_NAMESPACE:$METRIC_NAME
      metricSelector:
        matchLabels:
           env: ENV
           service: SERVICE_NAME
     targetValue: 0.000015
```

So Is this behavior is what we should expect? How could we overcome the time waiting for reported value ?

Any help is appreciated. :-)
