### ISSUE TITLE
[BUG] Container creates a st-vector container, without consent, st-vector creates a volume EVERY TIME IT STARTS but is never used (always 8kb)

### ISSUE THREAD

**Issue by LostOnTheLine** [DataDog/datadog-agent#14872]
**Agent Environment**

Windows Docker Desktop on WSL2
```yaml
  dd-agent:
    image: 'datadog/agent:latest'
    #image: gcr.io/datadoghq/agent:7
    container_name: dd-agent
    environment:
      - TZ=America/Phoenix
      - DD_API_KEY={{{REDACTED}}}
      - DD_SITE=us5.datadoghq.com
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_ENABLED=true
      - DD_PROCESS_AGENT_ENABLED=true
    ports:
      - 8125:8125/udp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /d/docker/log/var/log/datadog:/var/log/datadog
      - /d/docker/log/datadog/lib/vector:/var/lib/vector
    restart: always
    security_opt:
      - no-new-privileges:true
    labels:
      - "com.centurylinklabs.watchtower.scope=dockerhub"
```
**Describe what happened:**
I discovered I had over 100 volumes, almost all size 8kb (Empty) & I discovered 2 of them were currently in use by `DataDog` & `st-vector`. 

I discovered that when I stopped DataDog `st-vector` did not stop, but if I removed it it's volume & container would be recreated when DataDog started.

Stopping & restarting these created **_NEW_** volumes every time, defeating the entire _point_ of a volume. 

Mapping `/var/log` to a BindMount did not work & the volume for that was still created, even though `/var/log/datadog`, the point it the volume was mapped to, already existed.
Mapping `/var/log/datadog` prevented it from being created.

The other, however, seems to have a LOT of system access, & doesn't respect the `no-new-privileges:true` or recognize the `/var/lib/vector`, it's mount directory, in the Docker-Compose. This security threat installs itself without user consent or even informing of it. 

I tried deleting the `st-vector` container &, with datadog stopped, creating a new container with the same settings except a BondMount for `/var/lib/vector` but when datadog starts it replaces it with the dumb one. I switched between the DockerHub & Google repositories for DataDog, but the `st-vector` ALWAYS comes from Google. `no-new-privileges:true` true, false, or removed has the same result.

These volumes, being replaced by a new one each startup **serve no purpose**. I'm sure they will fill up with stuff when I have the agent fully setup, but as they get replaced each time it starts that would be the same as if the volume didn't exist at all. There is no way 

**Describe what you expected:**
To be asked or at least informed when a container is going to be created, especially one with such system access & to be able to control the level of access it has

To be able to bypass any volumes set in a Docker-Compose/Docker Run

For volumes to ONLY exist when needed to preserve persistent data & those volumes to be used on subsequent startups of the container.

**Steps to reproduce the issue:**
Use the software, stop & start it as well as `st-vector`

**Additional environment details (Operating System, Cloud provider, etc):**
