### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ethanresnick** [DataDog/datadog-agent#14921]
**Agent Environment**
Kubernetes cluster agent, installed via helm.

Agent version: 7.41.1

The relevant snippet of my helm values is:

```yaml
datadog:
  otlp:
    receiver:
      protocols:
        grpc:
          enabled: true
agents:
  containers:
    traceAgent:
      env:
        # I have a large set of remappings for removing the auto-instrumentation
        # library name boilerplate. Only an example shown here.
        - name: DD_OTLP_CONFIG_TRACES_SPAN_NAME_REMAPPINGS
          value: '{"@opentelemetry/instrumentation-pg.client":"pg.client","@opentelemetry/instrumentation-pg.server": "pg.server"}'
```

**Describe what happened:**

I'm sending traces from a Nodejs app to the Datadog agent's OLTP endpoint, via grpc, using the standard Nodejs Open Telemetry SDK. In some of my spans, I add `operation.name` and `resource.name` attributes, in order to improve the appearance/capabilities of the span in the Datadog UI. When my span has _only_ `operation.name` and `resource.name` as attributes, this works perfectly. However, as soon as I add another attribute to the span (regardless of the attribute name), the spans `resource.name` and `operation.name` tags are ignored, and the spans instead have the Otel span name used as the resource name, while the operation name is formed with the library name + span kind. 

**Describe what you expected:**
I expected `operation.name` and `resource.name` to be respected, just like when there are no other attributes.

**Steps to reproduce the issue:**
I don't have a simple, extracted reproducible example yet, though I can try to put one together. (What's the easiest way to do this?) In the meantime, I was hoping that the description above might be enough for someone who knows this code better than I do to recognize what's wrong.

**Additional environment details (Operating System, Cloud provider, etc):**
AWS, EKS,
