### ISSUE TITLE
Support for multi_line log processing for journald logs

### ISSUE THREAD

**Issue by joshprice88** [DataDog/datadog-agent#15045]
For applications that log to journald, multi_line processing rules seem to be ignored when configured in /etc/datadog-agent/conf.d/journald.d/conf.yaml with the following configuration.
```
logs:
  - type: journald
    config_id: journald
    path: /var/log/journal
    exclude_units:
      - datadog-agent.service
    exclude_matches:
      - CONTAINER_NAME=python-logger
  - type: journald
    config_id: python-logger
    source: docker
    service: python-logger
    path: /var/log/journal
    include_matches:
      - CONTAINER_NAME=python-logger
    log_processing_rules:
      - type: multi_line
        name: new_log_start_with_date
        pattern: \d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}\.\d{3}
```
Logs flow to datadog, but multi-line logs are not consolidated.  I could not find documentation indicating multi_line log processors are not supported for journald logging, and other log_processing_rules types(such as exclude_at_match) tested do seem to work as expected.
