### ISSUE TITLE
PrometheusScrape - Unable to collect configurations from provider (Upgrading from 3.3.0 to 3.10)

### ISSUE THREAD

**Issue by agarciahumanes** [DataDog/datadog-agent#15699]
Hello there, we were using datadog **helm charts 3.3.0** and both **agent** and **cluster-agent** **7.40.1** version.

Our code looks like this when it comes to scrapping with prometheus:

```
prometheusScrape:
  enabled: true
  serviceEndpoints: true

  additionalConfigs:
    - configurations:
        - tags:
          - "source_type:custom-openmetrics"
          openmetricsConfig:
            max_returned_metrics: 5000
      autodiscovery:
        kubernetes_annotations:
          include:
            datadog-openmetrics-check: "true"
          exclude:
            datadog-openmetrics-check: "false"
```

Worked like a charm, but then we upgrade to one of the latest versions **3.10.6** and **7.42.0** ,these issues start happening, they all look identical

`UTC | CLUSTER | ERROR | (pkg/autodiscovery/config_poller.go:211 in collect) | Unable to collect configurations from provider prometheus-services: endpoints "schema-api" not found` only difference is the endpoint name

We've tried few more versions and issues are there. They seem to be fixed if we choose 3.6.7 or lower versions, but since the values.yaml structure is the same across versions, we don't know what's the issue or how can we fix it in order to use latest version.
