### ISSUE TITLE
[BUG] Getting `external.metrics.k8s.io/v1beta1: Got empty response for: external.metrics.k8s.io/v1beta1`

### ISSUE THREAD

**Issue by gdubicki** [DataDog/datadog-agent#15934]
**Agent Environment**

agent version: 7.38.2
deployed with the helm chart: 2.37.9
in a k8s cluster (more info at the bottom)

**Describe what happened:**

I am getting an error/warning when I run any kubectl command on a cluster that has datadog deployed:
```
E0302 18:01:45.684553    1989 memcache.go:255] couldn't get resource list for external.metrics.k8s.io/v1beta1: Got empty response for: external.metrics.k8s.io/v1beta1
```

Example:
```
$ kubectl get pod foo
E0302 18:01:45.684553    1989 memcache.go:255] couldn't get resource list for external.metrics.k8s.io/v1beta1: Got empty response for: external.metrics.k8s.io/v1beta1
Error from server (NotFound): pods "foo" not found
```

Usually it behaves like a warning, not causing any trouble except for the noise, but sometime it seems to be dealbreaker.

Example, when trying to run https://github.com/derailed/popeye tool:

```
$ popeye
E0302 17:56:47.154757    1231 memcache.go:255] couldn't get resource list for external.metrics.k8s.io/v1beta1: Got empty response for: external.metrics.k8s.io/v1beta1
 ___     ___ _____   _____                       D          .-'-.
| _ \___| _ \ __\ \ / / __|                       O     __| K    `\
|  _/ _ \  _/ _| \ V /| _|                         H   `-,-`--._   `\
|_| \___/_| |___| |_| |___|                       []  .->'  X     `|-'
  Biffs`em and Buffs`em!                            `=/ (__/_       /
                                                      \_,    `    _)
                                                         `----;  |


Boom! 💥 unable to retrieve the complete list of server APIs: external.metrics.k8s.io/v1beta1: Got empty response for: external.metrics.k8s.io/v1beta1
```

**Describe what you expected:**

No warning/errors.

**Steps to reproduce the issue:**

1. run `kubectl get foo`

**Additional environment details (Operating System, Cloud provider, etc):**

```
$ kubectl version --short
(...)
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.23.14-gke.1800
```

Cloud Provider/Platform (AKS, GKE, Minikube etc.): GKE

**Comment by gdubicki** [comment]
A workaround: https://github.com/kubernetes/kubernetes/pull/115978

**Comment by remyduthu** [comment]
+1

**Comment by bt-macole** [comment]
This gets resolved if you use external.metrics with custom metrics in an hpa.

ex DD agent config

```yaml
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: datadog-system
spec:  
  global:
    clusterName: example
    credentials:
      apiSecret:
        keyName: api-key
        secretName: datadog-secret
      appSecret:
        keyName: app-key
        secretName: datadog-secret
  override:
    nodeAgent:
      containers:
      env:
      - name: DD_HOSTNAME_FILE
        value: /var/lib/cloud/data/instance-id
      - name: DD_COLLECT_GCE_TAGS
        value: "false"
      tolerations:
      - operator: Exists
  features:
    clusterChecks:
      enabled: true
    externalMetricsServer:
      enabled: true
      useDatadogMetrics: true
      endpoint:
        credentials:
          apiSecret:
            keyName: api-key
            secretName: datadog-secret
          appSecret:
            keyName: app-key
            secretName: datadog-secret
    kubeStateMetricsCore:
      conf:
        configMap:
          name: kubernetes-state-core-confd
      enabled: true
```

external.metrics resources are empty, this will give you the warning if you `kubectl api-resources`

can see its empty with:
```bash
kubectl get --raw /apis/external.metrics.k8s.io/v1beta1
{"kind":"APIResourceList","apiVersion":"v1","groupVersion":"external.metrics.k8s.io/v1beta1","resources":[]}
```

add hpa for external.metrics following this guide: https://www.datadoghq.com/blog/autoscale-kubernetes-datadog/

```yaml
apiVersion: "rbac.authorization.k8s.io/v1"
kind: ClusterRole
metadata:
  labels: {}
  name: datadog-cluster-agent-external-metrics-reader
rules:
  - apiGroups:
      - "external.metrics.k8s.io"
    resources:
      - "*"
    verbs:
      - list
      - get
      - watch
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: ClusterRoleBinding
metadata:
  labels: {}
  name: datadog-cluster-agent-external-metrics-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: datadog-cluster-agent-external-metrics-reader
subjects:
  - kind: ServiceAccount
    name: horizontal-pod-autoscaler
    namespace: kube-system
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: nginxext
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  metrics:
  - type: External
    external:
      metricName: nginx.net.request_per_s
      metricSelector:
        matchLabels:
            kube_container_name: nginx
      targetAverageValue: 9
 ```

check exteranl metrics again

```bash
kubectl get --raw /apis/external.metrics.k8s.io/v1beta1 | jq '.'
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "external.metrics.k8s.io/v1beta1",
  "resources": [
    {
      "name": "nginx.net.request_per_s",
      "singularName": "",
      "namespaced": true,
      "kind": "ExternalMetricValueList",
      "verbs": [
        "get"
      ]
    }
  ]
}
```

no more warning
```bash
kubectl api-resources | grep unable
echo $?
1
```
