### ISSUE TITLE
[BUG] Unable to configure multiple external metrics with the same label but different label values

### ISSUE THREAD

**Issue by Timothy-Dougherty** [DataDog/datadog-agent#16127]
Hi, we are trying to configure a HPA with external metrics. We'd like to be able to use the same metric but reference different label values. however the datadgo-agent only uniquely identifies metrics by the labels and not the values assigned to those labels, meaning only one of the metrics with the same label will be reported.

**Agent Environment**

```Cluster agent 1.18.0 - Commit: '78e3126' - Serialization version: v5.0.9```
**Describe what happened:**
configured a HPA with multiple external metrics referencing the same label but with different values:
```
  - external:
      metric:
        name: some.metric
        selector:
          matchLabels:
            same_label: avalue
            cluster: sandbox
      target:
        type: Value
        value: 2k
    type: External
  - external:
      metric:
        name: some.metric
        selector:
          matchLabels:
            same_label: adifferentvalue
            cluster: sandbox
      target:
        type: Value
        value: 2k
```
when the datadog-agent trys to retrieve the values for both it fails for one as it cannot uniquely identify it and the currentMetrics field gets filled in with a blank value:
```
currentMetrics:
  - type: ""
  - external:
      current:
        value: "0"
      metric:
        name: some.metric
        selector:
          matchLabels:
            same_label: adifferentvalue
            cluster: sandbox
    type: External
```

The hpa then reports a failure to get the external metric:
```
'the HPA was unable to compute the replica count: unable to get external
      metric some.metric/&LabelSelector{MatchLabels:map[string[]string{same_label: avalue,cluster: sandbox,},MatchExpressions:[]LabelSelectorRequirement{},}:
      no metrics returned from external metrics API'
```
**Describe what you expected:**
I expected both metrics to be retrieved correctly.

**Steps to reproduce the issue:**
create a HPA with an external metric referring to the same metric with the same labels but a different value assigned to one of them.

**Additional environment details (Operating System, Cloud provider, etc):**
