### ISSUE TITLE
[BUG] Error in external metric with a specific label, with others it works

### ISSUE THREAD

**Issue by dcristobalhMad** [DataDog/datadog-agent#16209]
**Agent Environment**

`gcr.io/datadoghq/cluster-agent:7.40.1`

**Describe what happened:**

To create a hpa and scale based on a datadog metric, it is necessary to use labels so that the target is the service of the application. The problem is that it works with some labels and not with others. In this case we are using metrics that are provided by traefik.

**Describe what you expected:**

Get values from external metric with specific label

**Steps to reproduce the issue:**

HPA:
```
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: test
  namespace: staging-test
spec:
  maxReplicas: 4
  metrics:
    - type: External
      external:
        metric:
          name: traefik.service.request.duration.max
          selector:
            matchLabels:
              service: staging-test-test-80_kubernetes
        target:
          type: AverageValue
          averageValue: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-deployment
```

```
Custom Metrics Server
=====================

  Data sources
  ------------
  URL: https://api.datadoghq.com

  
  ConfigMap name: system/datadog-custom-metrics
  External Metrics
  ----------------
    Total: 1
    Valid: 0
    
  * horizontal pod autoscaler: staging-test/test
    Metric name: traefik.service.request.duration.max
    Labels:
    - service: staging-test-test-80_kubernetes
    Value: 0
    Timestamp: 2023-03-21 11:30:58 UTC (1679398258000)
    Valid: false
```

**Additional environment details (Operating System, Cloud provider, etc):**

t4g.large 
arm64 node and AWS
