### ISSUE TITLE
[BUG]  AKS Unable to get disk metrics: [Errno 40] Too many levels of symbolic links

### ISSUE THREAD

**Issue by cam3ron2** [DataDog/datadog-agent#16433]
**Agent Environment**

Agent: 7.43.1

**Describe what happened:**

At some point in time in the last month we began to see interrmittent issues with metric collection from agents running in AKS.

Upon inspection of agent logs on impacted nodes, the following error was observed:

```shell
datadog-2jj7c agent 2023-04-04 19:12:03 UTC | CORE | WARN | (pkg/collector/python/datadog_agent.go:132 in LogMessage) | disk:67cc0574430a16ba | (disk.py:135) | Unable to get disk metrics for /host/var/run/containerd/io.containerd.runtime.v2.task/k8s.io/e2b2ac5ef9f685fc65ebf8f0292779e864f049f72e3f2d571095d430ecfe6243/rootfs/host/proc/sys/fs/binfmt_misc: [Errno 40] Too many levels of symbolic links: '/host/var/run/containerd/io.containerd.runtime.v2.task/k8s.io/e2b2ac5ef9f685fc65ebf8f0292779e864f049f72e3f2d571095d430ecfe6243/rootfs/host/proc/sys/fs/binfmt_misc'. You can exclude this mountpoint in the settings if it is invalid.
```

Unlike the symptoms described in https://github.com/DataDog/datadog-agent/issues/3329 `systemd-binfmt` is NOT in an inactive/dead state.

Additionally, because the mount point at issue is hashed, we can not reliably blacklist it via modifying the agent config without blacklisting the entirety of `/host/var/run/containerd/io.containerd.runtime.v2.task/k8s.io/`.  

**Describe what you expected:**

I expected the agent to collect metrics. Ideally if it can't collect metrics for one mount point I would also expect all other metrics to continue to flow to DataDog -- instead it appears that all metric collection comes to a halt. 

**Steps to reproduce the issue:**

Install the agent in AKS > 1.25.5

**Additional environment details (Operating System, Cloud provider, etc):**

Chart: 3.25.1
Provider: AKS
K8s Version: 1.25.5

**Comment by sakavato** [comment]
I got a same issue. why it closed? Did you solve this issue?

**Comment by vyrwu** [comment]
See: https://github.com/DataDog/datadog-agent/issues/1961#issuecomment-446918067

**Comment by wilkejo** [comment]
@cam3ron2 I have the same question and issue as sakavato. How did you solve this?

**Comment by Kenneth-Abrams** [comment]
We are seeing the same issue and we're thinking it's causing our node disk space to fill up. Anyone else experience issues with disk space while seeing these errors flood in?

**Comment by pkoraca** [comment]
Same here. 

Kubernetes version: 1.24
Kubernetes platform: AWS EKS
Chart: 3.10.5
Datadog agent version: 7.42.0

Log:

```
UTC | CORE | WARN | (pkg/collector/python/datadog_agent.go:125 in LogMessage) | disk:67cc0574430a16ba | ([disk.py:135](http://disk.py:135/)) | Unable to get disk metrics for /host/var/run/containerd/io.containerd.runtime.v2.task/[k8s.io/11933a7003721c8c5371b5c6b267a3f7752cda19152cb84ce91523b22d6d8e98/rootfs/host/proc/sys/fs/binfmt_misc](http://k8s.io/11933a7003721c8c5371b5c6b267a3f7752cda19152cb84ce91523b22d6d8e98/rootfs/host/proc/sys/fs/binfmt_misc): [Errno 40] Too many levels of symbolic links: '/host/var/run/containerd/io.containerd.runtime.v2.task/[k8s.io/11933a7003721c8c5371b5c6b267a3f7752cda19152cb84ce91523b22d6d8e98/rootfs/host/proc/sys/fs/binfmt_misc](http://k8s.io/11933a7003721c8c5371b5c6b267a3f7752cda19152cb84ce91523b22d6d8e98/rootfs/host/proc/sys/fs/binfmt_misc)'. You can exclude this mountpoint in the settings if it is invalid.
```

**Comment by theres-jon** [comment]
We see this as well - 

Kubernetes version: 1.24
AWS EKS

Chart: 3.25.5
Agent version: 7.43.1

**Comment by theres-jon** [comment]
@cam3ron2 Can you reopen this issue, please? Unless there's a resolution we're not aware of.

**Comment by jiahao19971** [comment]
I created a `disk.d/conf.yaml` inside [Agent configuration directory](https://docs.datadoghq.com/agent/guide/agent-configuration-files/?tab=agentv6v7#agent-configuration-directory) for the datadog agent via configmaps volume mount

Can refer here for the full default [conf.yaml](https://github.com/DataDog/integrations-core/blob/master/disk/datadog_checks/disk/data/conf.yaml.default)

```
init_config:
    mount_point_global_exclude:
      - (/host)?/proc/sys/fs/binfmt_misc$
instances:
  - use_mount: false
    mount_point_exclude:
      - /proc/sys/fs/binfmt_misc
      - .*/host/proc/sys/fs/binfmt_misc
```

Hope this help anyone

**Comment by rabidscorpio** [comment]
Why was this closed with no explanation? I'm getting the same issue on EKS 1.27 with datadog agent helm chart version 1.4.8.

**Comment by peter-edb** [comment]
For those doing this in helm it can be added like so:

``` yaml
...
  # datadog.confd -- Provide additional check configurations (static and Autodiscovery)

  ## Each key becomes a file in /conf.d
  ## ref: https://github.com/DataDog/datadog-agent/tree/main/Dockerfiles/agent#optional-volumes
  ## ref: https://docs.datadoghq.com/agent/autodiscovery/
  confd:
    # Workaround to solve https://github.com/DataDog/datadog-agent/issues/16433
    disk.yaml: |-
      init_config:

      instances:
             ## Instruct the check to collect using mount points instead of volumes.
          - use_mount: true
          
             ## Collect data from root mountpoint (regex)
             mount_point_include:
                  - ^/$
 ...
```

Apologies if the spacing is off

**Comment by terusaku** [comment]
I will add this information for someone reference.


I got same warning in EKS 1.24, but resolved the issue to add `criSocketPath` explicitly.

Below, helm chart config quotation.
```yml
criSocketPath: /var/run/containerd/containerd.sock
```

**Comment by nadiia-caspar** [comment]
@terusaku thank you, it worked for me 🙏

**Comment by coro101** [comment]
For those using the Datadog Operator, here is [reference link](https://github.com/DataDog/datadog-operator/blob/main/docs/configuration.v2alpha1.md) and snippet

```yaml
spec:
  global:
    criSocketPath: /var/run/containerd/containerd.sock
```
