### ISSUE TITLE
[BUG] Agent admission controller does not lookup pod auto-discovery annotation for unified service tags

### ISSUE THREAD

**Issue by naikn** [DataDog/datadog-agent#16556]
**Agent Environment**
Agent version: 7.43.0-jmx
Deployed into k8s

**Describe what happened:**
Documentation reference: https://docs.datadoghq.com/containers/kubernetes/tag/?tab=containerizedagent#tag-autodiscovery 

Admission controller enabled mutation of the tags set using pod annotations does not create container environment variables DD_ENV, DD_SERVICE and DD_VERSION

For setting the unified service tags, we can use only labels like `tags.datadoghq.com/version`. Kube labels have a character limit of 63 characters and causes deployment failure if its exceeded. Using annotation solves this problem. We can add tags using annotation using `ad.datadoghq.com/tags`. But setting version, service and env under the annotation do not get picked by the admission controller.

**Describe what you expected:**
If unified service tags are set using annoations, then it should be picked by admission controller and injected as env vars on the containers.

https://github.com/DataDog/datadog-agent/blob/main/pkg/clusteragent/admission/mutate/tags.go#L60 looks at pod level labels first and if not found looks at owner labels. The mutate function should also look at pod annotations after that. 

**Steps to reproduce the issue:**

Set pod labels:
```
  labels:
    admission.datadoghq.com/enabled: "true"
    tags.datadoghq.com/service: "i-will-bet-this-service-will-exceed-63-character-limits-for-sure"
    tags.datadoghq.com/version: "branch-master-git-hash-6bf8078e16086942ba74c3573efce86df26505a5"
```
This  results in failure of deployment.

Set pod annotation:
```
annotations:
   ad.datadoghq.com/tags: '{"service" : "i-will-bet-this-service-will-exceed-63-character-limits-for-sure", "version":"branch-master-git-hash-6bf8078e16086942ba74c3573efce86df26505a5"}'
```
This does not create the env vars DD_SERVICE and DD_VERSION on the containers

**Additional environment details (Operating System, Cloud provider, etc):**
