### ISSUE TITLE
[BUG] APM admissionController mutation doesn't work

### ISSUE THREAD

**Issue by volkotyk** [DataDog/datadog-agent#16710]
**Agent Environment**
Datadog agent
```
Controlled By:  DaemonSet/datadog
    Image:         gcr.io/datadoghq/agent:7.43.1
    Environment:
      DD_API_KEY:                                <set to the key 'api-key' in secret 'datadog'>  Optional: false
      KUBERNETES:                                yes
      DD_SITE:                                   us3.datadoghq.com
      DD_DOGSTATSD_PORT:                         8125
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC:            true
      DD_CLUSTER_AGENT_ENABLED:                  true
      DD_CLUSTER_AGENT_KUBERNETES_SERVICE_NAME:  datadog-cluster-agent
      DD_CLUSTER_AGENT_AUTH_TOKEN:               <set to the key 'token' in secret 'datadog-cluster-agent'>  Optional: false
      DD_APM_ENABLED:                            true
      DD_LOGS_ENABLED:                           true
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL:      true
      DD_LOGS_CONFIG_K8S_CONTAINER_USE_FILE:     true
```

APM Agent config:
```
  apm:
    socketEnabled: true
    portEnabled: true
    enabled: false
    port: 8126
    useSocketVolume: false
    socketPath: /var/run/datadog/apm.socket

  admissionController:
    enabled: true
    mutateUnlabelled: true
```

**Describe what happened:**
Admission Controller can't inject the Datadog Library 

**Describe what you expected:**
```
Tried to use metadata:
metadata:
  labels:
    tags.datadoghq.com/env: <env>
    tags.datadoghq.com/service: <service>
    tags.datadoghq.com/version: <version>
spec:
  template:
    metadata:
      labels:
        tags.datadoghq.com/env: <env>
        tags.datadoghq.com/service: <service>
        tags.datadoghq.com/version: <version>
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/java-lib.version: v1.12.1
```
 Tried to use agent settings:
    ` mutateUnlabelled: true`

AWS integration configured and works correct
```
**Steps to reproduce the issue:**
For test use small demo app. Admission Controller does not integrate Datadog Library  with next config:
apiVersion: v1
kind: Pod
metadata:
  name: datadog-java-apm-demo
  annotations:
    admission.datadoghq.com/java-lib.version: "latest"
  labels:
    admission.datadoghq.com/enabled: "true"
spec:
  containers:
  - name: java-service
    image: nilushancosta/datadog-java-apm-demo
    ports:
    - containerPort: 8080
```
  One more doesn't work:
```
  apiVersion: v1
kind: Pod
metadata:
  name: datadog-java-apm-demo
  namespace: datadog
  labels:
    admission.datadoghq.com/enabled: "true"
    admission.datadoghq.com/config.mode: "socket"
    tags.datadoghq.com/env: stg
    tags.datadoghq.com/service: test-java
    tags.datadoghq.com/version: 0.0.1
  annotations:
    admission.datadoghq.com/java-lib.version: v1.12.1
spec:
  containers:
  - name: java-service
    image: nilushancosta/datadog-java-apm-demo
    ports:
    - containerPort: 8080
```
 
  Manual connection work fine and APM shows info:
  
```
  apiVersion: v1
kind: Pod
metadata:
  name: datadog-java-apm-demo
spec:
  volumes:
  - hostPath:
      path: /var/run/datadog
      type: DirectoryOrCreate
    name: datadog
  - emptyDir: {}
    name: datadog-auto-instrumentation      

  initContainers:
  - command:
    - sh
    - copy-lib.sh
    - /datadog-lib
    env:
    - name: DD_ENTITY_ID
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.uid
    - name: DD_TRACE_AGENT_URL
      value: unix:///var/run/datadog/apm.socket
    image: gcr.io/datadoghq/dd-lib-java-init:latest
    imagePullPolicy: Always
    name: datadog-lib-java-init
    volumeMounts:
    - mountPath: /datadog-lib
      name: datadog-auto-instrumentation

  containers:
  - name: java-service
    image: nilushancosta/datadog-java-apm-demo
    ports:
    - containerPort: 8080

    env:
    - name: DD_ENTITY_ID
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.uid
    - name: DD_TRACE_AGENT_URL
      value: unix:///var/run/datadog/apm.socket
    - name: JAVA_TOOL_OPTIONS
      value: ' -javaagent:/datadog-lib/dd-java-agent.jar'
    volumeMounts:
    - mountPath: /var/run/datadog
      name: datadog
    - mountPath: /datadog-lib
      name: datadog-auto-instrumentation    
```
  

**Additional environment details (Operating System, Cloud provider, etc):**
```
AWS EKS
Server Version: v1.24.12-eks-ec5523e
agent:7.43.1
Deployed with Helm chart 
  name       = "datadog"
  repository = "https://helm.datadoghq.com"
  chart      = "datadog"
  version    = "3.25.3"
```

**Comment by igdianov** [comment]
I got the same problem with Datadog admission controller web hook not mutating pods with `admission.datadoghq.com/enabled: "true"` label. 

Tried and tested with k8s versions 1.22,1.23,1.24,1.25 in AWS EKS. It worked only with k8s 1.21.

**Comment by saitama-dh** [comment]
same problem here using chart version 3.28.1 had to rollback to 3.3.3

**Comment by mindovermiles262** [comment]
Seeing the same thing here. K8s version 1.24, DD helm chart 3.10.  As an alternative you should be able to mount the datadog socket as a volume [Docs](https://app.datadoghq.com/apm/service-setup?architecture=container-based&collection=Helm%20Chart%20%28Recommended%29&environment=kubernetes&language=net&traceOnboardingDisableLibInjection=true) (uncheck "Inject the Datadog Library via the Datadog Admission Controller")
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tags.datadoghq.com/env: <env>
    [ ... ]
spec:
  template:
    metadata:
      labels:
        tags.datadoghq.com/env: <env>
        [ ... ]
    spec:
      volumes:
        - hostPath:
            path: /var/run/datadog/
          name: apmsocketpath
      containers:
        - name: <CONTAINER_NAME>
          image: <CONTAINER_IMAGE>/<TAG>
          volumeMounts:
            - name: apmsocketpath
              mountPath: /var/run/datadog
```
