### ISSUE TITLE
[BUG] Prometheus Histogram handling seems to be broke

### ISSUE THREAD

**Issue by datsabk** [DataDog/datadog-agent#17001]
**Agent Environment**
v7.39.2-jmx

**Describe what happened:**
I am generating sample prometheus metrics for my app as shown below: 
```
# TYPE promtest_metric_ops_total counter
promtest_metric_ops_total 334
# HELP promtest_metric_request_duration_seconds Duration of the request.
# TYPE promtest_metric_request_duration_seconds histogram
promtest_metric_request_duration_seconds_bucket{le="0.1"} 56
promtest_metric_request_duration_seconds_bucket{le="5"} 140
promtest_metric_request_duration_seconds_bucket{le="10"} 252
promtest_metric_request_duration_seconds_bucket{le="+Inf"} 334
promtest_metric_request_duration_seconds_sum 1852.8399999999992
promtest_metric_request_duration_seconds_count 334
```
However, Datadog agent doesn't seem to be generating the expected percentiles/aggregates/distribution metrics. 

**Describe what you expected:**
Generates aggregations and percentile metrics

**Steps to reproduce the issue:**
- Create a sample application to generate prometheus metrics. 
- Annotate with ad.datadoghq.com annotations 
- Check metrics in the Datadog Metrics explorer

**Additional environment details (Operating System, Cloud provider, etc):**

Datadog YAML:

```
    dogstatsd_buffer_size: 65535
    dogstatsd_so_rcvbuf: 16777216
    histogram_aggregates:
    - max
    - median
    - avg
    - count
    - sum
    histogram_copy_to_distribution: true
    histogram_percentiles:
    - "0.95"
    - "0.90"
    - "0.50"
    jmx_use_container_support: true
    tags:
    - environment:stage
    - env:stage
    - region:us-west-2
   
```

**Comment by goodspark** [comment]
I'm seeing this too.

DD agent: v7.39.2
Agent is running as a DaemonSet on a k8s cluster w the v3.1.3 DD Helm chart.

Relevant Helm chart values:
```yml
datadog:
  prometheusScrape:
    enabled: true
    additionalConfigs:
      - configurations:
        - send_distribution_buckets: true
```

k8s deployment with autodiscovery annotations:
```yml
    metadata:
      annotations:
        ad.datadoghq.com/myapp.check_names: '["openmetrics"]'
        ad.datadoghq.com/myapp.init_configs: '[{}]'
        ad.datadoghq.com/myapp.instances: |
          [
            {
              "openmetrics_endpoint": "http://%%host%%:2112/",
              "namespace": "myapp",
              "metrics": [
                "myapp*"
              ]
            }
          ]
```

FWIW, I am seeing Prometheus metrics go through. It's just that histograms aren't being converted into distributions, like datsabk said.

I followed this guide: https://docs.datadoghq.com/agent/kubernetes/prometheus/
