### ISSUE TITLE
agent respond 404 page not found from 8126 port on EKS Fargate

### ISSUE THREAD

**Issue by naruse666** [DataDog/datadog-agent#17524]
I'm running datadog-agent as a sidecar.
And set this up as reference [Amazon EKS on AWS Fargate](https://docs.datadoghq.com/integrations/eks_fargate/).

When I run `curl localhost:8126` from my application to the datadog-agent container, it returns a `404 page not found.`

When `curl localhost:8126/info` was executed, a correct response was returned.

This PR discusses ECS Fargaate, but a 404 is responded to as well.
I'm aware that kubernetes can connect as localhost to the sidecar.
https://github.com/DataDog/dd-trace-rb/issues/1446

I'm hoping to learn something from the answers, as no one else seems to have faced this problem.

**result of `agent status`command**
```
===============
Agent (v7.45.0)
===============
=========
APM Agent
=========
  Status: Running
  Pid: 401
  Uptime: 76144 seconds
  Mem alloc: 10,213,336 bytes
  Hostname:
  Receiver: 0.0.0.0:8126
  Endpoints:
    https://trace.agent.datadoghq.com

  Receiver (previous minute)
  ==========================
    No traces received in the previous minute.
```

**Agent Environment**
`v7.45.0`

**Describe what happened:**
agent had response `404 page not found`.

**Describe what you expected:**
correct response from port 8126.

**Steps to reproduce the issue:**
run with 
- AWS EKS on Fargate v3.2.0
- kubernetes version: 1.25.0

**Additional environment details (Operating System, Cloud provider, etc):**
kubernetes manifest I'm using. (ClusterRole is bound as document [AWS EKS Fargate RBAC](https://docs.datadoghq.com/integrations/eks_fargate/#aws-eks-fargate-rbac) )
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      serviceAccountName: my-app
      containers:
        - name: my-app
          image: <MY_APP_IMAGE>
        - name: datadog-agent
          image: public.ecr.aws/datadog/agent:latest
          ports:
          - containerPort: 8126
          env:
          - name: DD_API_KEY
             value: <MY_API_KEY>
          - name: DD_APP_KEY
             value: <MY_APP_KEY>
          - name: DD_EKS_FARGATE
             value: "true"
          - name: DD_KUBERNETES_KUBELET_NODENAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: DD_SITE
             value: "datadoghq.com"
          - name: DD_CLUSTER_NAME
             value: "my-cluster"
```
