### ISSUE TITLE
[BUG] Datadog agent does not take DD_CONTAINER_EXCLUDE into consideration when used on its own image

### ISSUE THREAD

**Issue by mistrate** [DataDog/datadog-agent#17804]
**Agent Environment**
Agent 7.45.0 - Commit: 964e770 - Serialization version: v5.0.81 - Go version: go1.19.9

**Describe what happened:**
We have the following service in our docker compose file
```yaml
datadog:
    image: datadog/agent:latest
    restart: unless-stopped
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_CONTAINER_EXCLUDE="image:datadog/agent"
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_HOSTNAME=${EXTERNAL_HOSTNAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
```
But we still get logs inside datadog, for example:
```
memcache.avg_item_size cannot be collected because `bytes` or `curr_items` are missing, or `curr_items` is 0
```
This is, of course, because we are using memcached as part of the docker-compose stack
```
agent | CORE
filename | pkg/collector/python/datadog_agent.go
level | WARN
lineno | 132
mcache | ccd387f670fae65
process | LogMessage
pyFilename | mcache.py
pyLineno | 166
service | datadog-agent
timestamp | 1687526615000

```

```
container_id:897d55ccce0819b151446d0f425d5e468e8f1661fe5bc03319e6de1f1e347b18,
container_name:project_datadog_1,
datadog.index:someindex,
datadog.submission_auth:private_api_key,
docker_image:datadog/agent:latest,
git.repository_url:https://github.com/datadog/datadog-agent,
image_name:datadog/agent,
image_tag:latest,
service:agent,
short_image:agent,
source:agent,team:someteam
```
**Describe what you expected:**
I would expect for datadog-agent logs to not be sent to datadog if the image is excluded

**Steps to reproduce the issue:**
* Create a docker compose file with multiple services, one of which is for datadog like the YAML snippet above.
* Start the docker setup with a valid API key
* Notice that datadog agent is still sending logs to datadog

**Additional environment details (Operating System, Cloud provider, etc):**
The machine running docker is using Debian, Docker version 20.10.5+dfsg1, build 55c4c88
