### ISSUE TITLE
[BUG] Agent metric name validation is inconsistent with documentation

### ISSUE THREAD

**Issue by campbel** [DataDog/datadog-agent#17867]
**Agent Environment**

Cluster Agent version `7.42.0`

**Describe what happened:**

I'm setting up an HPA using an external Datadog Metric and seeing errors in the cluster agent.

**HPA Config**

```yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dx-test-deployment
  namespace: dev-dx-test-deployment
spec:
  maxReplicas: 10
  metrics:
  - external:
      metric:
        name: datadogmetric@dev-dx-test-deployment:cpu
      target:
        type: Value
        value: "50"
    type: External
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dx-test-deployment
```

**Datadog Metric Config**

```yaml
---
apiVersion: datadoghq.com/v1alpha1
kind: DatadogMetric
metadata:
  name: cpu
spec:
  query: avg:kubernetes.cpu.usage.total{kube_app_name:dx-test-deployment}.rollup(30)

```

Resulting error

```plaintext
2023-06-28 02:51:31 UTC | CLUSTER | ERROR | (pkg/util/kubernetes/autoscalers/autoscalers.go:108 in inspectHPAv2) | cannot build external metric value for HPA dev-dx-test-deployment/dx-test-deployment, skipping: metric name "datadogmetric@dev-dx-test-deployment:cpu" is invalid
```

Checking the source [here](https://github.com/DataDog/datadog-agent/blob/1b72bcf2e698e12da88e4e09ca191ebd4b406164/pkg/util/kubernetes/autoscalers/autoscalers.go#L223), it does seem that the name violates the regexp. But, this is unexpected as its in contradiction with the [documentation](https://docs.datadoghq.com/containers/guide/cluster_agent_autoscaling_metrics/?tab=helm#example-hpas-with-datadogmetric) which uses `@`, `:` and `-`. 

**Describe what you expected:**

I expected the metric to be properly queried and calculated for the HPA to utilize.

**Steps to reproduce the issue:**

1. Spin up a fresh cluster (I used EKS)
2. Setup datadog agent with cluster agent and metrics enabled per the documentation [here](https://docs.datadoghq.com/containers/guide/cluster_agent_autoscaling_metrics/?tab=helm)
3. Create a datadogmetric in a namespace with a `-` or that uses a name with a `-`.
4. Create a deployment / HPA that utilizes the metric.
5. Observe the datadog-cluster-agent for errors.

**Additional environment details (Operating System, Cloud provider, etc):**

Kubernetes 1.24 / EKS

**Comment by campbel** [comment]
I'll add that utilizing an inlined metric like

```yaml
  - external:
      metric:
        name: kubernetes.cpu.usage.total
        selector:
          matchLabels:
            kube_app_name: dx-test-deployment
      target:
        type: Value
        value: "50"
    type: External
```

Works as expected. Presumably because its able to get past the validation.
