### ISSUE TITLE
Unified python version of GitHubActions.

### ISSUE THREAD

**Issue by taku333** [DataDog/datadog-agent#18319]
The python version of GitHubActions can be unified from the following settings.
The go version is unified.

```
steps:
- uses: actions/checkout@v3
- uses: actions/setup-python@v4
  with:
    python-version-file: '.python-version' # Read python version from a file .python-version
- run: python my_script.py
```
https://github.com/actions/setup-python/blob/61a6322f88396a6271a6ee3565807d608ecaddd1/docs/advanced-usage.md#using-the-python-version-file-input

However, due to two issues, it was issued as an ISSUE instead of a pull request.

1. 3.8.10,3.8.14,3.9.16　and versions are not unified.
https://github.com/DataDog/datadog-agent/blob/13b09e8cbf074ae437503e3564794840822badb8/.github/workflows/windows-unittests.yml#L26C28-L26C34

A and various python versions exist.
Versions vary depending on the workflow of the actions.
I was wondering if there is some reason or other why the python version cannot be changed due to OS or feature dependencies.
We also thought that the change was not made to take into account the impact of unifying the versions on the overall action.

2. It is set in .gitignore.

https://github.com/DataDog/datadog-agent/blob/13b09e8cbf074ae437503e3564794840822badb8/.gitignore#L32

If it seems unnecessary to change, please Close.
