### ISSUE TITLE
[BUG] Dual shipping doesn't ship the matrix of "kubernetes state matrix core" integration.  

### ISSUE THREAD

**Issue by Derek-Xiang** [DataDog/datadog-agent#18325]
Dual shipping doesn't ship the matrix of "kubernetes state matrix core" integration, but it can be seen from the source datadog instance as it is enabled by :

```yaml
kubeStateMetricsEnabled: false
  kubeStateMetricsCore:
    enabled: true
```

**Agent Environment**
Agent 7.45.0

Installed with datadog helm with chart version: datadog-3.32.4

**Describe what happened:**
Dual shipping has been set as: 
```yaml
# Dual shipping
agents:
  enabled: true
  useConfigMap: true
  customAgentConfig:
    additional_endpoints:
      "https://us5.datadoghq.com":
      - *****************************
```

But the matrix "kubernetes_state" is not shipped to the target datadog instance

**Describe what you expected:**
The same matix and data should be shipped to destination datadog instance like the source datadog instance

**Steps to reproduce the issue:**
- You need to use datadog monitor a kubernetes cluster
- add the dual shipping code snippets to datadog.yaml or value.yaml of helm
```yaml
datadog:
  ...
  kubeStateMetricsEnabled: false
  kubeStateMetricsCore:
    enabled: true
  ...

agents:
  enabled: true
  useConfigMap: true
  customAgentConfig:
    additional_endpoints:
      "https://us5.datadoghq.com":
      - *****************************
```
- Check the dashboard of both on "Kubernetes Overview" to see if there is data for charts like "Node", "Deployment" etc.
- Check if you can see the matrix named "kubernetes_state" in destination datadog "matrix summary"

**Additional environment details (Operating System, Cloud provider, etc):**
