### ISSUE TITLE
How/where can we find hidden APM paramaters for APM POC setup?

### ISSUE THREAD

**Issue by tirelibirefe** [DataDog/datadog-agent#18886]
Hello,
We would like to do Datadog APM POC setup but we are not be able to find some hidden APM parameters anywhere for 2 days.

Regarding to the documentation [here](https://app.datadoghq.eu/apm/service-setup?appsec=false&architecture=container-based&collection=Helm%20Chart%20%28Recommended%29&environment=kubernetes&language=net), at Step #3, we need to fill some blanks.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    tags.datadoghq.com/env: <env>
    tags.datadoghq.com/service: <service>
    tags.datadoghq.com/version: <version>
spec:
  template:
    metadata:
      labels:
        tags.datadoghq.com/env: <env>
        tags.datadoghq.com/service: <service>
        tags.datadoghq.com/version: <version>
```
Where and how to get these information? Could you please advise?

Thanks & Regards
