### ISSUE TITLE
Error running check disk: [{"message": "[Errno 2] No such file or directory: '/host/proc/filesystems'"

### ISSUE THREAD

**Issue by amlwwalker** [DataDog/datadog-agent#2001]
**Describe what happened:**

I am using the agent inside docker, and specifically using convox to deploy my infrastructure. convox.yml is very close to a docker-compose.yml. I have datadog agent running inside the compose file as such

```
    datadog:
      agent: true
      privileged: true
      environment:
        - DD_API_KEY=${DATADOG_API_KEY}
        - DD_APM_ENABLED=true
        - DD_LOGS_ENABLED=true
        - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      image: datadog/agent:latest
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /proc/:/host/proc/:ro
        - /cgroup/:/host/sys/fs/cgroup:ro
```

and I have the following errors in my logs. 

```
2018-07-14 16:10:04 UTC | ERROR | (runner.go:277 in work) | Error running check disk: [{"message": "[Errno 2] No such file or directory: '/host/proc/filesystems'", "traceback": "Traceback (most recent call last):\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/checks/base.py\", line 294, in run\n    self.check(copy.deepcopy(self.instances[0]))\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/disk/disk.py\", line 43, in check\n    self.collect_metrics_psutil()\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/disk/disk.py\", line 90, in collect_metrics_psutil\n    for part in psutil.disk_partitions(all=True):\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/psutil/__init__.py\", line 1839, in disk_partitions\n    return _psplatform.disk_partitions(all)\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/psutil/_pslinux.py\", line 1000, in disk_partitions\n    with open_text(\"%s/filesystems\" % get_procfs_path()) as f:\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/psutil/_pslinux.py\", line 194, in open_text\n    return open(fname, \"rt\", **kwargs)\nIOError: [Errno 2] No such file or directory: '/host/proc/filesystems'\n"}]
2018-07-14 16:10:04 UTC | WARN | (cgroup.go:510 in parseCgroupMountPoints) | No mountPoints were detected, current cgroup root is: /host/sys/fs/cgroup/
```

I am running localy for testing at the moment (OSX with docker). I can see in the logs that datadog agent is successfully detecting the other containers

**Describe what you expected:**

Hopefully to see logs from my other containers in datadog events!

**Steps to reproduce the issue:**

I expect, to create a docker-compose file, stick a container in there (web app for example) and copy the above docker-compose configuration for datadog/agent. Then check the docker logs.

If that doesn't work, it would mean using convox locally and doing the above, however explaining how to use convox is beyong this

**Additional environment details (Operating System, Cloud provider, etc):**
