### ISSUE TITLE
[BUG] http_check http_response_status_code now has to be a string

### ISSUE THREAD

**Issue by flickers** [DataDog/datadog-agent#20093]
**Agent Environment**
Datadog Agent 7.48.0 on kubernetes 1.27 EKS

**Describe what happened:**
http checks no longer work and agent status returns this error
```
    http_check (9.0.1)
    ------------------
      Instance ID: http_check:www.example.com:90af51ac676ab1fe [ERROR]
      Configuration Source: file:/etc/datadog-agent/conf.d/http_check.yaml
      Total Runs: 5,522
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 1ms
      Last Execution Date : 2023-10-12 11:49:42 UTC (1697111382000)
      Last Successful Execution Date : Never
      Error: Detected 1 error while loading configuration model `InstanceConfig`:
http_response_status_code
  Input should be a valid string
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/datadog_checks/base/checks/base.py", line 1210, in run
          initialization()
        File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/datadog_checks/base/checks/base.py", line 517, in load_configuration_models
          instance_model = self.load_configuration_model(package_path, 'InstanceConfig', instance_config, context)
        File "/opt/datadog-agent/embedded/lib/python3.9/site-packages/datadog_checks/base/checks/base.py", line 561, in load_configuration_model
          raise_from(ConfigurationError('\n'.join(message_lines)), None)
        File "<string>", line 3, in raise_from
      datadog_checks.base.errors.ConfigurationError: Detected 1 error while loading configuration model `InstanceConfig`:
      http_response_status_code
        Input should be a valid string
```

**Describe what you expected:**
That I could use integers or string for http_response_status_code in http_checks

**Steps to reproduce the issue:**
This works http_response_status_code value as string
```
  clusterAgent:
    confd:
      http_check.yaml: |-
        cluster_check: true
        init_config:
          timeout: 5

        instances:
          - url: https://www.example.com
            name: www.example.com
            check_certificate_expiration: true
            http_response_status_code : "404"
            disable_ssl_validation: false
            days_warning: 20
            days_critical: 5
            tags:
              - env:stage
```
This doesn't work http_response_status_code value as integer
```
  clusterAgent:
    confd:
      http_check.yaml: |-
        cluster_check: true
        init_config:
          timeout: 5

        instances:
          - url: https://www.example.com
            name: www.example.com
            check_certificate_expiration: true
            http_response_status_code : 404
            disable_ssl_validation: false
            days_warning: 20
            days_critical: 5
            tags:
              - env:stage
```

**Additional environment details (Operating System, Cloud provider, etc):**
Kubernetes EKS v1.27 (AWS)
