### ISSUE TITLE
[BUG] serverless-init affected by CVE-2023-45142

### ISSUE THREAD

**Issue by nilleb** [DataDog/datadog-agent#20185]
trivy detects a vulnerability in serverless-init
```
DEBUG	Detecting library vulnerabilities, type: gobinary, path: app/datadog-init
```

**Agent Environment**

**Describe what happened:**
trivy scan failed because of https://nvd.nist.gov/vuln/detail/CVE-2023-45142

**Describe what you expected:**

**Steps to reproduce the issue:**
Prepare a new dockerfile
```
COPY --from=datadog/serverless-init:1.1.2-rc1 /datadog-init /app/datadog-init
```
then execute a trivy scan against the image
```
    - task: trivy@1
      inputs:
        version: v0.42.1 # 0.45.1 --> https://github.com/aquasecurity/trivy/discussions/5258
        severities: CRITICAL,HIGH
        image: $(DOCKER_TASK_BUILT_IMAGES)
        docker: false
        exitCode: 1
        options: --timeout 30m0s --debug 
```

**Additional environment details (Operating System, Cloud provider, etc):**
Linux (Ubuntu 22)
