### ISSUE TITLE
[Suppoert] Couldn't reconcile Webhook datadog-webhook

### ISSUE THREAD

**Issue by tolerant-hu** [DataDog/datadog-agent#20368]
### kubectl version
Client Version: v1.28.0
Server Version: v1.25.6

### Helm on Azure AKS:
datadog-agent           	default  	deployed	datadog-3.39.3           

### Value.yaml:
```yaml
datadog:
  apiKeyExistingSecret: datadog-secret
  kubelet:
    tlsVerify: false
  secretBackend:
    command: "/readsecret_multiple_providers.sh"

providers:
  aks:
    enabled: true

agents:
  containers:
    agent:
      env:
        - name: DD_CONTAINER_EXCLUDE
          value: "kube_namespace:.*"
        - name: DD_CONTAINER_INCLUDE
          value: "kube_namespace:default"
  image:
    tagSuffix: jmx
```

### Error output:
2023-10-24 08:18:45 UTC | CLUSTER | INFO | (pkg/clusteragent/admission/controllers/webhook/controller_base.go:170 in processNextWorkItem) | Couldn't reconcile Webhook datadog-webhook: Operation cannot be fulfilled on mutatingwebhookconfigurations.admissionregistration.k8s.io "datadog-webhook": the object has been modified; please apply your changes to the latest version and try again
