### ISSUE TITLE
How to use DD_APM_IGNORE_RESOURCES with admission controller?

### ISSUE THREAD

**Issue by sh-ogawa** [DataDog/datadog-agent#20564]
I want to ignore trace for health check.
So I add the following value.

```yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hogehoge
spec:
  replicas: 2
  template:
    metadata:
      annotations:
        # ... 
        admission.datadoghq.com/java-lib.version: v1.22.0
    spec:
      containers:
      - name: hogehoge
        # ... 
        env:
        - name: DD_APM_IGNORE_RESOURCES
          value: GET /health_check
```

But it isn't work correctly, I receive `GET /health_check` into `APM > Traces`.

Please tell me how to use DD_APM_IGNORE_RESOURCES with admission controller.
