### ISSUE TITLE
[BUG] Using Celery Message Priorities With Redis Backend Breaks DatadogMetric Query

### ISSUE THREAD

**Issue by misimpso** [DataDog/datadog-agent#20692]
**Agent Environment**

Agent Version: `7.39.1`
DatadogMetric Resource Version: `datadoghq.com/v1alpha1`
Python Version: `3.8.13`
Redis Version: `6.2.6`
Celery Version: `5.2.7`

**Describe what happened:**
We use celery with a redis broker for our Python task scheduling. To scale our celery infrastructure, we use a `DatadogMetric` resource to power our `HorizontalPodAutoscaler`.

The `DatadogMetric`
```
apiVersion: datadoghq.com/v1alpha1
kind: DatadogMetric
metadata:
  name: my-service-scheduled-queue-size
spec:
  query: "max:redis.key.length{service:my-service AND env:{{ .Values.env }}}.rollup(60)"
```

The `HorizontalPodAutoscaler`
```
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-service-scheduled-worker-hpa
  labels:
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-service-celery-scheduled
  minReplicas: 2
  maxReplicas: 4
  metrics:
   - type: External
      external:
        metric:
          name: datadogmetric@my-namespace:my-service-scheduled-queue-size
        target:
          type: AverageValue
          averageValue: {{ .Values.hpa.celeryScheduled.datadogMetrics.targetAvgValue }}
```

We were tinkering with [celery task prioritization](https://docs.celeryq.dev/en/stable/userguide/routing.html#redis-message-priorities) to try deal with our workload more efficiently. Redis doesn't support message priorities out of the box, so celery takes any named queues and creates more queues for each priority level required. The default separator is `"\x06\x16"`, but we changed it to `":"`. For a named queue, `"jobs"`, and 3 priority levels, will result in 4 queues: (`jobs`, `jobs:0`, `jobs:1`, `jobs:2`).

Our celery infrastructure was able to work with the new priorities, however the HPA stopped working. When we pushed the task prioritization code, we noticed the output of the `redis.key.length` metric went straight to 0.
![image](https://github.com/DataDog/datadog-agent/assets/16249360/bd75d96e-46f5-4e79-9339-0deae4279a25)

The initial deploy with the change worked, but subsequent deploys failed with the following message:
```
2m4s        Warning   FailedGetExternalMetric   horizontalpodautoscaler/my-service-scheduled-worker-hpa   unable to get external metric my-service/datadogmetric@my-namespace:my-service-scheduled-queue-size/nil: unable to fetch metrics from external metrics API: Internal error occurred: DatadogMetric is invalid, err: Outdated result from backend, query: max:redis.key.length{service:my-service AND env:sandbox}.rollup(60)
3m20s       Warning   FailedGetExternalMetric   horizontalpodautoscaler/my-service-worker-hpa             unable to get external metric my-service/datadogmetric@my-namespace:my-service-queue-size/nil: unable to fetch metrics from external metrics API: Internal error occurred: DatadogMetric is invalid, err: Outdated result from backend, query: max:redis.key.length{service:my-service AND env:sandbox}.rollup(60)
```

It looks like the metric wasn't just returning zero, but actively failing to execute.

**Describe what you expected:**
The datadog metric would not be impacted by new celery queues being made.
