### ISSUE TITLE
[BUG]  Log Collection not working when I am using argo rollout

### ISSUE THREAD

**Issue by sourceful-karlson** [DataDog/datadog-agent#21490]
**Agent Environment**

**Describe what happened:**

- Log Collection not working when I am using argo rollout

**Describe what you expected:**

- I expect logs to appears in datadog

**Steps to reproduce the issue:**
- deploy an application using argo rollout
- set collect log as true
- log does not appear
- change log back to deployment
- log appear

**Additional environment details (Operating System, Cloud provider, etc):**
- GKE Autopilot
- datadog helm chart datadog:3.49.7
- argo rollout v1.2.1

**Comment by sourceful-karlson** [comment]
```yaml
> targetSystem: "linux"
clusterAgent:
  # clusterAgent.enabled -- Set this to false to disable Datadog Cluster Agent
  enabled: true
  admissionController:
    enabled: true

    ## @param mutateUnlabelled - boolean - optional
    ## Enable injecting config without having the pod label:
    ## admission.datadoghq.com/enabled="true"
    #
    mutateUnlabelled: false
datadog:
  containerExclude: "kube_namespace:.*"
  containerInclude: "kube_namespace:default"
  ## containerInclude: "kube_namespace:default kube_namespace:argocd kube_namespace:ambassador"
  apm:
    enabled: true
    env: develop
    portEnabled: true
  site: datadoghq.eu
  apiKey: asdfasdfasdf
  appKey: asdfasdfasdfasd
  clusterName: asdfasdfasdf-asdfasdfasdf-1

  # Enable the new `kubernetes_state_core` check.
  kubeStateMetricsCore:
    enabled: true
  # Avoid deploying kube-state-metrics chart.
  # The new `kubernetes_state_core` doesn't require to deploy the kube-state-metrics anymore.
  kubeStateMetricsEnabled: false

  logs:
    ## @param enabled - boolean - optional - default: false
    ## Enables this to activate Datadog Agent log collection.
    #
    enabled: true

    ## @param containerCollectAll - boolean - optional - default: false
    ## Enable this to allow log collection for all containers.
    #
    containerCollectAll: true

agents:
  priorityClassCreate: true
  # priorityClassName: high-priority
  containers:
    agent:
      resources:
        requests:
          cpu: 200m
          memory: 1024Mi


    traceAgent:
      resources:
        requests:
          cpu: 200m
          memory: 1024Mi


    processAgent:
      resources:
        requests:
          cpu: 200m
          memory: 1024Mi



providers:
  gke:
    autopilot: true
```

**Comment by sourceful-karlson** [comment]
```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: quote
spec:
  selector:
    matchLabels:
      app: quote
  replicas: 1
  template:
    metadata:
      annotations: 
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      labels:
        app: quote
    spec:
      containers:
        - name: python
          image: docker.io/datawire/quote:0.5.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1024Mi"
              cpu: "1000m"
          # readinessProbe:
          #   httpGet:
          #     path: /quote/healthcheck/readiness
          #     port: 5000
          #   initialDelaySeconds: 180
          #   periodSeconds: 120
          #   failureThreshold: 3
          # livenessProbe:
          #   httpGet:
          #     path: /quote/healthcheck
          #     port: 5000
          #   initialDelaySeconds: 120
          #   periodSeconds: 60
          #   failureThreshold: 3
          ports:
            - containerPort: 5000
          env:
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_APPSEC_ENABLED
              value: "false"
            - name: ROLLING_RESTART
              value: "0"
            - name: DD_REMOTE_CONFIGURATION_ENABLED
              value: "false"
  strategy:
    blueGreen:
      autoPromotionEnabled: false
      activeService: quote-service
      previewService: quote-service-preview

```
