### ISSUE TITLE
[BUG] cluster checks runner keeps trying to get remote configuration when remote config is disabled

### ISSUE THREAD

**Issue by jcogilvie** [DataDog/datadog-agent#21516]
**Agent Environment**
Deployed via operator v1.1.0

root@datadog-cluster-checks-runner:/# agent version
Agent 7.47.1 - Commit: 24dcc70 - Serialization version: v5.0.90 - Go version: go1.20.6

**Describe what happened:**
Log repeats this every 5 seconds:
```
2023-12-12 19:31:10 UTC | CORE | INFO | (pkg/config/remote/client.go:266 in pollLoop) | retrying the first update of remote-config state (rpc error: code = Unknown desc = remote configuration service not initialized)
```

Looks like whatever condition is being checked in [this loop](https://github.com/DataDog/datadog-agent/blob/fb97121e39607ee7d036d3f403ec2de7eaac3b72/pkg/config/remote/client/client.go#L332) isn't breaking it out at the top like it's supposed to.

**Describe what you expected:**
Cluster checks runner should see that remote config is disabled, and stop trying unless/until the CR is updated to enable it.

**Steps to reproduce the issue:**
Deploy the following CR:

```
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  finalizers:
    - finalizer.agent.datadoghq.com
  name: datadog
  namespace: datadog

spec:
  features:
    admissionController:
      agentCommunicationMode: hostip
      enabled: true
      failurePolicy: Fail
      mutateUnlabelled: true
    apm:
      enabled: true
      hostPortConfig:
        enabled: true
      unixDomainSocketConfig:
        enabled: true
    clusterChecks:
      enabled: true
      useClusterChecksRunners: true
    cspm:
      enabled: false
    dogstatsd:
      hostPortConfig:
        enabled: true
      originDetectionEnabled: true
      unixDomainSocketConfig:
        enabled: true
        path: /var/run/datadog/statsd.sock
    eventCollection:
      collectKubernetesEvents: true
    externalMetricsServer:
      enabled: false
      useDatadogMetrics: false
    kubeStateMetricsCore:
      enabled: true
    liveContainerCollection:
      enabled: true
    liveProcessCollection:
      enabled: true
    logCollection:
      containerCollectAll: true
      containerCollectUsingFiles: true
      enabled: true
      openFilesLimit: 1000
    npm:
      collectDNSStats: true
      enableConntrack: true
      enabled: true
    oomKill:
      enabled: true
    orchestratorExplorer:
      enabled: true
    otlp:
      receiver:
        protocols:
          grpc:
            enabled: true
          http:
            enabled: true
    remoteConfiguration:
      enabled: false
    tcpQueueLength:
      enabled: true
    usm:
      enabled: false
  global:
    clusterName: foo-bar
    credentials:
      apiSecret:
        keyName: api-key
        secretName: datadog-secret
      appSecret:
        keyName: app-key
        secretName: datadog-secret
    registry: public.ecr.aws/datadog
  override:
    clusterAgent:
      env:
        - name: DD_LOG_FORMAT_JSON
          value: 'true'
      extraConfd:
        configMap:
          name: checks-confd
      image:
        tag: 7.47.1
      labels:
        admission.datadoghq.com/enabled: 'false'
      priorityClassName: system-cluster-critical
      replicas: 2
    clusterChecksRunner:
      image:
        tag: 7.47.1
    nodeAgent:
      env:
        - name: DD_LOG_FORMAT_JSON
          value: 'true'
        - name: DD_LOGS_CONFIG_AUTO_MULTI_LINE_DETECTION
          value: 'true'
        - name: DD_HISTOGRAM_PERCENTILES
          value: 0.90 0.95 0.99
        - name: DD_DOGSTATSD_TAG_CARDINALITY
          value: orchestrator
      extraConfd:
        configMap:
          name: checks-confd
      image:
        tag: 7.47.1
      labels:
        admission.datadoghq.com/enabled: 'false'
      priorityClassName: system-node-critical
```

Observe cluster checks runner logs for the indicated behavior.

**Additional environment details (Operating System, Cloud provider, etc):**
AWS EKS 1.27
