### ISSUE TITLE
[BUG] Failures to query pg_stat_statements_info in postgres apm integration with specified dbname

### ISSUE THREAD

**Issue by joesteffee** [DataDog/datadog-agent#21829]
**Agent Environment**
Cluster Agent 7.49.1 - Commit: 1790cab - Serialization version: v5.0.97 - Go version: go1.20.10

**Describe what happened:**
When using this configuration:
```
  - dbm: true
    dbname: <custom DB name>
    collect_activity_metrics: true
    collect_bloat_metrics: true
    collect_schemas:
      enabled: true
    query_samples:
      explain_parameterized_queries: true
    ignore_databases:
      - master
      - rdsadmin
      - postgres
    relations:
      - relation_regex: '.*'
        relkind:
          - r
          - i
          - t
          - s
          - p
    host: <redacted>
```
I receive frequent warnings:
2024-01-02 19:43:04 UTC | CORE | WARN | (pkg/collector/python/datadog_agent.go:131 in LogMessage) | postgres:6640f5283d2dae90 | (statements.py:370) | Failed to query for pg_stat_statements_info: relation "pg_stat_statements_info" does not exist
LINE 1: SELECT dealloc FROM pg_stat_statements_info

The pg_stat_statements_info database only exists inside the 'postgres' database, but we have integrations set up to only query necessary databases. Need to either update the agent to allow specifying DB where this view is or update documentation to add this view to where the agent can pick it up.

**Describe what you expected:**
Ability to set destination database of pg_stat_statements_info relation

**Additional environment details (Operating System, Cloud provider, etc):**
AWS EKS with RDS
