### ISSUE TITLE
[BUG] OTLP receiver fails to start if logs_enabled=false

### ISSUE THREAD

**Issue by timmc-edx** [DataDog/datadog-agent#23017]
**Agent Environment**

```
$ datadog-agent version
Agent 7.51.0 - Commit: 5b3c5cc - Serialization version: v5.0.100 - Go version: go1.21.5
```

This is on an Ubuntu docker container.

**Describe what happened:**
I enabled the agent's OTLP receiver with the following configuration:

```
otlp_config:
  receiver:
    protocols:
        grpc:
          endpoint: "localhost:4317"
        http:
          endpoint: "localhost:4318"
  metrics:
    enabled: true
  traces:
    enabled: true
  logs:
    enabled: true
```

The agent started, but was not listening on ports 4317 and 4318. I eventually found that `datadog-agent status` showed the following:

```
====
OTLP
====

  Status: Enabled
  Collector status: Failed to start
  Error: OTLP logs is enabled but logs agent is not enabled
```
Adding `logs_enabled: true` allowed the collector to start.

**Describe what you expected:**
The agent should either entirely fail to start, or should succeed but log (at WARN level) about mismatched config. Partially working is a confusing state.
