### ISSUE TITLE
Is Datadog Agent meant to run on kind (kubernetes) too?

### ISSUE THREAD

**Issue by sourcopolo** [DataDog/datadog-agent#23052]
I'm trying to run Datadog agent on [kind](https://kind.sigs.k8s.io/) cluster running on my machine. But I've been fighting one issue after another.

My question is simple: Is Datadog Agent meant to run on kind clusters too? For example, datadog agent had trouble detecting the hostname (until I set it manually).

**Comment by carlosroman** [comment]
Yes, the Agent can run on `kind`. We actually use it for some our end to end tests ([kine test](https://github.com/DataDog/datadog-agent/blob/main/test/new-e2e/examples/kind_test.go)). How are you deploying the Agent ([Helm](https://docs.datadoghq.com/containers/kubernetes/installation/?tab=helm), [Datadog Operator](https://docs.datadoghq.com/containers/kubernetes/installation/?tab=datadogoperator) or [daemonset]()https://docs.datadoghq.com/containers/guide/kubernetes_daemonset)?

**Comment by network-charles** [comment]
It would help if you mounted the docker socket volume on your nodes as described [here](https://docs.datadoghq.com/agent/troubleshooting/hostname_containers/?tab=dockeronvm#accessing-the-container-runtime-api-1).

Specify it in your kind manifest.
**cluster.yaml**
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30909 # The k8s service node port
    hostPort: 9090 # The host port you want to expose the k8s service
    protocol: TCP
  extraMounts:
    - hostPath: /var/run/docker.sock
      containerPath: /var/run/docker.sock
      readOnly: true
- role: worker
  extraMounts:
    - hostPath: /var/run/docker.sock
      containerPath: /var/run/docker.sock
      readOnly: true
```

Then create the cluster.
```bash
kind create cluster --config cluster.yaml
```

**Comment by network-charles** [comment]
@carlosroman, my issue is that the datadog agent isn't sending orchestrator data. I installed the agent using the datadog operator. I also have the below defined in my manifest.
```yaml
orchestratorExplorer:
    enabled: true
liveContainerCollection:
    enabled: true
```
