### ISSUE TITLE
Can't use K8s secret in auth header

### ISSUE THREAD

**Issue by frazergibsongohenry** [DataDog/datadog-agent#23326]
**Agent Environment**
Datadog Helm chart 3.57.3
(

**Describe what happened:**
Added an Open Metric check for Scalr following [these](https://docs.scalr.io/docs/openmetrics) docs:
```
    openmetrics.yaml: |-
      cluster_check: true
      init_config:
      instances:
        - openmetrics_endpoint: https://<account>.scalr.io:443/api/iacp/v3/metrics
          metrics:  
            - .*  
          headers:  
            Authorization: ENC[k8s_secret@datadog/scalr/token]
            Prefer: profile=preview
```

I'm including the "Bearer" string as part of the token as per the secrets docs [here](https://docs.datadoghq.com/agent/configuration/secrets-management/?tab=linux#defining-secrets-in-configurations).

However, the Authorization value is moved to another line and I believe this is stopping it from working as when the token is in plain text and on one line it works
```
=== openmetrics check ===
Configuration provider: file
Configuration source: file:/etc/datadog-agent/conf.d/openmetrics.yaml
Config for instance ID: openmetrics:86185c9b1a9d5933
empty_default_hostname: true
headers:
  Authorization: |
    Bearer <token>
  Prefer: profile=preview
metrics:
- .*
openmetrics_endpoint: https://<account>.scalr.io:443/api/iacp/v3/metrics
tags:
- cluster_name:minikube
- kube_cluster_name:minikube
~
===
```

**Describe what you expected:**

Push Scalr metrics to Datadog

**Steps to reproduce the issue:**

Deploy the Datadog helm chart with this cluster check

**Additional environment details (Operating System, Cloud provider, etc):**
