### ISSUE TITLE
Datadog-agent does not forward metrics to own statsd server

### ISSUE THREAD

**Issue by hrishiic** [DataDog/datadog-agent#2358]
**Output of the info page (if this is a bug)**
```
Getting the status from the agent.

==============
Agent (v6.4.2)
==============

  Status date: 2018-09-24 11:59:30.052389 UTC
  Pid: 337
  Python Version: 2.7.15
  Logs: 
  Check Runners: 2
  Log Level: DEBUG

  Paths
  =====
    Config File: /etc/datadog-agent/datadog.yaml
    conf.d: /etc/datadog-agent/conf.d
    checks.d: /etc/datadog-agent/checks.d

  Clocks
  ======
    NTP offset: -0.002020282 s
    System UTC time: 2018-09-24 11:59:30.052389 UTC

  Host Info
  =========
    bootTime: 2018-09-21 20:00:34.000000 UTC
    kernelVersion: 4.14.62-70.117.amzn2.x86_64
    os: linux
    platform: debian
    platformFamily: debian
    platformVersion: buster/sid
    procs: 71
    uptime: 227959
    virtualizationRole: guest
    virtualizationSystem: xen

  Hostnames
  =========
    ec2-hostname: REDACTED.us-west-2.compute.internal
    host_aliases: [REDACTED.us-west-2.compute.internal]
    hostname: i-0c622fc943984bc6e
    instance-id: i-0c622fc943984bc6e
    socket-fqdn: REDACTED.us-west-2.compute.internal.
    socket-hostname: REDACTED.us-west-2.compute.internal

=========
Collector
=========

  Running Checks
  ==============
    cpu
    ---
      Total Runs: 158
      Metric Samples: 6, Total: 942
      Events: 0, Total: 0
      Service Checks: 0, Total: 0
      Average Execution Time : 0ms
      
  
    disk (1.2.0)
    ------------
      Total Runs: 158
      Metric Samples: 130, Total: 20540
      Events: 0, Total: 0
      Service Checks: 0, Total: 0
      Average Execution Time : 1180ms
      
  
    docker
    ------
      Total Runs: 158
      Metric Samples: 228, Total: 36024
      Events: 0, Total: 3
      Service Checks: 1, Total: 158
      Average Execution Time : 141ms
      
  
    file_handle
    -----------
      Total Runs: 158
      Metric Samples: 1, Total: 158
      Events: 0, Total: 0
      Service Checks: 0, Total: 0
      Average Execution Time : 0ms
      
  
    io
    --
      Total Runs: 158
      Metric Samples: 26, Total: 4090
      Events: 0, Total: 0
      Service Checks: 0, Total: 0
      Average Execution Time : 0ms
      
  
    kubelet (1.4.0)
    ---------------
      Total Runs: 158
      Metric Samples: 116, Total: 18321
      Events: 0, Total: 0
      Service Checks: 3, Total: 474
      Average Execution Time : 912ms
      
  
    load
    ----
      Total Runs: 158
      Metric Samples: 6, Total: 948
      Events: 0, Total: 0
      Service Checks: 0, Total: 0
      Average Execution Time : 0ms
      
  
    memory
    ------
      Total Runs: 158
      Metric Samples: 17, Total: 2686
      Events: 0, Total: 0
      Service Checks: 0, Total: 0
      Average Execution Time : 5ms
      
  
    network (1.6.0)
    ---------------
      Total Runs: 158
      Metric Samples: 32, Total: 5056
      Events: 0, Total: 0
      Service Checks: 0, Total: 0
      Average Execution Time : 11ms
      
  
    ntp
    ---
      Total Runs: 158
      Metric Samples: 1, Total: 158
      Events: 0, Total: 0
      Service Checks: 1, Total: 158
      Average Execution Time : 0ms
      
  
    uptime
    ------
      Total Runs: 158
      Metric Samples: 1, Total: 158
      Events: 0, Total: 0
      Service Checks: 0, Total: 0
      Average Execution Time : 0ms
      
  
========
JMXFetch
========

  Initialized checks
  ==================
    no checks
    
  Failed checks
  =============
    no checks
    
=========
Forwarder
=========

  CheckRunsV1: 158
  Dropped: 0
  DroppedOnInput: 0
  Errors: 0
  Events: 0
  HostMetadata: 0
  IntakeV1: 14
  Metadata: 0
  Requeued: 0
  Retried: 0
  RetryQueueSize: 0
  Series: 0
  ServiceChecks: 0
  SketchSeries: 0
  Success: 330
  TimeseriesV1: 158

  API Keys status
  ===============
    https://6-4-2-app.agent.datadoghq.com,*************************624b7: API Key valid

==========
Logs Agent
==========

  Logs Agent is not running

=========
DogStatsD
=========

  Checks Metric Sample: 92246
  Event: 4
  Events Flushed: 4
  Number Of Flushes: 158
  Series Flushed: 73253
  Service Check: 2373
  Dogstatsd Metric Sample: 396

```

**Describe what happened:**

I have an EKS cluster which runs the datadog-agent:v6.x to report on custom metrics from my application. I am able to see the custom metric on my dashboard which is fowarded by the datadog agent (i verified using tcpdump on the port 8125 that the agent recieves this metric)
I want to also export this metric to prometheus, so i deployed the statsd_exporter as a daemonset on the cluster to convert the statsd style metrics to prometheus. 

From looking at the documentation 
(https://github.com/DataDog/datadog-agent/blob/master/pkg/config/config_template.yaml#L250-L256 )
I enabled the two variables by passing in the env variables to the datadog-agent. 

```
        - name: DD_STATSD_FORWARD_HOST
          value: 10.100.242.147 (clusterIP of the statsd_exporter daemonset)
        - name: DD_STATSD_FORWARD_PORT
          value: "9125"
```
But, i am unable to see any metrics forwarded to the exporter. It looks like the datadog-agent is not forwarding the metrics to the `statsd_exporter`
I have verified by pointing my application to the `statsd_exporter` and it works by transforming the statsd metrics into the prometheus style. 

Here is the daemonset spec for the datadog agent. 

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  creationTimestamp: 2018-09-23T06:45:01Z
  generation: 1
  labels:
    app: ddog-datadog
    chart: datadog-1.0.0
    heritage: Tiller
    release: ddog
  name: ddog-datadog
  namespace: default
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ddog-datadog
  template:
    metadata:
      labels:
        app: ddog-datadog
      name: ddog-datadog
    spec:
      containers:
      - env:
        - name: DD_API_KEY
          valueFrom:
            secretKeyRef:
              key: api-key
              name: ddog-datadog
        - name: DD_LOG_LEVEL
          value: DEBUG
        - name: KUBERNETES
          value: "yes"
        - name: DD_KUBERNETES_KUBELET_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: DD_USE_DOGSTATSD
          value: "true"
        - name: DD_DOGSTATSD_PORT
          value: "8125"
        - name: DD_DOGSTATSD_NON_LOCAL_TRAFFIC
          value: "true"
        - name: DD_STATSD_FORWARD_HOST
          value: 10.100.242.147
        - name: DD_STATSD_FORWARD_PORT
          value: "9125"
        image: datadog/agent:6.4.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - ./probe.sh
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: datadog
        ports:
        - containerPort: 8125
          hostPort: 8125
          name: dogstatsdport
          protocol: UDP
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: dockersocket
          readOnly: true
        - mountPath: /host/proc
          name: procdir
          readOnly: true
        - mountPath: /host/sys/fs/cgroup
          name: cgroups
          readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: ddog-datadog
      serviceAccountName: ddog-datadog
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/run/docker.sock
          type: ""
        name: dockersocket
      - hostPath:
          path: /proc
          type: ""
        name: procdir
      - hostPath:
          path: /sys/fs/cgroup
          type: ""
        name: cgroups
  templateGeneration: 1
  updateStrategy:
    type: OnDelete
```
Here is the daemonset spec for the `statsd_exporter`

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  generation: 2
  labels:
    app: statsd-exporter
    chart: statsd-exporter-0.1.0
    heritage: Tiller
    release: one
  name: one-statsd-exporter
  namespace: default
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: statsd-exporter
      release: one
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: statsd-exporter
        release: one
    spec:
      containers:
      - image: docker.io/prom/statsd-exporter:v0.7.0
        args:
          - "--statsd.listen-tcp=:9125"
          - "--statsd.listen-udp=:9125"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: prom-tcp
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: statsd-exporter
        ports:
        - containerPort: 9125
          name: statsd-udp
          protocol: UDP
        - containerPort: 9102
          name: prom-tcp
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: prom-tcp
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  templateGeneration: 2
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
```

**Describe what you expected:**

The datadog-agent should forward the metrics to my own statsd server (statsd_exporter in this case) which it does not do. 

**Steps to reproduce the issue:**
Apply the specs provided in the ticket.

**Additional environment details (Operating System, Cloud provider, etc):**
AWS EKS cluster.
