### ISSUE TITLE
[Logging] What is the relationship between journald check and log declarations

### ISSUE THREAD

**Issue by rromanchuk** [DataDog/datadog-agent#2529]
What is the relationship between `journald` and `logs:` declaration of type `journald`, should i not be using both?  Am i responsible for deduping by using `include_units` and `exclude_units` between service specific checks and the `journald` check? 

```yml
datadog_checks:
  journald:
    logs:
      - type: journald
        include_units:
          - sudo.service
          - sshd.service
          - cron.service
          - awsagent.service
          - systemd-journald
          - datadog-agent
  puma:
    init_config:
    logs:
      - type: journald
        path: /var/log/journal/
        include_units:
          - puma.service
        service: api
        source: ruby
        sourcecategory: worker
  shoryuken:
    init_config:
    logs:
      - type: journald
        path: /var/log/journal/
        include_units:
          - shoryuken.service
        service: shoryuken
        source: sqs
        sourcecategory: worker
  sidekiq:
    init_config:
    logs:
      - type: journald
        path: /var/log/journal/
        include_units:
          - sidekiq.service
        service: sidekiq
        source: redis
        sourcecategory: worker
```
