### ISSUE TITLE
Custom metrics provider should convert metrics / tags names into Kubernetes format.

### ISSUE THREAD

**Issue by renaudguerin** [DataDog/datadog-agent#2548]
Hello,

I'm using the Datadog Helm chart (datadog-1.5.1) with agent 6.5.2 and cluster-agent 0.10.0 on GKE (k8s 1.10.7) 
I've opened a support ticket about this, but since this is clearly a missing feature / bug in the custom metrics provider, I thought it would be worth opening an issue too.

I’m trying to use the Cluster Agent’s external metrics provider for Kubernetes autoscaling, following this doc : https://github.com/DataDog/datadog-agent/blob/master/docs/cluster-agent/CUSTOM_METRICS_SERVER.md

The use case is to autoscale a workers deployment based on the number of jobs in a Redis-based queue (we use the popular Bull package for NodeJS as our queue https://github.com/OptimalBits/bull ).

We've set up the redisdb check in the agent to monitor the length of a key named `bull:tasks:wait` (this is hardcoded in the Bull library). This ends up as a Datadog metric named `redis.key.length` with a `bull:tasks:wait` tag.

The doc says the metric/labels provided in the Kubernetes HPA manifest should be in Datadog format. So I did this :
```
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: bullworker
  namespace: production
spec:
  maxReplicas: 100
  minReplicas: 3
  metrics:
  - type: External
    external:
      metricName: redis.key.length
      metricSelector:
        matchLabels:
            redis_host: redis
            key: "bull:tasks:wait"
            cluster-name: production
      targetAverageValue: 5
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 100
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: bullworker
```

Unfortunately, the label/tag I need to filter on contains a colon “:”, and it seems like this isn’t allowed by Kubernetes :

>   Warning FailedGetExternalMetric 32s (x4 over 2m) horizontal-pod-autoscaler invalid label value: "bull:tasks:wait": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue', or 'my_value', or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
> Warning FailedComputeMetricsReplicas 32s (x4 over 2m) horizontal-pod-autoscaler failed to get redis.key.length external metric: invalid label value: "bull:tasks:wait": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue', or 'my_value', or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
> 

One possibility would be to remove illegal characters at the Redis check level. But it seems to me the right place to do this conversion is actually in the Custom Metrics provider, because this format requirement is specific to Kubernetes.

Can you help ? 
Thanks !
