### ISSUE TITLE
[BUG] k8s metrics for pods disappear as number of services increase 

### ISSUE THREAD

**Issue by duxing** [DataDog/datadog-agent#26479]
**Agent Environment**
```
Agent 7.53.0 - Commit: 0eec38d - Serialization version: v5.0.111 - Go version: go1.21.9
```
deployed via `helm` chart (`3.65.2`).
running on AWS EKS (1.29) (using `containerd` as runtime)

**Describe what happened:**
`datadog` has been working well on this cluster, reporting all the expected metrics until recently I started a particular test.
under this test, basic `kubernetes` metrics (e.g. `kubernetes.cpu.usage.total`) all disappeared for pods from my test workloads.

the test deployment I've set up is a simple hello world HTTP server without any traffic or modification before and after the test. the only thing I modified during the test is the number of replicas, ranging from 0 to 1000 pods but the same issue exists in any replicas setting.

the test setup is:
 - deploy the hello world service (1 `Deployment` with 5 replicas + 1 `Service`) to k8s and verify connectivity (`curl`): API works and metrics are showing (e.g. `max:kubernetes.cpu.usage.total{cluster_name:my-cluster, kube_namespace:my-ns, container_name:my-server} by {pod_name}`)
 - set up 800 `Service` objects that share the same selector as the `Service` in the same namespace. use `seq` and regex replace this can be easily done. At the end of this step, there should be 801 `Service`s in the `my-ns` namespace
 - set the deployment scale to 0: `kubectl scale --replicas=0 -n my-ns deploy/my-server`
 - scale up the deployment to `X` replicas: `kubectl scale --replicas=<X> -n my-ns deploy/my-server`. you can replicate this issue easily with a replica of 3 or 5.

datadog will report the metrics (for some of the pods, not all) for a couple of minutes, and then metrics from all of these pods disappear.

an example metric view tested with `X=50`:
![image](https://github.com/DataDog/datadog-agent/assets/1322437/273591fa-e616-48f6-ab64-3849b0f0fe16)

restarting the `agent` or `cluster-agent` don't solve the problem. checked logs from `agent` and `cluster-agent` and I didn't see anything helpful. checked resource usage for all `agent` and `cluster-agent` instances and they're fine: no CPU throttle or OOM. I've also tested bumping up the check tag cardinality and it didn't help either.

if I repeat the last 2 steps (scale down to 0 and back up), I'll see metrics for a couple of minutes again until getting into the same issue. The only "fix" is to remove all the artificially created services, which is part of my test.

I've opened a [support ticket](https://help.datadoghq.com/hc/en-us/requests/1717129) on this and 2 people have helped: I've tested suggestions on increasing check running and reducing unnecessary checks and none of the suggestions are fixing this issue. 

**Describe what you expected:**

I expect to see the `kubernetes` (and `containerd`) metrics during my test setup (with 801 services pointing to the same set of pods). there's maybe some limitation on `workloadmeta` causing this issue. if it is the case, this limitation needs to be better surfaced via logs or metrics or `agent status` output to help pin point what configuration change could have fixed this issue. 

**Steps to reproduce the issue:**
see "Describe what happened"

**Additional environment details (Operating System, Cloud provider, etc):**

my value override for helm chart:
```
datadog:
  clusterName: "my-cluster"
  logLevel: info

  dogstatsd:
    useHostPort: true
    nonLocalTraffic: true
    tagCardinality: high

  collectEvents: true

  checksCardinality: high
  kubelet:
    tlsVerify: true
    coreCheckEnabled: true

  leaderElection: true
  leaderLeaseDuration:  600

  clusterChecks:
    enabled: true
  kubeStateMetricsCore:
    enabled: true
  apm:
    portEnabled: true

  env:
    - name: DD_CHECK_RUNNERS
      value: "10"

  podLabelsAsTags:
    app: kube_app
    component: kube_component
    env: kube_env
    k8s-app: kube_k8s-app
    managed_by: kube_managed_by
    name: kube_name
    project: kube_project
    release: kube_release
    role: kube_role
    task_group: kube_task_group
    template-app: kube_template-app
    team: kube_team
    cluster_addon: kube_cluster_addon
  
  confd:
    go_expvar.yaml: |-
      init_config:
      instances:
        # monitor datadog-agent scheduler: ensure all checks are executed during the interval
          # "namespace" is used as prefix
        - namespace: datadog.agent
          # port needs to match `.Values.datadog.expvarPort`
          expvar_url: http://localhost:6000/debug/vars
          metrics:
            - path: scheduler/ChecksEntered
            - path: scheduler/Queues/.*/Size
              alias: datadog.agent.scheduler.queues.size
            - path: scheduler/Queues/.*/Interval
              alias: datadog.agent.scheduler.queues.interval
            - path: scheduler/QueuesCount

  helmCheck:
    enabled: true
    collectEvents: true

  prometheusScrape:
    enabled: false
    serviceEndpoints: false

  criSocketPath: /var/run/containerd/containerd.sock

  ignoreAutoConfig:
   - istio

agents:
  enabled: true
  podAnnotations:
    sidecar.istio.io/inject: "false"
  additionalLabels:
    cluster_addon: "true"
  containers:
    agent:
      logLevel: info
      resources:
        requests:
          cpu: 512m
          memory: 1Gi
        limits:
          cpu: "1"
          memory: 2Gi
    traceAgent:
      resources:
        requests:
          cpu: 150m
          memory: 128Mi
        limits:
          cpu: 300m
          memory: 512Mi
    processAgent:
      resources:
        requests:
          cpu: 60m
          memory: 512Mi
        limits:
          cpu: 200m
          memory: 1Gi
  useConfigMap: true
  customAgentConfig:
    histogram_aggregates:
      - avg
      - count 
    histogram_percentiles:
      - "0.95"
    apm_config:
      apm_non_local_traffic: true
    jmx_use_container_support: true
    cloud_provider_metadata:
      - "aws"
  useHostNetwork: true
  tolerations:
    - operator: "Exists"
  priorityClassName: system-node-critical

  rbac:
    create: true
    serviceAccountName: datadog
    automountServiceAccountToken: true

clusterAgent:
  enabled: true
  replicas: 3
  resources:
    requests:
      cpu: "1"
      memory: 512Mi
    limits:
      cpu: "2"
      memory: 2Gi
  command: ["/entrypoint.sh", "datadog-cluster-agent", "start"]
  metricsProvider:
    enabled: true
  podAnnotations:
    sidecar.istio.io/inject: "false"
  additionalLabels:
    cluster_addon: "true"
  rbac:
    create: true
    serviceAccountName: datadog-cluster-agent
    automountServiceAccountToken: true
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
    effect: NoSchedule
  datadog_cluster_yaml:
    cloud_provider_metadata:
      - "aws"
```
