### ISSUE TITLE
prometheus bearer token

### ISSUE THREAD

**Issue by bradrydzewski** [DataDog/datadog-agent#2667]
I apologize if this is the wrong place to make such a request, but I'm having difficulty going through the support channels. I would like to scrape a prometheus `/metrics` endpoint with the datadog agent, however, the metrics endpoint is protected and requires a bearer token for authorization.

When you configure a scraper in prometheus you can specify a bearer_token parameter [1]. It would be great if this could be configured with the datadog agent as well (If this is already possible, my apologies). Thanks!

```
# Sets the `Authorization` header on every scrape request with
# the configured bearer token. It is mutually exclusive with `bearer_token_file`.
[ bearer_token: <secret> ]
```

[1] https://prometheus.io/docs/prometheus/latest/configuration/configuration/

**Comment by hkaj** [comment]
Thanks for reaching out, I have a PR open to document that actually: https://github.com/DataDog/integrations-core/pull/2585
So basically you need to expose the bearer token as an environment variable in the datadog agent pod, and then use add this to your app pod annotations:
```yaml
         ad.datadoghq.com/slave.check_names: '["openmetrics"]'
         ad.datadoghq.com/slave.init_configs: '[{}]'
         ad.datadoghq.com/slave.instances: '[{"prometheus_url": "http://%%host%%:<MY_EXPORTER_PORT>/metrics","namespace": "<MY_APP>","metrics": ["*"],"extra_headers": {"Authorization": "Bearer %%env_<MY_TOKEN_ENV_VAR>%%"}}]'
```

And the agent will interpolate the `%%env_TOKEN%%` part with your token. Does that address your use case?

**Comment by luanguimaraesla** [comment]
@hkaj I tried to set up the openmetrics for the kube-apiserver following the [example](https://github.com/DataDog/integrations-core/blob/master/openmetrics/datadog_checks/openmetrics/data/conf.yaml.example) you modified. This is my configuration file 

```yaml
apiVersion: v1
data:
  kube-apiserver-metrics.yaml: |-
    init_config:
    instances:
    - prometheus_url: "https://kubernetes.default.svc.cluster.local.:443/metrics"
      namespace: "kube-apiserver"
      metrics:
        - apiserver_request_count
      ssl_ca_cert: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      extra_headers:
        Authorization: "Bearer %%env_SERVICEACCOUNT_BEARER_TOKEN%%"
      max_returned_metrics: 1
kind: ConfigMap
metadata:
  name: datadog-prometheus
  namespace: datadog
```

The envvar `SERVICEACCOUNT_BEARER_TOKEN` is configured correctly and I can execute `curl` inside pod:

```bash
curl --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
-H "Authorization: Bearer ${SERVICEACCOUNT_BEARER_TOKEN}" \
https://kubernetes.default.svc.cluster.local.:443/metrics
```

Datadog-agent still receiving **Unauthorized 401** from the kube-apiserver
```
[ AGENT ] 2018-11-21 15:39:24 UTC | ERROR | (runner.go:289 in work) | Error running check openmetrics: [{"message": "401 Client Error: Unauthorized for url: https://kubernetes.default.svc.cluster.local.:443/metrics", "traceback": "Traceback (most recent call last):\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/base.py\", line 366, in run\n    self.check(copy.deepcopy(self.instances[0]))\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/openmetrics/base_check.py\", line 45, in check\n    self.process(scraper_config)\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/openmetrics/mixins.py\", line 286, in process\n    for metric in self.scrape_metrics(scraper_config):\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/openmetrics/mixins.py\", line 254, in scrape_metrics\n    response = self.poll(scraper_config)\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/openmetrics/mixins.py\", line 401, in poll\n    response.raise_for_status()\n  File \"/opt/datadog-agent/embedded/lib/python2.7/site-packages/requests/models.py\", line 939, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nHTTPError: 401 Client Error: Unauthorized for url: https://kubernetes.default.svc.cluster.local.:443/metrics\n"}]
```

Do you think there is any misconfiguration?
