### ISSUE TITLE
datadog v6 docker issue

### ISSUE THREAD

**Issue by hryamzik** [DataDog/datadog-agent#2685]
Agent installed with an ansible [role](https://github.com/DataDog/ansible-datadog) fails to monitor docker:

```
    docker
    ------
        Instance ID: docker [ERROR]
        Total Runs: 109
        Metric Samples: 0, Total: 0
        Events: 0, Total: 0
        Service Checks: 0, Total: 0
        Average Execution Time : 0s
        Error: permanent failure in dockerutil: retry number exceeded
        No traceback
        Warning: Error initialising check: [permanent failure in dockerutil: retry number exceeded]
```

The issue is that `dd-agent` user isn't member of a `docker` group.

Worked fine with v5. Here's a workaround, I use it in a role that uploads my configs and has official role as a dependency:

```yml
- name: ensure dd-agent is in docker group
  user:
    name: dd-agent
    groups: docker
    append: yes
  notify: restart datadog-agent
```
