### ISSUE TITLE
[BUG]  config key otlp_config.metrics.sums.initial_cumulative_monotonic_value is unknown

### ISSUE THREAD

**Issue by piotr1212** [DataDog/datadog-agent#27477]
Upgrade from agent 7.52.1 to 7.53.0 I got the following log message:

```
 (pkg/util/log/log.go:871 in func1) | config key otlp_config.metrics.sums.initial_cumulative_monotonic_value is unknown
```

I don't see any deprecation notices or breaking changes in the changelog. The code still seems to support this configuration. We need this feature. The otlp section from our config:
```
otlp_config:
  metrics:
    resource_attributes_as_tags: true
    sums:
      initial_cumulative_monotonic_value: auto
  receiver:
    protocols:
      grpc:
        endpoint: 127.0.0.1:4317
```

**Agent Environment**
Agent 7.53.0 - Commit: 0eec38d - Serialization version: v5.0.111 - Go version: go1.21.9

on Ubuntu

**Describe what happened:**
config key not accepted

**Describe what you expected:**
config key to be accepted

**Steps to reproduce the issue:**
Set otlp_config.metrics.sums.initial_cumulative_monotonic_value in the config of agent 7.53 or higher and start it. Notice log warning about config key unknonw

**Additional environment details (Operating System, Cloud provider, etc):**
Ubuntu
