### ISSUE TITLE
[BUG] KSM: HPA metrics don't get standard labels applied

### ISSUE THREAD

**Issue by shivshav** [DataDog/datadog-agent#27524]
**Agent Environment**

Deployed in Kubernetes using the [official Datadog Helm chart](https://github.com/DataDog/helm-charts/tree/main/charts/datadog).

Versions:
- Helm chart: 3.67.5
- Agent: 7.54.0
- Cluster Agent: 7.54.0
 
Our whole `kubeStateMetricsCore` configuration from our usage of the Datadog Helm chart
```yaml
...
    kubeStateMetricsCore:
      enabled: true
      # Don't run on main agent daemonset pods to keep resource usage stable across pods
      useClusterCheckRunners: true
      collectVpaMetrics: true
      # Common labels found on most K8S resources that we'd like as tags in DD
      # See https://docs.datadoghq.com/integrations/kubernetes_state_core/?tab=helm#default-labels-as-tags for labels
      # already collected
      ksm_common_label_map: &ksm_common_label_map
        # Our custom labels
        app: leafly_app
        notifications_leafly_io_slack: notifications_route_slack
        notifications_leafly_io_opsgenie: notifications_route_opsgenie
        process: leafly_process
        release: leafly_release
        # External labels we wanna collect
        k8s_app: kube_system_app  # usually provided by kOps on manifests it manages
      labelsAsTags:
        container: *ksm_common_label_map
        cronjob: *ksm_common_label_map
        daemonset: *ksm_common_label_map
        deployment: *ksm_common_label_map
        endpoint: *ksm_common_label_map
        horizontalpodautoscaler: *ksm_common_label_map
        ingress: *ksm_common_label_map
        job: *ksm_common_label_map
        node:
          kops_k8s_io_instancegroup: kops_instancegroup
          leafly_node_util: util_node
        pdb: *ksm_common_label_map
        persistentvolumeclaim: *ksm_common_label_map
        pod: *ksm_common_label_map
        replicaset: *ksm_common_label_map
        service: *ksm_common_label_map
        statefulset: *ksm_common_label_map
...
```

**Describe what happened:**
Our KSM-based HPA metrics do not have the [default labels](https://docs.datadoghq.com/integrations/kubernetes_state_core/?tab=helm#default-labels-as-tags) attached to them unlike other resources (see screenshots below).

What our tags look like for a `kubernetes_state.hpa.` metric (`kubernetes_state.hpa.max_replicas` in this case)
<img width="285" alt="Screenshot 2024-07-11 at 11 39 47 AM" src="https://github.com/DataDog/datadog-agent/assets/6853278/88ef7102-675a-48c4-86ef-dc3343cb179d">

What our tags look like for another `kubernetes_state.` metric that is working as expected (`kubernetes_state.deployment.replicas_ready` in this case)
<img width="328" alt="Screenshot 2024-07-11 at 11 40 13 AM" src="https://github.com/DataDog/datadog-agent/assets/6853278/08cdb06a-47ad-4866-917b-0a0038ac41c7">

**Describe what you expected:**
I expect most of the `kubernetes_state.hpa.*` metrics to have the following tags attached to them with no configuration on our end based on the [documentation here](https://docs.datadoghq.com/integrations/kubernetes_state_core/?tab=helm#default-labels-as-tags) (I can confirm the labels exist on our resources)
- `kube_app_name`
- `kube_app_instance`
- `kube_app_version`
- `kube_app_component`
- `kube_app_part_of`
- `kube_app_managed_by`
- `helm_chart`
- `env`
- `service`
- `version`

**Steps to reproduce the issue:**
1. Deploy Datadog helm chart to Kubernetes cluster with `kubeStateMetricsCore` values config noted above
2. Deploy HPA resource that utilizes standard K8S labels and/or Datadog Unified Service Tagging labels
3. Observe metrics emitted by Datadog do not have the aforementioned tags attached

**Additional environment details (Operating System, Cloud provider, etc):**

# Potential Fix?
I noticed the `defaultLabelJoins` function [here](https://github.com/DataDog/datadog-agent/blob/main/pkg/collector/corechecks/cluster/ksm/kubernetes_state_defaults.go#L139) **does not** include `kube_horizontalpodautoscaler_labels` in the returned `map`, which [is what KSM calls the label metric it emits](https://github.com/kubernetes/kube-state-metrics/blob/85d1423b5b896f4fbce8394afed20cfe17371251/internal/store/horizontalpodautoscaler.go#L49). So maybe that's all that needs to happen for this issue to be resolved? But not certain.
