### ISSUE TITLE
Problem getting DD_DOCKER_LABELS_AS_TAGS to work in simple docker-compose setup.

### ISSUE THREAD

**Issue by automatthew** [DataDog/datadog-agent#2788]
**Describe what happened:**

Docker container labels are not getting collected as tags when the DD_DOCKER_LABELS_AS_TAGS is set to the example from the [agent documentation](https://docs.datadoghq.com/agent/basic_agent_usage/docker/#tagging):

```
DD_DOCKER_LABELS_AS_TAGS='{"com.docker.compose.service":"service_name"}'
```

Datadog autodiscovers redis, but only sets the standard redisdb check tags.  I set a tag in the DD_TAGS variable to verify that the env vars were passing correctly, and that tag does appear in the datadog metrics.

**Describe what you expected:**

I expected the `com.docker.compose.service` label for the my-redis container to be collected by datadog as the tag `service`.

**Steps to reproduce the issue:**

Using this docker-compose file, run `docker-compose up`.  Check the tags collected for the redisdb check using `agent configcheck`

```yaml
version: "2"

services:

  my-redis:
    image: redis

  datadog:
    image: datadog/agent:latest-jmx
    environment:
      - DD_API_KEY=xyxyxy
      - DD_DOCKER_LABELS_AS_TAGS='{"com.docker.compose.service":"service_name"}'
      - DD_TAGS="reason:problem_with_tagging"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
```

The tags shown in the configcheck:

```
=== redisdb check ===
Source: File
Instance ID: redisdb:2cd0d1695bb262fa
host: 172.19.0.2
port: "6379"
tags:
- image_name:redis
- short_image:redis
- image_tag:latest
- docker_image:redis:latest
~
Auto-discovery IDs:
* redis
===
```

**Additional environment details (Operating System, Cloud provider, etc):**

I tested this on an EC2 instance running Ubuntu.
