### ISSUE TITLE
[BUG] otel-agent binary not present in Docker image

### ISSUE THREAD

**Issue by nickvecelliooo** [DataDog/datadog-agent#28523]
**Agent Environment**
Initially found on 7.55.2, also tested on 7.55.3, latest, and 7-beta (the most recent push to dockerhub)

**Describe what happened:**
When `otelCollector.enabled` is set to `true` in the Helm chart, [a container is added to the pod called ](https://github.com/DataDog/helm-charts/blob/main/charts/datadog/templates/_container-otel-agent.yaml#L9)`otel-agent`, with a command of 
```
  command: ["otel-agent", "-foreground", "-config={{ template "datadog.otelconfPath" . }}/datadog.yaml"]
```
When the container tries to start, the following occurs:
```
    message: 'failed to create containerd task: failed to create shim task: OCI
      runtime create failed: runc create failed: unable to start container
      process: exec: "otel-agent": executable file not found in $PATH: unknown'
```

**Describe what you expected:**
The otel-agent binary to be present and the container to start

**Steps to reproduce the issue:**
Install the Datadog Helm chart with the below
```
datadog:
  apiKey: <yoink>
  clusterName: demo
  otelCollector:
    enabled: true
```
and the pod will not start.

This can also be tested in the images on dockerhub
```
$ docker run -it datadog/agent:7-beta bash
root@a5bfaa78b3f9:/# find / -name 'otel*'
/opt/entrypoints/otel-agent
root@a5bfaa78b3f9:/# cat /opt/entrypoints/otel-agent 
#!/usr/bin/env bash
set -euo pipefail

exec /opt/datadog-agent/embedded/bin/otel-agent --config /etc/datadog-agent/otel-config.yaml
root@a5bfaa78b3f9:/# /opt/datadog-agent/embedded/bin/otel-agent
bash: /opt/datadog-agent/embedded/bin/otel-agent: No such file or directory
```

**Comment by adaosantos** [comment]
Same problem here =/

**Comment by Gaelik-git** [comment]
I think this is because the feature is in beta:

You can find from this example in the helm repo : https://github.com/DataDog/helm-charts/blob/main/examples/datadog/agent_otel_collector.yaml that the image used is a not the latest one
```yml
agents:
  image:
    repository: datadog/agent-dev
    tag: nightly-ot-beta-main
    doNotCheckTag: true
```

When testing this image it seems to work

**Comment by sanglt** [comment]
Hi team,

Do you have any update on this work? We are want to use the otel collector feature and waiting this issue.

**Comment by pilab-gwon** [comment]
Currently, not working..
Has anyone resolved it?

```
Usage:
  otel-agent [command] [flags]
  otel-agent [command]

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  run         Starting OpenTelemetry Collector
  version     Print the version info

Flags:
      --config --config=file:/path/to/first --config=file:path/to/second   Locations to the config file(s), note that only a single location can be set per flag entry e.g. --config=file:/path/to/first --config=file:path/to/second. (default [])
      --core-config string                                                 Location to the Datadog Agent config file. (default "")
      --feature-gates flag                                                 Comma-delimited list of feature gate identifiers. Prefix with '-' to disable the feature. '+' or no prefix will enable the feature. (default connector.datadogconnector.NativeIngest,-connector.spanmetrics.legacyMetricNames,-filelog.allowFileDeletion,filelog.allowHeaderMetadataParsing,filelog.container.removeOriginalTimeField,-filelog.mtimeSortType,-filter.filterlog.useOTTLBridge,-filter.filtermetric.useOTTLBridge,-filter.filterspan.useOTTLBridge,hostmetrics.process.bootTimeCache,-k8sattr.fieldExtractConfigRegex.disallow,k8sattr.rfc3339,logs.assignKeys,logs.jsonParserArray,-parser.uri.ecscompliant,pkg.translator.prometheus.NormalizeName,-pkg.translator.prometheus.PermissiveLabelSanitization,processor.resourcedetection.hostCPUSteppingAsString,-processor.resourcedetection.removeGCPFaasID,-processor.tailsamplingprocessor.metricstatcountspanssampled,processor.transform.ConvertBetweenSumAndGaugeMetricContext,receiver.hostmetrics.normalizeProcessCPUUtilization,receiver.jaeger.DisableRemoteSampling,-receiver.prometheusreceiver.EnableNativeHistograms,-receiver.prometheusreceiver.RemoveLegacyResourceAttributes,-receiver.prometheusreceiver.UseCreatedMetric,-service.noopTracerProvider,-service.profilesSupport,telemetry.UseLocalHostAsDefaultMetricsAddress,-telemetry.disableAddressFieldForInternalTelemetry,-telemetry.disableHighCardinalityMetrics,telemetry.useOtelWithSDKConfigurationForInternalTelemetry,-transform.flatten.logs)
  -h, --help                                                               help for otel-agent
      --set func                                                           Set arbitrary component config property. The component has to be defined in the config file and the flag has a higher precedence. Array config properties are overridden and maps are joined. Example --set=processors.batch.timeout=2s
      --sync-delay duration                                                Delay before first config sync. (default 0s)
      --sync-to duration                                                   Timeout for sync requests. (default 3s)

Use "otel-agent [command] --help" for more information about a command.

Error: invalid log level (INFO) set in the Datadog Agent configuration
```

**Comment by truthbk** [comment]
Hey @sanglt sorry for the slow response. As mentioned above, the feature is indeed still in `beta`. There are several beta images available (you can identify them with the `ot-beta` suffix in the image tags). If you are interested in an extensive use of the feature, I would recommend you reach out to us to join the beta testing program.

Thank you!

**Comment by gouravsw** [comment]
Hello All, Is there any update on this issue. We are planning to use this feature but getting the same error as mentioned above?

**Comment by pilab-gwon** [comment]
I'm currently running the latest stable version (datadog-3.129.0) of the Datadog Agent, and it seems to be working fine now without having to use `nightly-ot-beta-main`.

**Comment by krlv** [comment]
The Datadog Distribution of the OpenTelemetry (DDOT) Collector became generally available with the Agent [v7.64.0 release](https://github.com/DataDog/datadog-agent/releases/tag/7.64.0)
You no longer need to use `ot-beta` images or override `agents.image.repository`.

To install/enable DDOT Collector, please follow our [official documentation](https://docs.datadoghq.com/opentelemetry/setup/ddot_collector/install/kubernetes?tab=datadogoperator).

---

### Kubernetes with Datadog Operator

Add this to your `datadog-agent.yaml`:

```yaml
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    clusterName: <CLUSTER_NAME>
    site: <DATADOG_SITE>
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key

  # Enable Features
  features:
    otelCollector:
      enabled: true
      ports:
        - containerPort: 4317
          hostPort: 4317
          name: otel-grpc
        - containerPort: 4318
          hostPort: 4318
          name: otel-http
      conf:
        configMap:
          name: otel-agent-config-map
```

Operator guide: https://docs.datadoghq.com/opentelemetry/setup/ddot_collector/install/kubernetes/?tab=datadogoperator#install-the-datadog-agent-with-opentelemetry-collector

---

### Kubernetes with Helm

Add this to your `datadog-values.yaml`:

```yaml
datadog:
  site: <DATADOG_SITE>
  apiKeyExistingSecret: datadog-secret

  otelCollector:
    enabled: true
    ports:
      - containerPort: "4317"
        hostPort: "4317"
        name: otel-grpc
      - containerPort: "4318"
        hostPort: "4318"
        name: otel-http
```

Helm guide: https://docs.datadoghq.com/opentelemetry/setup/ddot_collector/install/kubernetes/?tab=helm#install-the-datadog-agent-with-opentelemetry-collector

---

### Linux VM or Bare Metal

Run the one-liner to install the Agent with the DDOT Collector:

```bash
DD_API_KEY=<DATADOG_API_KEY> \
DD_SITE="datadoghq.com" \
DD_OTELCOLLECTOR_ENABLED=true \
DD_AGENT_MAJOR_VERSION=7 \
DD_AGENT_MINOR_VERSION=70.0-1 \
bash -c "$(curl -L https://install.datadoghq.com/scripts/install_script_agent7.sh)"
```

Linux guide: https://docs.datadoghq.com/opentelemetry/setup/ddot_collector/install/linux/

---

If you were previously using a pre-release image, please migrate to the GA setup above by removing `agents.image.*` overrides.

---

### References:

- Blog announcement and GA update: [Unify OpenTelemetry and Datadog with the Datadog Distribution of the OTel Collector](https://www.datadoghq.com/blog/datadog-distribution-otel-collector/)
- Documentation: [Datadog Distribution of OpenTelemetry Collector](https://docs.datadoghq.com/opentelemetry/setup/ddot_collector)
- Architecture Center: [Monitoring Kubernetes with Datadog Distribution of the OpenTelemetry (DDOT) Collector](https://www.datadoghq.com/architecture/monitoring-kubernetes-with-datadog-distribution/)
