### ISSUE TITLE
Error ‘failed to clone3: Invalid argument’ when launching Datadog Agent 7 on Cloudrun

### ISSUE THREAD

**Issue by SakagamiKazuto** [DataDog/datadog-agent#28911]
## Overview
When starting Datadog Agent 7 on Cloudrun, after the error ‘failed to clone3: Invalid argument’, the log ‘Exiting concentrator, computing remaining stats’ appears and the process is The process is killed.

## Environments
```
image: gcr.io/datadoghq/agent:7
env:
- name: DD_SITE
  value: datadoghq.com
- name: DD_HOSTNAME
  value: <our-hostname>
- name: DD_APM_ENABLED
  value: 'true'
- name: DD_API_KEY
  value: <our-datadog-api-key>
- name: DD_REMOTE_CONFIGURATION_ENABLED
  value: 'false'
```

## Logs
<img width="1216" alt="スクリーンショット 2024-08-30 12 08 37" src="https://github.com/user-attachments/assets/f70092aa-09fc-444b-a859-792012b4be96">
<img width="1187" alt="スクリーンショット 2024-08-30 12 08 07" src="https://github.com/user-attachments/assets/0eee30a5-1060-4b10-864b-d9b83d79bc43">
<img width="1227" alt="スクリーンショット 2024-08-30 12 05 10" src="https://github.com/user-attachments/assets/85b99fc0-6ae1-4fc8-b29e-72cdf1762b96">

Please let me know if you need any other information, thank you.
