### ISSUE TITLE
Tag extraction for log tags

### ISSUE THREAD

**Issue by george-miller** [DataDog/datadog-agent#2915]
I am running the latest Datadog agent as a DaemonSet on my Kubernetes cluster.  I am trying to apply `log_processing_rules` to a group of pods, all who have the label `app: foo`.  I know I could do this as a pod annotation, but I do not want to have duplicate configs everywhere and force my developers to write those annotations to get the benefits of `log_processing_rules`.  

As far as I understand, you can only assign log configs to a subset of pods by using the `source` or `service` tags.  I want to globally define log configs for all pods with the `app: foo` label in the agent's config directory (for example in /etc/datadog-agent/conf.d/foo.d/conf.yaml) so my developers don't have to put duplicate annotations on all their pods.

I see two solutions:
1. Either allow Tag extraction for log tags so things would be tagged with:
```
kubernetes_pod_labels_as_tags:
  app: service  # Make the service tag have the value of the app label
```
and those tags would apply to logs (not just metrics) or

2. Allow me to define arbitrary tags to filter on, which might end up in a config like this:
```
    logs:
    - kube_app: foo
      log_processing_rules:
      - type: "multi_line"
        name: "new_log_start_with_date"
        pattern: .\d{2}:\d{2}:\d{2}
```
