### ISSUE TITLE
proposal: allow setting ignore_resources via env. var

### ISSUE THREAD

**Issue by jontonsoup** [DataDog/datadog-agent#2917]
We use the gin tracer and produce over 20k health checks an hour (microservices). Is there any way to filter out the health checks so we don't go above our max? 

Thanks!

**Comment by nic-lan** [comment]
Hi, 
i have a cluster agent with `DD_APM_IGNORE_RESOURCES` eq to '["GET /ping"]'.

The issue that I experience is that after setting the env with above value not only the `ping` request is filtered out ( which is what i want ) but also all the other resources ( example `POST api/v2/submissions/validate`).

here below the cluster agent env part:
```
- env:
        - name: DD_LOGS_ENABLED
          value: "true"
        - name: DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL
          value: "true"
        - name: DD_APM_ENABLED
          value: "true"
        - name: DD_API_KEY
          value: 123456789abcde
        - name: DD_COLLECT_KUBERNETES_EVENTS
          value: "true"
        - name: DD_LEADER_ELECTION
          value: "true"
        - name: KUBERNETES
          value: "true"
        - name: DD_PROCESS_AGENT_ENABLED
          value: "true"
        - name: DD_DOGSTATSD_NON_LOCAL_TRAFFIC
          value: "true"
        - name: DD_APM_ANALYZED_SPANS
          value: my-service|rack.request=1
        - name: DD_APM_IGNORE_RESOURCES
          value: '["GET /ping"]'
        - name: DD_KUBERNETES_KUBELET_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
  image: datadog/agent:latest
```

Should i also connect with the support team or this is the right place ?
