### ISSUE TITLE
Please tell me how to collect EKS Control Plane metrics in helm method

### ISSUE THREAD

**Issue by derekcha** [DataDog/datadog-agent#29325]
I want to collect the Control Plane metrics of the EKS I am using via Datadog Agent. So I looked for the manual and found this [link](https://docs.datadoghq.com/containers/kubernetes/control_plane/?tab=helm#EKS).
```
annotations:
  ad.datadoghq.com/endpoints.check_names: '["kube_apiserver_metrics"]'
  ad.datadoghq.com/endpoints.init_configs: '[{}]'
  ad.datadoghq.com/endpoints.instances:
    '[{ "prometheus_url": "https://%%host%%:%%port%%/metrics", "bearer_token_auth": "true" }]'
```
However, the way I want to do it is using the helm way (injecting confd into agent) rather than adding annotations directly to kubernetes-api service, because I want to unify it with adding other metric collections.

Can you tell me how to collect eks control plane metrics by adding confd?
