### ISSUE TITLE
[BUG] `CrashLoopBackOff` after upgrading Datadog Agent to version `7.57.0` on AKS with security context 

### ISSUE THREAD

**Issue by LQss11** [DataDog/datadog-agent#29427]
**Agent Environment**  
- **Agent version**: 7.57.0  
- **Cluster Agent version**: 7.57.0  
- **Operating System**: Linux  
- **Cloud Provider**: Azure  

**Describe what happened:**  
We upgraded both the Cluster Agent and Datadog Agent from version 7.56.2 to 7.57.0. After the upgrade, the Datadog Agent began failing with a `CrashLoopBackOff` error. We were able to resolve the issue by downgrading the Datadog Agent back to version 7.56.2. However, we are concerned about compatibility issues when running different versions of the Cluster Agent and Datadog Agent.

The error encountered in the Datadog Agent logs is as follows:  
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7642b8f]

goroutine 668 [running]:
github.com/DataDog/datadog-agent/pkg/logs/launchers/integration.(*Launcher).run(0x0)
        /omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/logs/launchers/integration/launcher.go:78 +0x2f
created by github.com/DataDog/datadog-agent/pkg/logs/launchers/integration.(*Launcher).Start in goroutine 345
        /omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/logs/launchers/integration/launcher.go:66 +0x4f
```

The issue occurs when applying the following security context to the agent container:
```yaml
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 100
```

**Describe what you expected:**  
We expected the Datadog Agent to run successfully on version 7.57.0 with the specified security context applied. Additionally, we expect both the Cluster Agent and Datadog Agent to work on version 7.57.0 without encountering the `CrashLoopBackOff` error.

**Steps to reproduce the issue:**  
1. Upgrade both the Datadog Agent and Cluster Agent to version 7.57.0.
2. Apply the following configuration for the agents and security context:

```yaml
agents:
  containers:
    agent:
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 100
    initContainers:
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 100
    processAgent:
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 100
    traceAgent:
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 100
  image:
    doNotCheckTag: true
    tag: 7.57.0

clusterAgent:
  admissionController:
    configMode: service
    enabled: true
    mutateUnlabelled: true
  containers:
    clusterAgent:
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 100
    initContainers:
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 100
  createPodDisruptionBudget: true
  env:
  - name: DD_ADMISSION_CONTROLLER_AUTO_INSTRUMENTATION_INIT_SECURITY_CONTEXT
    value: '{"capabilities":{"drop":["ALL"]},"runAsNonRoot":true,"runAsUser":10000,"readOnlyRootFilesystem":true,"allowPrivilegeEscalation":false,"seccompProfile":{"type":"RuntimeDefault"}}'
  - name: DD_APM_INSTRUMENTATION_VERSION
    value: v1
  image:
    doNotCheckTag: true
    tag: 7.57.0
  replicas: 2

clusterChecksRunner:
  enabled: true
  securityContext:
    runAsNonRoot: true
    runAsUser: 100

datadog:
  apiKeyExistingSecret: datadog-secret
  apm:
    instrumentation:
      enabled: false
    portEnabled: true
    socketEnabled: false
  kubeStateMetricsCore:
    useClusterCheckRunners: true
  kubelet:
    tlsVerify: false
  logLevel: DEBUG
  logs:
    containerCollectAll: true
    enabled: true
  processAgent:
    enabled: true
    processCollection: true
  secretBackend:
    command: /readsecret_multiple_providers.sh
  securityContext:
    runAsNonRoot: true
    runAsUser: 100
  site: datadoghq.com
  tags:
  - env:prod

providers:
  aks:
    enabled: true

targetSystem: linux
```

**Additional environment details (Operating System, Cloud provider, etc):**  
- **Cluster**: AKS
