### ISSUE TITLE
[BUG] Automatic version tagging for containerized environments doesn't work

### ISSUE THREAD

**Issue by yoav-klein** [DataDog/datadog-agent#29425]
**Agent Environment**
Agent version: 7.55.2

**Describe what happened:**
The docs in https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging/?tab=kubernetes 
state that the `version` tag should be taken from the `image_tag`. Therefore, for the following pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: my-app
    tags.datadoghq.com/env: "staging"
    tags.datadoghq.com/service: "mysvc"
spec:
  containers:
  - name: nginx
    image: yoavklein3/nginx:0.1
    ports:
    - containerPort: 80
```

the `version` tag should be `0.1`.  But I don't see any version tag on the logs generated by this container.

**Describe what you expected:**
the `version` tag should be `0.1`.  But I don't see any version tag on the logs generated by this container.

**Steps to reproduce the issue:**
1. Install the Datadog Agent using the Datadog Operator on a Kubernetes cluster.
2. Deploy the following pod:

```
apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: my-app
    tags.datadoghq.com/env: "staging"
    tags.datadoghq.com/service: "mysvc"
spec:
  containers:
  - name: nginx
    image: yoavklein3/nginx:0.1
    ports:
    - containerPort: 80
```

**Additional environment details (Operating System, Cloud provider, etc):**
