### ISSUE TITLE
"Dogstatsd: error parsing metrics: invalid field number" from Istio

### ISSUE THREAD

**Issue by michaelkipper** [DataDog/datadog-agent#2982]
**Output of the info page (if this is a bug)**
```
root@gke-istio-staging-19-default-pool-51acdfca-gwck:/# agent status
Getting the status from the agent.

==============
Agent (v6.9.0)
==============

  Status date: 2019-02-03 02:33:42.371748 UTC
  Pid: 374
  Python Version: 2.7.15
  Logs: 
  Check Runners: 4
  Log Level: info

  Paths
  =====
    Config File: /etc/datadog-agent/datadog.yaml
    conf.d: /etc/datadog-agent/conf.d
    checks.d: /etc/datadog-agent/checks.d

  Clocks
  ======
    NTP offset: -552µs
    System UTC time: 2019-02-03 02:33:42.371748 UTC

  Host Info
  =========
    bootTime: 2019-02-02 05:43:51.000000 UTC
    kernelVersion: 4.14.65&#43;
    os: linux
    platform: debian
    platformFamily: debian
    platformVersion: buster/sid
    procs: 75
    uptime: 56s

  Hostnames
  =========
    host_aliases: [gke-istio-staging-19-default-pool-51acdfca-gwck.istio-20180824 gke-istio-staging-19-default-pool-51acdfca-gwck]
    hostname: gke-istio-staging-19-default-pool-51acdfca-gwck.c.istio-20180824.internal
    socket-fqdn: gke-istio-staging-19-default-pool-51acdfca-gwck.c.istio-20180824.internal.
    socket-hostname: gke-istio-staging-19-default-pool-51acdfca-gwck
    hostname provider: gce
    unused hostname providers:
      configuration/environment: hostname is empty
```

**Describe what happened:**
Istio Pilot is set up like so:

```yaml
  containers:
  ...
  - args:
    - proxy
    - --serviceCluster
    - istio-pilot
    - --templateFile
    - /etc/istio/proxy/envoy_pilot.yaml.tmpl
    - --statsdUdpAddress
    - $(HOST_IP):8125
    - --controlPlaneAuthPolicy
    - MUTUAL_TLS
    env:
    ...
    - name: HOST_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
```

The DataDog Agent is running as a `DaemonSet`.

I'm getting thousands of log messages like this:

```
[ AGENT ] 2019-02-03 02:55:13 UTC | ERROR | (server.go:252 in worker) | Dogstatsd: error parsing metrics: invalid field number for "envoy.cluster.outbound|80||heapster.kube-system.svc.cluster.local.membership_total:1|g"
[ AGENT ] 2019-02-03 02:55:13 UTC | ERROR | (server.go:252 in worker) | Dogstatsd: error parsing metrics: invalid field number for "envoy.cluster.outbound|443||kubernetes-dashboard.kube-system.svc.cluster.local.membership_total:1|g"
[ AGENT ] 2019-02-03 02:55:13 UTC | ERROR | (server.go:252 in worker) | Dogstatsd: error parsing metrics: invalid field number for "envoy.cluster.outbound|443||kubernetes-dashboard.kube-system.svc.cluster.local.membership_healthy:1|g"
[ AGENT ] 2019-02-03 02:55:13 UTC | ERROR | (server.go:252 in worker) | Dogstatsd: error parsing metrics: invalid field number for "envoy.cluster.outbound|443||kubernetes-dashboard.kube-system.svc.cluster.local.max_host_weight:1|g"
[ AGENT ] 2019-02-03 02:55:13 UTC | ERROR | (server.go:252 in worker) | Dogstatsd: error parsing metrics: invalid field number for "envoy.cluster.outbound|443||kubernetes-dashboard.kube-system.svc.cluster.local.version:800903190138838288|g"
[ AGENT ] 2019-02-03 02:55:13 UTC | ERROR | (server.go:252 in worker) | Dogstatsd: error parsing metrics: invalid field number for "envoy.cluster.outbound|15031||istio-ingressgateway.istio-system.svc.cluster.local.version:800903190138838288|g"
[ AGENT ] 2019-02-03 02:55:13 UTC | ERROR | (server.go:252 in worker) | Dogstatsd: error parsing metrics: invalid field number for "envoy.cluster.outbound|15031||istio-ingressgateway.istio-system.svc.cluster.local.membership_healthy:1|g"
```

**Describe what you expected:**
Umm... not that.

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**
GKE
