### ISSUE TITLE
[BUG] postfix.queue.size metric is lost after updating to 7.57.x

### ISSUE THREAD

**Issue by int128** [DataDog/datadog-agent#29826]
**Agent Environment**
datadog-agent 7.57.2

**Describe what happened:**
When we updated the datadog-agent to 7.57.2, the metric of `postfix.queue.size` is lost. We reverted the version to 7.55.2 or 7.56.2, the metric is appeared again.

**Describe what you expected:**
`postfix.queue.size` metric is sent to Datadog after updating datadog-agent.

**Steps to reproduce the issue:**
Deploy the postfix container to Kubernetes cluster.

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  # ...snip...
spec:
  template:
    metadata:
      annotations:
        ad.datadoghq.com/postfix.checks: |
          {
            "postfix": {
              "init_config": {
                "postqueue": true
              },
              "instances": [
                {
                  "config_directory": "/etc/postfix",
                  "queues": [
                    "incoming",
                    "active",
                    "deferred"
                  ]
                }
              ]
            }
          }
    spec:
      containers:
        - image: smtp-relay-postfix
          imagePullPolicy: Always
          name: postfix
          # ...snip...
          volumeMounts:
            - name: queue
              mountPath: /var/spool/postfix
  volumeClaimTemplates:
    - metadata:
        name: queue
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: gp2
        resources:
          requests:
            storage: 50Gi
```

Here is the list of versions and this problem.

- ❌ public.ecr.aws/datadog/agent:7.57.2 (Datadog Helm Chart 3.73.1)
- ✅ public.ecr.aws/datadog/agent:7.56.2 (Datadog Helm Chart 3.71.1)
- ✅ public.ecr.aws/datadog/agent:7.55.2 (Datadog Helm Chart 3.69.1)

**Additional environment details (Operating System, Cloud provider, etc):**
- Amazon EKS 1.30
- Datadog Helm Chart https://github.com/DataDog/helm-charts/tree/main/charts/datadog
- Postfix 3.4.14 (Debian)
