### ISSUE TITLE
[BUG] NDM Autodisovery in `datadog.yaml` breaks when using `ignored_ip_addresses`

### ISSUE THREAD

**Issue by a-rhodes** [DataDog/datadog-agent#30181]
**Agent Environment**
Tested Versions: 7.57.2 & 7.57.0

Bug was introduced in `7.54.0` when `network_devices.autodiscovery` was added to `datadog.yaml`

**Describe what happened:**
When using the `ignored_ip_addresses` feature of `network_devices.autodiscovery.configs`, the SNMP Listener will fail to start and no network devices will be monitored.

**Describe what you expected:**
Expect `ignored_ip_addresses` to work as documented.

**Steps to reproduce the issue:**
Add a `network_devices` config to `datadog.yaml`:
```
network_devices:
  autodiscovery:
    loader: core
    configs:
      - network_address: 192.168.0.1/30
        snmp_version: 2
        port: 161
        community_string: public
        ignored_ip_addresses:
          - 192.168.0.2
```

No log for `Configs for autodiscovery detected: Adding the snmp listener` or `snmp listener successfully started` in `agent.log`

**Additional environment details (Operating System, Cloud provider, etc):**
Here is a PR with a unit test showing the failure: https://github.com/DataDog/datadog-agent/pull/30177
Here is a PR with a fix and a new unit test: https://github.com/DataDog/datadog-agent/pull/30180

The issue comes down to the YAML Unmarshal. It is documented that the config item `ignored_ip_addresses` should be a list of IPs as strings, but the struct for the config expects a `map[string]bool`. In the primary autodiscovery code, it calls `snmp.NewListenerConfig()`
https://github.com/DataDog/datadog-agent/blob/main/comp/core/autodiscovery/listeners/snmp.go#L71
Which has a special hook for converting lists to maps:
https://github.com/DataDog/datadog-agent/blob/main/pkg/snmp/snmp.go#L101-L117

But, when the agent starts and tries to add the listener, it attempts to load the config without this hook, and as such the configuration fails to load and the listener is not added. The error is also not logged, so the user has no idea why it's failing:
https://github.com/DataDog/datadog-agent/blob/122c53feeacc292ea17a26173d797913919b9c90/pkg/config/autodiscovery/autodiscovery.go#L77-L84
