### ISSUE TITLE
[BUG] - clusterchecks securityContext defined in Values not being applied

### ISSUE THREAD

**Issue by carlos-leocadio-jnpr** [DataDog/datadog-agent#30676]
**Agent Environment**
Chart 3.77.0
Agent 7.58.0 

**Describe what happened:**
User-specific securityContext defined in Values for `clusterchecks` is **not being applied** in the pod's configuration.
I have defined`clusterchecks` in Values as shown below, which includes `clusterChecksRunner.securityContext`.

```yaml
      ## Cluster Checks Runner Section
      clusterChecksRunner:
        enabled: true
        revisionHistoryLimit: 1
        image:
          name: public.ecr.aws/datadog/agent
          tag: 7.58.0
        securityContext:
          runAsUser: 100
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        createPodDisruptionBudget: true
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 300m
            memory: 512Mi
```

```bash
user@lab:~$ k get pod/datadog-agent-clusterchecks-5ccdd74457-s4qnc -n datadog -o jsonpath='{.spec.securityContext}' | jq .
{
  "runAsUser": 100,
  "seccompProfile": {
    "type": "RuntimeDefault"
  }
}
```

The `clusterChecksRunner.resources` section from Values is being successfully applied [here](https://github.com/DataDog/helm-charts/blob/6b2cbbcd144297048120f1fb295feb794cdf89c1/charts/datadog/templates/agent-clusterchecks-deployment.yaml#L178).

```bash
user@lab:~$ k get pod/datadog-agent-clusterchecks-5ccdd74457-s4qnc -n datadog -o jsonpath='{.spec.containers[*].resources}' | jq .
{
  "limits": {
    "cpu": "300m",
    "memory": "512Mi"
  },
  "requests": {
    "cpu": "200m",
    "memory": "256Mi"
  }
}
```

**Describe what you expected:**

The `clusterChecksRunner.securityContext` parameter, like the `clusterChecksRunner.resources` parameter, is expected to be consumed by helm and applied to the `agent-clusterchecks-deployment` [here](https://github.com/DataDog/helm-charts/blob/6b2cbbcd144297048120f1fb295feb794cdf89c1/charts/datadog/templates/agent-clusterchecks-deployment.yaml#L72), but that is not happening.
