### ISSUE TITLE
Adding support for environment variables in config files

### ISSUE THREAD

**Issue by levraipixel** [DataDog/datadog-agent#3082]
Hi,

I've prepared a tiny feature to add support for environment variables in config files: https://github.com/DataDog/datadog-agent/compare/master...yhourdel:master
Should I prepare a proper PR for this? Or is it something only useful for me and I shouldn't bother?
I just don't want to take time to learn Reno, write tests, etc unless needed.
Thanks

**Comment by xvello** [comment]
Hi @yhourdel 

Agent 6.1 introduced the new %%env_XXXXX%% [template variable](https://docs.datadoghq.com/agent/autodiscovery/?tab=docker#supported-template-variables) that does what you are looking for. Could you please give it a try?

**Comment by yhourdel** [comment]
Thanks @xvello, I'll check it out.

**Comment by rpuserh** [comment]
This is not working @levraipixel  @xvello .  
I exported environment variable SNOW_PASSWORD
and tried using it in my config file
```
init_config:
instances:
  - account: myACCOUNT
    username: myDATADOG_SERVICE_USER
    password: %%env_SNOW_PASSWORD%%
    role: ROLE
    min_collection_interval: 36
```

received error
```
2021-10-08 01:11:52 UTC | CORE | WARN | (pkg/autodiscovery/providers/file.go:198 in collectEntry) | /etc/datadog-agent/conf.d/snowflake.d/conf.yaml is not a valid config file: yaml: line 5: found character that cannot start any token
```

My datadog agent is running on k8s

Question is how to use interpolation syntax in config files ? 

Please advice

**Comment by olivielpeau** [comment]
@rpuserh For the resulting yaml to be valid, please make sure to put `%%env_SNOW_PASSWORD%%` in quotes, i.e. :

```yaml
init_config:
instances:
  - account: myACCOUNT
    username: myDATADOG_SERVICE_USER
    password: "%%env_SNOW_PASSWORD%%"
    role: ROLE
    min_collection_interval: 36
```

Since the feature requested in this issue is implemented in the Agent ([docs](https://docs.datadoghq.com/agent/faq/template_variables/)), I'll go ahead and close this issue.
