### ISSUE TITLE
datadog-agent seems to be slowing down Python code in Docker. 

### ISSUE THREAD

**Issue by farzaa** [DataDog/datadog-agent#3087]
I have the follow `docker-compose` and `environment` file below. I have another docker container named `worker` that simply reads in a video file frame-by-frame and logs the current time every 0.20 seconds using the native Python `logger` library. 

I am getting an issue where the `worker` container seems to start lagging behind a lot, sometimes up to 30-45 seconds. I'll check But, when I turn the datadog-agent off, it stays right on time. 

This issue is also fixed when I do `docker-compose -f docker-compose.yml up -d --remove-orphans` and restart the agent, though I am unsure why. My thought was it's trying to send the logs of dead containers, and slowing down running containers in the process. How does datadog-agent work with orphaned and unused containers? Does it still read their logs or only actually send the logs of running containers? 

Note: I have not configured my agent as done [here](https://docs.datadoghq.com/logs/log_collection/python/?tab=json_logformatter). My Python logger just logs to stdout/stderr, which I assume datadog-agent picks up from the container (pls correct me if I'm wrong here).

Any help us to figuring out why the agent is causing `worker` logs to lag behind would be great!

```
  ddagent:
    image: datadog/agent:latest
    container_name: datadog-agent
    env_file:
      - datadog.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
```

```
DD_API_KEY=api_key_here
DD_LOGS_ENABLED=true
DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
DD_AC_EXCLUDE="name:datadog-agent"
```
