### ISSUE TITLE
Unquoted numerical values cannot be templated in k8s annotations

### ISSUE THREAD

**Issue by schancel** [DataDog/datadog-agent#3165]
Datadog agent running as a daemonset on GKE is outputing the following error:
```
[ AGENT ] 2019-03-18 23:31:25 UTC | ERROR | (kubelet.go:97 in parseKubeletPodlist) | Can't parse template for pod xxxxxxx: in instances: Failed to unmarshal JSON: invalid character '%' looking for beginning of value
```
Looking at the associated pod, the annotations are as such:

```
      annotations:
        ad.datadoghq.com/redis.check_names: '["redisdb"]'
        ad.datadoghq.com/redis.init_configs: '[{}]'
        ad.datadoghq.com/redis.instances: '[{"host": "%%host%%", "port": %%port%%}]'
```

It appears that the templating is not happening prior to unmarshalling -- requiring all parameters to be strings?

https://github.com/DataDog/datadog-agent/blob/bc07505b48f4eb2505209499715c623628950423/pkg/autodiscovery/providers/utils.go#L91
