### ISSUE TITLE
[BUG] otel-agent binary not present in Docker image

### ISSUE THREAD

**Issue by pilab-gwon** [DataDog/datadog-agent#32715]
**Agent Environment**

- **Agent Version**: `stable` release (`7.55`, `7.56`, `7.57`, `7.58`, `7.59`, `7.60`, `7-beta`)
- **Deployment Environment**: Kubernetes (EKS v1.29)
- **Configuration Management**: Helm Chart 

**Describe what happened:**

```yaml
    otelCollector:
        config: |-
            receivers:
                otlp:
                    protocols:
                        grpc:
                            endpoint: 0.0.0.0:4317
                        http:
                            endpoint: 0.0.0.0:4318
            exporters:
                debug:
                    verbosity: info
                datadog:
                    hostname: "otelcol-docker"
                    traces:
                        span_name_as_resource_name: true
                        trace_buffer: 500
                    api:
                        key: <REDACTED>
            processors:
                batch:
                batch/datadog:
                    send_batch_max_size: 100
                    send_batch_size: 10
                    timeout: 10s
                probabilistic_sampler/traces:
                    sampling_percentage: 10
                probabilistic_sampler/logs:
                    sampling_percentage: 10
                resourcedetection:
                    detectors: [env, eks]
                    timeout: 15s
                    override: true
            connectors:
                datadog/connector:
                    traces:
                        span_name_as_resource_name: true
                        compute_stats_by_span_kind: true
                        peer_tags_aggregation: true
            service:
                pipelines:
                    logs:
                        receivers: [ otlp ]
                        processors: [ batch ]
                        exporters: [ debug ]
                    logs/datadog:
                        receivers: [ otlp ]
                        processors: [ batch/datadog ]
                        exporters: [ datadog ]
                    traces/sampling:
                        receivers: [ otlp ]
                        processors: [ probabilistic_sampler/traces, batch/datadog ]
                        exporters: [ datadog ]
                    traces/datadog:
                        receivers: [ otlp ]
                        processors: [ resourcedetection, batch/datadog ]
                        exporters: [ datadog/connector ]
                    metrics:
                        receivers: [ otlp, datadog/connector ]
                        processors: [ resourcedetection, batch/datadog ]
                        exporters: [ datadog ]
        enabled: true
    otlp:
        logs:
            enabled: false
        receiver:
            protocols:
                grpc:
                    enabled: false
                    endpoint: 0.0.0.0:4317
                    useHostPort: true
                http:
                    enabled: false
                    endpoint: 0.0.0.0:4318
                    useHostPort: true
```

I was hoping to use the OtelCollector, so I added the following configuration. However, I noticed that the stable and beta releases do not include the OpenTelemetry binary.

While looking for related issues, I came across [#28523](https://github.com/DataDog/datadog-agent/issues/28523), and as a workaround, I applied the following configuration:

```yaml
agents:
  image:
    repository: datadog/agent-dev
    tag: nightly-ot-beta-main
    doNotCheckTag: true
```

Up until a few days ago, the deployment was working well with this setup.

However, after recently updating the datadog-agent, I noticed that nightly-ot-beta-main had also been updated. When I tried rolling back to a previous version that had been working correctly, I found that its SHA256 digest was no longer available.

I believe there might be two possible solutions to this issue:

1. Would it be possible to provide the SHA256 digest of a version where the OtelCollector functions correctly?
2. Could the otel-agent binary be included in the stable release?

Additionally, I would really appreciate any insights into when this issue might be addressed.

Thank you for your time and support!
