### ISSUE TITLE
[BUG] OTLP Ingestion by the Datadog Agent doesn't start since v7.61.0

### ISSUE THREAD

**Issue by keisku** [DataDog/datadog-agent#32947]
**Agent Environment**

```bash
uname -a
Linux ip-10-0-133-150 6.8.0-1021-aws #23~22.04.1-Ubuntu SMP Tue Dec 10 16:50:46 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

docker --version
Docker version 27.4.1, build b9d17ea

docker exec datadog-agent agent version
Agent 7.61.0 - Commit: 202f54bcf5 - Serialization version: v5.0.137 - Go version: go1.22.8
```

**Describe what happened:**

[OTLP Ingestion by the Datadog Agent](https://docs.datadoghq.com/opentelemetry/interoperability/otlp_ingest_in_the_agent/?tab=host) doesn't start.

**Describe what you expected:**

agent should listen on `*:4318` and `*:4317` like

```bash
docker exec -it datadog-agent ss -tlpn
State                                                 Recv-Q                                                Send-Q                                                                                               Local Address:Port                                                                                                Peer Address:Port                                               Process                                                                                 
LISTEN                                                0                                                     4096                                                                                                     127.0.0.1:6162                                                                                                     0.0.0.0:*                                                   users:(("process-agent",pid=400,fd=18))                                                
LISTEN                                                0                                                     4096                                                                                                     127.0.0.1:6062                                                                                                     0.0.0.0:*                                                   users:(("process-agent",pid=400,fd=12))                                                
LISTEN                                                0                                                     4096                                                                                                     127.0.0.1:5012                                                                                                     0.0.0.0:*                                                   users:(("trace-agent",pid=397,fd=15))                                                  
LISTEN                                                0                                                     4096                                                                                                     127.0.0.1:5001                                                                                                     0.0.0.0:*                                                   users:(("agent",pid=402,fd=23))                                                        
LISTEN                                                0                                                     4096                                                                                                     127.0.0.1:5000                                                                                                     0.0.0.0:*                                                   users:(("agent",pid=402,fd=26))                                                        
LISTEN                                                0                                                     4096                                                                                                    127.0.0.11:43519                                                                                                    0.0.0.0:*                                                                                                                                          
LISTEN                                                0                                                     4096                                                                                                             *:8126                                                                                                           *:*                                                   users:(("trace-agent",pid=397,fd=11))                                                  
LISTEN                                                0                                                     4096                                                                                                             *:4318                                                                                                           *:*                                                   users:(("agent",pid=402,fd=22))                                                        
LISTEN                                                0                                                     4096                                                                                                             *:4317                                                                                                           *:*                                                   users:(("agent",pid=402,fd=21))                                                        
LISTEN                                                0                                                     4096                                                                                                             *:5003                                                                                                           *:*                                                   users:(("trace-agent",pid=397,fd=13))                                                  
```

**Steps to reproduce the issue:**

```yaml
services:
  agent:
    container_name: datadog-agent
    image: datadog/agent:7.61.0
    volumes:
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /proc/:/host/proc/:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT=0.0.0.0:4317
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT=0.0.0.0:4318
    env_file:
      - ~/sandbox.docker.env # DD_API_KEY is here.
```

```bash
docker compose up -d

docker logs datadog-agent | grep '\: process does not exist'
2025-01-14 09:44:20 UTC | CORE | ERROR | (comp/otelcol/collector/impl-pipeline/pipeline.go:111 in func1) | Error running the OTLP ingest pipeline: failed to register process metrics: process does not exist

# agent doesn't listen on `*:4318` and `*:4317` like
docker exec -it datadog-agent ss -tlpn
State                                                 Recv-Q                                                Send-Q                                                                                               Local Address:Port                                                                                                Peer Address:Port                                               Process                                                                                 
LISTEN                                                0                                                     4096                                                                                                    127.0.0.11:35859                                                                                                    0.0.0.0:*                                                                                                                                          
LISTEN                                                0                                                     4096                                                                                                     127.0.0.1:6162                                                                                                     0.0.0.0:*                                                   users:(("process-agent",pid=401,fd=18))                                                
LISTEN                                                0                                                     4096                                                                                                     127.0.0.1:5012                                                                                                     0.0.0.0:*                                                   users:(("trace-agent",pid=397,fd=15))                                                  
LISTEN                                                0                                                     4096                                                                                                     127.0.0.1:5001                                                                                                     0.0.0.0:*                                                   users:(("agent",pid=402,fd=20))                                                        
LISTEN                                                0                                                     4096                                                                                                     127.0.0.1:5000                                                                                                     0.0.0.0:*                                                   users:(("agent",pid=402,fd=24))                                                        
LISTEN                                                0                                                     4096                                                                                                     127.0.0.1:6062                                                                                                     0.0.0.0:*                                                   users:(("process-agent",pid=401,fd=11))                                                
LISTEN                                                0                                                     4096                                                                                                             *:8126                                                                                                           *:*                                                   users:(("trace-agent",pid=397,fd=11))                                                  
LISTEN                                                0                                                     4096                                                                                                             *:5003                                                                                                           *:*                                                   users:(("trace-agent",pid=397,fd=13))                                                  

```

**Additional environment details (Operating System, Cloud provider, etc):**

Found three workarounds.

### 1. Use 7.60.1

Using this version could be a workaround.

### 2. Set `HOST_PROC=/proc`

```yaml
services:
  agent:
    container_name: datadog-agent
    image: datadog/agent:7.61.0
    volumes:
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /proc/:/host/proc/:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - HOST_PROC=/proc # WORKAROUND
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT=0.0.0.0:4317
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT=0.0.0.0:4318
    env_file:
      - ~/sandbox.docker.env # DD_API_KEY is here.
```

### 3. Remove `/proc/:/host/proc/:ro` from `volumes`

This goes against the documentation.
https://docs.datadoghq.com/containers/docker/?tab=standard#setup

```yaml
services:
  agent:
    container_name: datadog-agent
    image: datadog/agent:7.61.0
    volumes:
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      # - /proc/:/host/proc/:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/cloud/data/instance-id:/var/lib/cloud/data/instance-id:ro
    environment:
      # - HOST_PROC=/proc
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT=0.0.0.0:4317
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT=0.0.0.0:4318
    env_file:
      - ~/sandbox.docker.env # DD_API_KEY is here.

```

### Related Information/Code

- https://github.com/open-telemetry/opentelemetry-collector/issues/7435
- Error comes from https://github.com/open-telemetry/opentelemetry-collector/blob/v0.116.0/service/internal/proctelemetry/process_telemetry.go#L72-L75
  - https://github.com/open-telemetry/opentelemetry-collector/blob/v0.116.0/service/go.mod#L10
  - https://github.com/shirou/gopsutil/blob/v4.24.11/process/process.go#L220-L226
  - https://github.com/shirou/gopsutil/blob/v4.24.11/process/process_posix.go#L103

**Comment by keisku** [comment]
@songy23 thank you for triaging this issue!

[Update OTel Collector dependencies to v0.117.0](https://github.com/DataDog/datadog-agent/pull/32863) doesn't solve it...

```yaml
services:
  agent:
    container_name: datadog-agent
    # Built this image by https://gitlab.ddbuild.io/DataDog/datadog-agent/-/jobs/765983422
    image: datadog/agent-dev:update-otel-collector-dependencies-0-117-0-py3
    volumes:
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /proc/:/host/proc/:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT=0.0.0.0:4317
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT=0.0.0.0:4318
    env_file:
      - ~/sandbox.docker.env # DD_API_KEY is here.
```

```bash
docker logs datadog-agent | grep '\: process does not exist'
2025-01-14 23:42:26 UTC | CORE | ERROR | (comp/otelcol/collector/impl-pipeline/pipeline.go:112 in func1) | Error running the OTLP ingest pipeline: failed to register process metrics: process does not exist
```

Looks agent fails to find own PID (= 404 in this case) from `/host/proc`.
PID 404 is only available in [pid namespaces](https://man7.org/linux/man-pages/man7/pid_namespaces.7.html) of agent container. This means PID 404 does not exist in procfs of the host.

```bash
docker exec -it datadog-agent stat /proc
  File: /proc
  Size: 0         	Blocks: 0          IO Block: 1024   directory
Device: 0,73	Inode: 1           Links: 275
Access: (0555/dr-xr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2025-01-14 23:42:24.526827488 +0000
Modify: 2025-01-14 23:42:24.526827488 +0000
Change: 2025-01-14 23:42:24.526827488 +0000
 Birth: -

docker exec -it datadog-agent stat /host/proc
  File: /host/proc
  Size: 0         	Blocks: 0          IO Block: 1024   directory
Device: 0,22	Inode: 1           Links: 275
Access: (0555/dr-xr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2025-01-14 11:49:58.227000034 +0000
Modify: 2025-01-14 11:49:58.227000034 +0000
Change: 2025-01-14 11:49:58.227000034 +0000
 Birth: -

docker exec -it datadog-agent ps -ef | grep 'agent run'
root         404     398  1 23:42 ?        00:00:04 agent run

docker exec -it datadog-agent find /proc -name '404'
/proc/404
/proc/404/task/404
```
