### ISSUE TITLE
[BUG]  APM Inject fails when explicitely mentioned istio container

### ISSUE THREAD

**Issue by Dasio** [DataDog/datadog-agent#33296]
**Agent Environment**

Agent 7.61.0 - Commit: 202f54bcf5 - Serialization version: v5.0.137 - Go version: go1.22.8

**Describe what happened:**
Deployed app with admission.datadoghq.com/enabled
Pod couldn't be created because of error in container `datadog-init-apm-inject`
```
/bin/sh: can't create /datadog-etc/ld.so.preload: Is a directory
```

**Describe what you expected:**
Create pod without issue

**Steps to reproduce the issue:**
It seems it's related to another init container, in our case istio. If I don't specify container explicitly everything works as expected, but if I want to modify something then init-apm-inject fails.

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: istio-proxy
    image: auto
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
```

**Additional environment details (Operating System, Cloud provider, etc):**
K8s Rev: v1.30.8-gke.1051000   
Istio: 1.22.1

**Comment by stanistan** [comment]
👋 @Dasio Can you also share the pod-spec that errors after the init containers are added?

**Comment by Dasio** [comment]
I meant adding istio-proxy with image tag "auto"

I have already shared pod-spec or what exactly you meant? spec
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    admission.datadoghq.com/enabled: "true"
spec:
  containers:
  - name: istio-proxy
    image: auto
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
```
This doesn't work, because container `datadog-init-apm-inject` fails.

This works (not mentioning istio-proxy)

```yaml
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
```
And so far I don't have idea why. We specify `istio-proxy` container to include some preStop lifecycle.
But this is minimal reproducible step I was able to reproduce.

Full pod spec after kubectl apply and failed init container https://gist.github.com/Dasio/b0f8a5caafd8748f172bd6f4a0a55b40
