### ISSUE TITLE
Datadog does not process logs before ingestion when using the K8s File source

### ISSUE THREAD

**Issue by tokyowizard** [DataDog/datadog-agent#3510]
**Output of the info page (if this is a bug)**
```
up (pid 340) 803 seconds
```

**Describe what happened:**
When we mount `dockersocket` with the mount path of `/var/run/docker.sock` as described in the [docs for kubernetes](https://docs.datadoghq.com/agent/kubernetes/daemonset_setup/?tab=k8sfile#log-collection), the format of the logs ingested comes in properly. We don't need to do anything extra.

But when we mount `logpath` with the mount path of `/var/log/pods`, the format of the logs have only `log`, `stream`  and `time` attributes. For example:

```
{
  "log": "{\"addr\":\"10.1.2.3:46726\",\"duration\":0,\"headers\":{\"Content-Length\":[\"345\"],\"Content-Type\":[\"text/html\"],\"Date\":[\"Mon, 20 May 2019 01:23:41 GMT\"],\"Server\":[\"EC2ws\"]},\"level\":\"info\",\"method\":\"GET\",\"msg\":\"processed request\",\"path\":\"/latest/meta-data/spot/termination-time\",\"status\":404,\"time\":\"2019-05-20T01:24:40Z\"}\n",
  "stream": "stderr",
  "time": "2019-05-20T01:24:40.139126726Z"
}
```
We would need to add parsing for every format that comes in for the values in the `log` attribute.

**Describe what you expected:**
When setting K8File with the `/var/log/pods` mount, we should not need to do anything extra as when setting Docker Socket with the `/var/run/docker.sock` mount.

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: datadog-agent
    app.kubernetes.io/component: agent
    app.kubernetes.io/managed-by: infra-kubernetes
    app.kubernetes.io/name: datadog-agent
    app.kubernetes.io/part-of: datadog
    release: datadog
  name: datadog-agent
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: agent
      app.kubernetes.io/managed-by: infra-kubernetes
      app.kubernetes.io/name: datadog-agent
      app.kubernetes.io/part-of: datadog
  template:
    metadata:
      annotations:
        checksum/autoconf-config: 38e0b9de817f645c4bec37c0d4a3e58baecccb040f5718dc069a72c7385a0bed
        checksum/checksd-config: 38e0b9de817f645c4bec37c0d4a3e58baecccb040f5718dc069a72c7385a0bed
        checksum/confd-config: ecdd083f59655a4c77002bc645fce5c6dc04a261b913492083db157a651141d8
      labels:
        app: datadog-agent
        app.kubernetes.io/component: agent
        app.kubernetes.io/managed-by: infra-kubernetes
        app.kubernetes.io/name: datadog-agent
        app.kubernetes.io/part-of: datadog
      name: datadog-agent
    spec:
      containers:
      - env:
        - name: DD_AC_EXCLUDE
          value: name:datadog-agent
        - name: DD_AD_CONFIG_POLL_INTERVAL
          value: "5"
        - name: DD_API_KEY
          valueFrom:
            secretKeyRef:
              key: api-key
              name: datadog-agent
        - name: DD_LOG_LEVEL
          value: INFO
        - name: DD_CLUSTER_AGENT_ENABLED
          value: "true"
        - name: DD_CLUSTER_AGENT_KUBERNETES_SERVICE_NAME
          value: datadog-agent-cluster-agent
        - name: DD_CLUSTER_AGENT_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: datadog-agent-cluster-agent
        - name: KUBERNETES
          value: "yes"
        - name: DD_KUBERNETES_POD_LABELS_AS_TAGS
          value: '{"app.kubernetes.io/component":"kube_app_component","app.kubernetes.io/instance":"kube_app_instance","app.kubernetes.io/name":"kube_app_name"}'
        - name: DD_KUBERNETES_POD_ANNOTATIONS_AS_TAGS
          value: '{"iam.amazonaws.com/role":"kube_iamrole"}'
        - name: DD_KUBERNETES_KUBELET_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_LOGS_ENABLED
          value: "true"
        - name: DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL
          value: "true"
        - name: DD_EXTRA_CONFIG_PROVIDERS
          value: clusterchecks
        image: datadog/agent:6.11.1
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - ./probe.sh
          initialDelaySeconds: 15
          periodSeconds: 5
        name: datadog
        ports:
        - containerPort: 8125
          name: dogstatsdport
          protocol: UDP
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /var/log/pods
          name: logpath
        - mountPath: /var/lib/docker/containers
          name: containerspath
        - mountPath: /var/run/docker.sock
          name: runtimesocket
          readOnly: true
        - mountPath: /host/proc
          name: procdir
          readOnly: true
        - mountPath: /host/sys/fs/cgroup
          name: cgroups
          readOnly: true
        - mountPath: /var/run/s6
          name: s6-run
        - mountPath: /conf.d
          name: confd
          readOnly: true
        - mountPath: /opt/datadog-agent/run
          name: pointerdir
      serviceAccountName: datadog-agent
      volumes:
      - hostPath:
          path: /var/log/pods
        name: logpath
      - hostPath:
          path: /var/lib/docker/containers
        name: containerspath
      - hostPath:
          path: /var/run/docker.sock
        name: runtimesocket
      - hostPath:
          path: /proc
        name: procdir
      - hostPath:
          path: /sys/fs/cgroup
        name: cgroups
      - emptyDir: {}
        name: s6-run
      - configMap:
          name: datadog-agent-confd
        name: confd
      - hostPath:
          path: /opt/datadog-agent/run
        name: pointerdir
  updateStrategy:
    type: RollingUpdate
```

Edit: Make the link more specific to the "Log Collection" section in the Datadog Kubernetes doc.
