### ISSUE TITLE
[BUG] sysprobe container fails to start

### ISSUE THREAD

**Issue by djtecha** [DataDog/datadog-agent#36021]
**Agent Environment**

```
Agent 7.64.1 - Commit: 154bd424d2 - Serialization version: v5.0.144 - Go version: go1.23.6
Kernel: 6.8.0-57-generic
Host OS: "Ubuntu 24.04.2 LTS"
k3s version v1.32.3+k3s1
```
 Running on a K3S cluster.

**Describe what happened:**

Container gets stuck in a crash loop. No longs but K8S events give the following:

```
Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: unable to setup user: resource temporarily unavailable```
```

**Describe what you expected:**

The container should start

**Steps to reproduce the issue:**

Enable Universal service monitoring
 

**Additional environment details (Operating System, Cloud provider, etc):**

Helm Chart:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: datadog
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: datadog
      sourceRef:
        kind: HelmRepository
        name: datadog
        namespace: cluster-config
      version: "3.110.10"
  values:
    datadog:
      clusterName: test
      logLevel: INFO
      apiKeyExistingSecret: "datadog-secret"
      site: "us3.datadoghq.com"
      tags:
        - "env:prod"
      serviceMonitoring:
        enabled: true
      clusterChecks:
        enabled: true
      logs:
        enabled: true
        containerCollectAll: true
      processAgent:
        enabled: false
      apm:
        instrumentation:
          enabled: false
          targets:
            - name: "default-target"
              namespaceSelector:
                matchNames:
                  - "media"
              ddTraceVersions:
                python: "3"
      networkMonitoring:
        enabled: false
      helmCheck:
        enabled: false
        collectEvents: true
      prometheusScrape:
        enabled: false
        serviceEndpoints: true
      envFrom:
         - secretRef:
             name: datadog-secret
      confd:
        istio.yaml: |-
          init_config:
          instances:
            - use_openmetrics: true
              send_histograms_buckets: false
              istiod_endpoint: http://istiod.istio-system.svc.cluster.local:15014/metrics
              tag_by_endpoint: false
    agents:
      podAnnotations:
        sidecar.istio.io/inject: "false"
      volumeMounts:
        - name: systemd
          mountPath: /host/run/systemd/
      volumes:
        - name: systemd
          hostPath:
            path: /run/systemd/
    clusterAgent:
      enabled: true
      podAnnotations:
        sidecar.istio.io/inject: "false"

```

**Comment by guyarb** [comment]
Hey @djtecha, please share instructions to reproduce your setup

**Comment by scottgerring** [comment]
I have this issue too, also on k3s. Here's the datadog-agent.yaml; agent is 7.63.1. 

```yaml
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    clusterName: home.gerring.ch
    site: datadoghq.eu
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
  features:
    sbom:
      enabled: true
      containerImage:
        enabled: true
      host:
        enabled: true
    logCollection:
      enabled: true
      containerCollectAll: true
    liveProcessCollection:
      enabled: true
    liveContainerCollection:
      enabled: true
    processDiscovery:
      enabled: true
    oomKill:
      enabled: true
    tcpQueueLength:
      enabled: true
    ebpfCheck:
      enabled: true
    apm:
      enabled: true
      instrumentation:
        enabled: true
        targets:
          - name: "default-target"
            ddTraceVersions:
              java: "1"
              dotnet: "3"
              python: "2"
              js: "5"
              php: "1"
    cspm:
      enabled: true
    cws:
      enabled: true
    npm:
      enabled: true
      enabled: true
      instrumentation:
        enabled: true
        targets:
          - name: "default-target"
            ddTraceVersions:
              java: "1"
              dotnet: "3"
              python: "2"
              js: "5"
              php: "1"
    cspm:
      enabled: true
    cws:
      enabled: true
    npm:
      enabled: true
```

**Comment by djtecha** [comment]
This is on a 3 node k3s setup running ubuntu on each node. Both x86 and arm64 nodes have this issue.

**Comment by djtecha** [comment]
@scottgerring where are you placing those helm values? I don't see that section in the helm chart: https://github.com/DataDog/helm-charts/blob/main/charts/datadog/values.yaml I tried adding it to the agent.containers.systemprobe section but it still fails.

```
    agents:
      containers:
        systemprobe:    
          securityContext:
            privileged: true
```

**Comment by djtecha** [comment]
I'm curious if this is an apparmor bug. Looking at the helm chart I see `runtime/default` used but have no idea where that profile name comes from. Its not in my hosts apparmor.d directory.

**Comment by scottgerring** [comment]
> [@scottgerring](https://github.com/scottgerring) where are you placing those helm values? I don't see that section in the helm chart: https://github.com/DataDog/helm-charts/blob/main/charts/datadog/values.yaml I tried adding it to the agent.containers.systemprobe section but it still fails.
> 
> ```
>     agents:
>       containers:
>         systemProbe:    
>           securityContext:
>             privileged: true
> ```

Hey @djtecha this is using the operator deployment - [the CRD is documented over here](https://github.com/DataDog/datadog-operator/blob/main/docs/configuration.v2alpha1.md) .

Did you manage to work it out with the helm deployment?

**Comment by djtecha** [comment]
No, still couldn't get it running via HELM. Same issue despite dropping that in the container section.

**Comment by djtecha** [comment]
Well wait... not sure why but maybe just walking away for a minute helped this. This appears to now be working.

```
    agents:
      containers:
        systemProbe:
          securityContext:
            privileged: true
```
