### ISSUE TITLE
[BUG] Aurora Autodiscovery extra_dbname doesn't fallback to default name for engine

### ISSUE THREAD

**Issue by wparr-circle** [DataDog/datadog-agent#36148]
**Agent Environment**

Chart 3.90.0, Agent 7.62.0

**Describe what happened:**
Using the new `%%extra_dbname%%` such as:
```yaml
        ad_identifiers:
          - _dbm_postgres_aurora
        cluster_check: true
        init_config:
        instances:
         - host: "%%host%%"
           port: "%%port%%"
           dbname: "%%extra_dbname%%"
           tags:
            - "dbclusteridentifier:%%extra_dbclusteridentifier%%"
            - "region:%%extra_region%%"
```

We find that the rendered database configuration where the default dbname is used in AWS, such as "postgres" in the case of PostgresSQL results that this results in an invalid configuration such as:

```
        instances:
         - host: "acmedb.com"
           port: "5432"
           dbname: ""
           tags:
            - "dbclusteridentifier:acmedb"
            - "region:us-east-1"
```

**Describe what you expected:**
That this renders to the default database name for the given engine type.

```
        instances:
         - host: "acmedb.com"
           port: "5432"
           dbname: "postgres"
           tags:
            - "dbclusteridentifier:acmedb"
            - "region:us-east-1"
```

**Steps to reproduce the issue:**
1. Provision an RDS cluster with the default db name
2. Attempt to configure an aurora autodiscovery based check with extra_dbname

**Additional environment details (Operating System, Cloud provider, etc):**
