### ISSUE TITLE
[BUG] Datadog on GKE Autopilot constantly reports ec2_prefer_imdsv2 warn messages

### ISSUE THREAD

**Issue by Ventilateur** [DataDog/datadog-agent#36316]
**Agent Environment**

- Agent version: 7.64.1
- Helm chart version: datadog-3.110.12
- K8s node version: v1.32.2-gke.1182001
- GKE Autopilot

Values file
```
agents:
  containers:
    agent:
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 200m
          memory: 256Mi

    traceAgent:
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
        limits:
          cpu: 100m
          memory: 200Mi

    processAgent:
      resources:
        requests:
          cpu: 100m
          memory: 200Mi
        limits:
          cpu: 100m
          memory: 200Mi

    systemProbe:
      resources:
        requests:
          cpu: 100m
          memory: 500Mi
        limits:
          cpu: 100m
          memory: 500Mi

  priorityClassCreate: true

clusterAgent:
  enabled: true
  metricsProvider:
    enabled: true
  rbac: 
    create: true
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 256Mi

providers:
  gke:
    autopilot: true


datadog:
  apiKeyExistingSecret: datadog-secret
  appKeyExistingSecret: datadog-secret
  site: datadoghq.eu

  ignoreAutoConfig:
    - cilium

  apm:
    socketEnabled: false
    portEnabled: true
    instrumentation:
      enabled: true
  
  logLevel: WARN
  
  logs:
    enabled: true
    containerCollectAll: true

  containerExclude: "kube_namespace:^kube-.* kube_namespace:^gke-.*"

  prometheusScrape:
    enabled: true

  # Not supported in Autopilot yet
  # https://docs.datadoghq.com/universal_service_monitoring/setup/?tab=helm#supported-versions-and-compatibility
  serviceMonitoring:
    enabled: false
```

**Describe what happened:**

I deployed Datadog agent using Helm chart on my GKE autopilot cluster. The agent pods are flooded with these warning logs:

```
WARN | (pkg/util/ec2/imds_helpers.go:103 in doHTTPRequest) | ec2_prefer_imdsv2 is set to true in the configuration but the agent was unable to proceed: status code 404 trying to PUT http://169.254.169.254/latest/api/token
```

**Describe what you expected:**

It looks like to me that `ec2_prefer_imdsv2` is an AWS specific config, I don't expect it to happen on GCP.

**Steps to reproduce the issue:**

- Create a GKE Autopilot cluster.
- Deploy DD agent with the values file above:

```
helm install <RELEASE_NAME> \
    --set datadog.appKey=<DATADOG_APP_KEY> \
    --set datadog.site=<DATADOG_SITE> \
    -f values.yaml
    datadog/datadog
```
