### ISSUE TITLE
[BUG] custom_resource doesn't work

### ISSUE THREAD

**Issue by AndMerlin** [DataDog/datadog-agent#37500]
**Agent Environment**

Agent version: 7.65.2

**Config ***
```
apiVersion: v1
data:
  kubernetes_apiserver.yaml: |-
    init_config:
    instances:
      -
        filtering_enabled: false
        unbundle_events: false
  kubernetes_state_core.yaml.default: |-
    init_config:
    instances:
      - collectors:
        - secrets
        - configmaps
        - customresourcedefinitions
        - nodes
        - pods
        - services
        - resourcequotas
        - replicationcontrollers
        - limitranges
        - persistentvolumeclaims
        - persistentvolumes
        - namespaces
        - endpoints
        - daemonsets
        - deployments
        - replicasets
        - statefulsets
        - cronjobs
        - jobs
        - horizontalpodautoscalers
        - poddisruptionbudgets
        - storageclasses
        - volumeattachments
        - ingresses
        labels_as_tags:
          {}
        annotations_as_tags:
          {}
        custom_resource:
          spec:
            resources:
              - commonLabels:
                  crd_type: eniconfig
                groupVersionKind:
                  group: crd.k8s.amazonaws.com
                  kind: ENIConfig
                  version: v1alpha1
                labelsFromPath:
                  crd_name:
                  - metadata
                  - name
                metrics:
                - each:
                    gauge:
                      path:
                      - metadata
                      - generation
                    type: gauge
                  help: ENI Config
                  name: eniconfig
              - groupVersionKind:
                  group: cilium.io
                  kind: CiliumEndpoint
                  version: v2
                metrics:
                - each:
                    info:
                      labelsFromPath:
                        name:
                        - metadata
                        - name
                    type: Info
                  help: The test
                  labelsFromPath:
                    id:
                    - status
                    - id
                  name: test_info
              - groupVersionKind:
                  group: kustomize.toolkit.fluxcd.io
                  kind: Kustomization
                  version: v1
                metricNamePrefix: gotk
                metrics:
                - each:
                    info:
                      labelsFromPath:
                        name:
                        - metadata
                        - name
                    type: Info
                  help: The current state of a Flux Kustomization resource.
                  labelsFromPath:
                    exported_namespace:
                    - metadata
                    - namespace
                    ready:
                    - status
                    - conditions
                    - '[type=Ready]'
                    - status
                    revision:
                    - status
                    - lastAppliedRevision
                    source_name:
                    - spec
                    - sourceRef
                    - name
                    suspended:
                    - spec
                    - suspend
                  name: resource_info
              - groupVersionKind:
                  group: helm.toolkit.fluxcd.io
                  kind: HelmRelease
                  version: v2
                metricNamePrefix: gotk
                metrics:
                - each:
                    info:
                      labelsFromPath:
                        name:
                        - metadata
                        - name
                    type: Info
                  help: The current state of a Flux HelmRelease resource.
                  labelsFromPath:
                    chart_app_version:
                    - status
                    - history
                    - "0"
                    - appVersion
                    chart_name:
                    - status
                    - history
                    - "0"
                    - chartName
                    chart_ref_name:
                    - spec
                    - chartRef
                    - name
                    chart_source_name:
                    - spec
                    - chart
                    - spec
                    - sourceRef
                    - name
                    exported_namespace:
                    - metadata
                    - namespace
                    ready:
                    - status
                    - conditions
                    - '[type=Ready]'
                    - status
                    revision:
                    - status
                    - history
                    - "0"
                    - chartVersion
                    suspended:
                    - spec
                    - suspend
                  name: resource_info
                - each:
                    info:
                      labelsFromPath:
                        app_version:
                        - status
                        - history
                        - "0"
                        - appVersion
                        chart_version:
                        - status
                        - history
                        - "0"
                        - chartVersion
                    type: Info
                  help: The version information of helm release resource.
                  labelsFromPath:
                    chart_name:
                    - spec
                    - chart
                    - spec
                    - chart
                    exported_namespace:
                    - metadata
                    - namespace
                    name:
                    - metadata
                    - name
                  name: helmrelease_version_info
              - groupVersionKind:
                  group: source.toolkit.fluxcd.io
                  kind: HelmChart
                  version: v1
                metricNamePrefix: gotk
                metrics:
                - each:
                    info:
                      labelsFromPath:
                        name:
                        - metadata
                        - name
                    type: Info
                  help: The current state of a Flux HelmChart resource.
                  labelsFromPath:
                    chart_name:
                    - spec
                    - chart
                    chart_version:
                    - spec
                    - version
                    exported_namespace:
                    - metadata
                    - namespace
                    ready:
                    - status
                    - conditions
                    - '[type=Ready]'
                    - status
                    revision:
                    - status
                    - artifact
                    - revision
                    suspended:
                    - spec
                    - suspend
                  name: resource_info
  orchestrator.yaml: "init_config:\ninstances: \n  - crd_collectors:\n      - helm.toolkit.fluxcd.io/v2/helmreleases\n
    \     - kustomize.toolkit.fluxcd.io/v1beta2/kustomizations\n      - kustomize.toolkit.fluxcd.io/v1/kustomizations"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: datadog
    meta.helm.sh/release-namespace: datadog
  creationTimestamp: "2023-12-06T18:35:01Z"
  labels:
    app.kubernetes.io/instance: datadog
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: datadog
    app.kubernetes.io/version: "7"
    helm.sh/chart: datadog-3.116.3
    helm.toolkit.fluxcd.io/name: datadog
    helm.toolkit.fluxcd.io/namespace: datadog
  name: datadog-cluster-agent-confd
  namespace: datadog
```

Only one thing I see in logs:

```
cluster-agent 2025-05-29 13:56:03 UTC | CLUSTER | DEBUG | (pkg/collector/corechecks/cluster/kubernetesapiserver/events_common.go:291 in getInvolvedObjectTags) | error getting entity for entity ID 'kubernetes_metadata://kustomize.toolkit.fluxcd.io/kustomizations/flux-system/cloudflared': tags may be missing
```

**Describe what happened:**
No customer metrics

**Describe what you expected:**
Expected new metrics 
for example: gotk.resource_info or kubernetes_state_customresource.eniconfig

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**
EKS 1.30 / Helm

**Comment by AndMerlin** [comment]
Thank you @sblumenthal for the explanation. 

I see that the feature is in developing. And regard what is expected: the problem is that I can't find the metrics in any prefix: kubernetes_state.customresource.* /kubernetes_state.* / kubernetes_state_customresource.*. I will rise the case with support team as I think this is should somehow show up in UI. 

Regarding metricNamePrefix, It is clear that the prefix will change, and this is what is expected from this parameter ccording to the instuction mentioned in HelmChart "See https://github.com/kubernetes/kube-state-metrics/blob/main/docs/metrics/extend/customresourcestate-metrics.md for a full description of each field."

**Comment by kneufeld-pbp** [comment]
@AndMerlin,

Have you modified the `datadog-datadog-ksm-core-dca` role to include Flux APIs? If so, how did you alter or augment the permissions using Flux?  

I was looking using this DD integrated feature because the agent is ignoring KSM's `customResourceState` metrics directly from a KSM pod. I am using otel autodiscover annotation on the pod. All the default KSM metrics are sent to Datadog, but the KSM customResourceState metrics (type `info`) for Flux are either ignored or not processed.

cluster-agent version: `7.67.0`

Case#2194518

@sblumenthal  Is [Monitoring your cluster with Kubernetes State Metrics](https://github.com/DataDog/datadog-operator/blob/main/docs/kubernetes_state_metrics.md) only documentation for all properties for the `kubernetes_state_core.yaml` configuration?  Is `custom_resource` an undocumented property?  This bug report is the only reference to  `custom_resource` I have been able to find.

**Comment by AndMerlin** [comment]
> Have you modified the datadog-datadog-ksm-core-dca role to include Flux APIs? If so, how did you alter or augment the permissions using Flux?

No

I was able to find a temporary solution. Some key points for consideration:
* metrics type info is not supported, use gauge instead
* Labels in metrics also don't work; use labelsFromPath right on the groupVersionKind level.

**Comment by kneufeld-pbp** [comment]
@AndMerlin would be able to share your KSM custom resource config for flux using gauge? 

@sblumenthal is support the metric type `info` in the works?

**Comment by kneufeld-pbp** [comment]
@AndMerlin 
As I expected, converting to gauge type is a painful process. ~~I can confirm DD is ignoring all metric labels(tags),  and only labels created at the groupVersionKind level. Due to DD ignoring these, one now has to manually create and maintain all these metrics, which is not sustainable in my environment.~~

To make sure the my KSM configuration is what I expect, I have been monitoring the KSM logs, to get registration of the metric, as well as shell into the DD Cluster Agent to curl the metric endpoint  on my KSM pod. In the process I discovered my mistake, for the my gauge configuration, indent level.  Maybe this also an issue for the integrated DD KSM. 

Here is my working gauge metric (all labels are in DD):
```yaml 
- groupVersionKind:
    group: kustomize.toolkit.fluxcd.io
    version: v1
    kind: Kustomization
  metricNamePrefix: kpn
  metrics:
    - name: "kustomization_resource_status"
      help: "The current state of Kustomization a GitOps Toolkit resource. 1 indicates Ready/True, 0 indicates not Ready/False"
      each:
        type: Gauge
        gauge:
          path: [status, conditions, "[type=Ready]"]
          valueFrom: [status]
          labelsFromPath:
            ready: [status]
            reason: [reason]
      labelsFromPath:
        customresource_name: [metadata, name]
        suspended: [spec, suspend]
        revision: [status, lastAppliedRevision]
        source_ref_kind: [spec, sourceRef, kind]
        source_ref_name: [spec, sourceRef, name]
```

How have others addressed integrating KSM custom RSM into Datadog, given the limited support? Skip DD altogether? Prometheus as a pre-processor?

**Comment by AndMerlin** [comment]
My KSM

`collectCrMetrics:
  - groupVersionKind:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
    labelsFromPath:
      name: [ metadata, name ]
    metrics:
      - name: "kustomization_suspend"
        help: "The current state of a Flux Kustomization resource."
        each:
          type: gauge
          gauge:
            path: [ spec]
            valueFrom: ["suspend"]
            labelsFromPath:
              suspend: [ "suspend" ]
      - name: "kustomization_ready"
        help: "The current state of a Flux Kustomization resource."
        each:
          type: gauge
          gauge:
            path: [ status, conditions,"0" ]
            valueFrom: [ "status" ]
            labelsFromPath:
              type: [ "type" ]
  - groupVersionKind:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
    labelsFromPath:
      name: [ metadata, name ]
    metrics:
      - name: "helmrelease_suspend"
        help: "The current state of a Flux HelmRelease resource."
        each:
          type: gauge
          gauge:
            path: [ spec ]
            valueFrom: [ "suspend" ]
            labelsFromPath:
              suspend: [ "suspend" ]
      - name: "helmrelease_ready"
        help: "The current state of a Flux HelmRelease resource."
        each:
          type: gauge
          gauge:
            path: [ status, conditions, "0" ]
            valueFrom: [ "status" ]
            labelsFromPath:
              type: [ "type" ]
  - groupVersionKind:
      group: source.toolkit.fluxcd.io
      version: v1
      kind: HelmChart
    labelsFromPath:
      name: [ metadata, name ]
    metrics:
      - name: "helmchart_ready"
        help: "The current state of a Flux HelmChart resource."
        each:
          type: gauge
          gauge:
            path: [ status, conditions, "[type=Ready]", status ]
            valueFrom: [ "status" ]
            labelsFromPath:
              type: [ "type" ]`

**Comment by kneufeld-pbp** [comment]
@AndMerlin Thanks

We went with the following, after trying few different including yours.
```yaml
    customResourceState:
      enabled: true
      config:
        kind: CustomResourceStateMetrics
        spec:
          resources:
            #--[ FluxCD Kustomizations ]---------
            - groupVersionKind:
                group: kustomize.toolkit.fluxcd.io
                version: v1
                kind: Kustomization
              metricNamePrefix: gotk
              metrics:
                - name: "resource_info"
                  help: "The Ready condition of FluxCD Kustomization resource. 1 indicates Ready/True, 0 indicates not Ready/False"
                  each:
                    type: Gauge
                    gauge:
                      path: [status, conditions, "[type=Ready]"]
                      valueFrom: [status]
                      labelsFromPath:
                        ready: [status]
                        reason: [reason]
                  commonLabels:
                    custom_metric: "true"
                    suspended: "false"
                    team: cloud-platform
                  labelsFromPath:
                    metadata_name: [metadata, name]
                    metadata_namespace: [metadata, namespace]
                    team: [metadata, labels, "tags.datadoghq.com/team"]
                    suspended: [spec, suspend]
                    revision: [status, lastAppliedRevision]
                    source_ref_kind: [spec, sourceRef, kind]
                    source_ref_name: [spec, sourceRef, name]
            #--[ FluxCD Sources ]----------------
            # Bucket
            - groupVersionKind:
                group: source.toolkit.fluxcd.io
                version: v1
                kind: Bucket
              metricNamePrefix: gotk
              metrics:
                - name: "resource_info"
                  help: "The Ready condition of FluxCD Bucket source resource. 1 indicates Ready/True, 0 indicates not Ready/False"
                  each:
                    type: Gauge
                    gauge:
                      path: [status, conditions, "[type=Ready]"]
                      valueFrom: [status]
                      labelsFromPath:
                        ready: [status]
                        reason: [reason]
                  commonLabels:
                    custom_metric: "true"
                    suspended: "false"
                    team: cloud-platform
                  labelsFromPath:
                    metadata_name: [metadata, name]
                    metadata_namespace: [metadata, namespace]
                    team: [metadata, labels, "tags.datadoghq.com/team"]
                    suspended: [spec, suspend]
                    revision: [status, lastAppliedRevision]
                    source_ref_kind: [spec, sourceRef, kind]
                    source_ref_name: [spec, sourceRef, name]
            # GitRepositories
            - groupVersionKind:
                group: source.toolkit.fluxcd.io
                version: v1
                kind: GitRepository
              metricNamePrefix: gotk
              metrics:
                - name: "resource_info"
                  help: "The Ready condition of FluxCD GitRepository source resource. 1 indicates Ready/True, 0 indicates not Ready/False"
                  each:
                    type: Gauge
                    gauge:
                      path: [status, conditions, "[type=Ready]"]
                      valueFrom: [status]
                      labelsFromPath:
                        ready: [status]
                        reason: [reason]
                  commonLabels:
                    custom_metric: "true"
                    suspended: "false"
                    team: cloud-platform
                  labelsFromPath:
                    metadata_name: [metadata, name]
                    metadata_namespace: [metadata, namespace]
                    team: [metadata, labels, "tags.datadoghq.com/team"]
                    suspended: [spec, suspend]
                    revision: [status, artifact, revision]
                    url: [spec, url]
            # HelmRepositoies
            - groupVersionKind:
                group: source.toolkit.fluxcd.io
                version: v1
                kind: HelmRepository
              metricNamePrefix: gotk
              metrics:
                - name: "resource_info"
                  help: "The Ready condition of FluxCD HelmRepository source resource. 1 indicates Ready/True, 0 indicates not Ready/False"
                  each:
                    type: Gauge
                    gauge:
                      path: [status, conditions, "[type=Ready]"]
                      valueFrom: [status]
                      labelsFromPath:
                        ready: [status]
                        reason: [reason]
                  commonLabels:
                    custom_metric: "true"
                    suspended: "false"
                    team: cloud-platform
                  labelsFromPath:
                    metadata_name: [metadata, name]
                    metadata_namespace: [metadata, namespace]
                    team: [metadata, labels, "tags.datadoghq.com/team"]
                    suspended: [spec, suspend]
                    revision: [status, artifact, revision]
                    url: [spec, url]
            # HelmChart
            - groupVersionKind:
                group: source.toolkit.fluxcd.io
                version: v1
                kind: HelmChart
              metricNamePrefix: gotk
              metrics:
                - name: "resource_info"
                  help: "The Ready condition of FluxCD HelmChart source resource. 1 indicates Ready/True, 0 indicates not Ready/False"
                  each:
                    type: Gauge
                    gauge:
                      path: [status, conditions, "[type=Ready]"]
                      valueFrom: [status]
                      labelsFromPath:
                        ready: [status]
                        reason: [reason]
                  commonLabels:
                    custom_metric: "true"
                    suspended: "false"
                    team: cloud-platform
                  labelsFromPath:
                    metadata_name: [metadata, name]
                    metadata_namespace: [metadata, namespace]
                    suspended: [spec, suspend]
                    team: [metadata, labels, "tags.datadoghq.com/team"]
                    revision: [status, artifact, revision]
                    chart_name: [spec, chart]
                    chart_version: [spec, version]
            # OCIRepositories
            - groupVersionKind:
                group: source.toolkit.fluxcd.io
                version: v1
                kind: OCIRepository
              metricNamePrefix: gotk
              metrics:
                - name: "resource_info"
                  help: "The Ready condition of FluxCD OCIRepository source resource. 1 indicates Ready/True, 0 indicates not Ready/False"
                  each:
                    type: Gauge
                    gauge:
                      path: [status, conditions, "[type=Ready]"]
                      valueFrom: [status]
                      labelsFromPath:
                        ready: [status]
                        reason: [reason]
                  commonLabels:
                    custom_metric: "true"
                    suspended: "false"
                    team: cloud-platform
                  labelsFromPath:
                    metadata_name: [metadata, name]
                    metadata_namespace: [metadata, namespace]
                    team: [metadata, labels, "tags.datadoghq.com/team"]
                    suspended: [spec, suspend]
                    revision: [status, artifact, revision]
                    url: [spec, url]

            #--[ FluxCD HelmRelease ]------------------
            - groupVersionKind:
                group: helm.toolkit.fluxcd.io
                version: v2
                kind: HelmRelease
              metricNamePrefix: gotk
              metrics:
                - name: "resource_info"
                  help: "The Ready condition of FluxCD HelmRelease resource. 1 indicates Ready/True, 0 indicates not Ready/False"
                  each:
                    type: Gauge
                    gauge:
                      path: [status, conditions, "[type=Ready]"]
                      valueFrom: [status]
                      labelsFromPath:
                        ready: [status]
                        reason: [reason]
                  commonLabels:
                    custom_metric: "true"
                    suspended: "false"
                    team: cloud-platform
                  labelsFromPath:
                    metadata_name: [metadata, name]
                    metadata_namespace: [metadata, namespace]
                    team: [metadata, labels, "tags.datadoghq.com/team"]
                    suspended: [spec, suspend]
                    revision: [status, lastAppliedRevision]
                    chart_name: [spec, chart, spec, chart]
                    chart_version: [status, history, "0", chartVersion]
                    chart_source_name: [spec, chart, spec, sourceRef, name]
                    app_version: [status, history, "0", appVersion]

            # #--[ FluxCD ImageAutomation ]--------------
            - groupVersionKind:
                group: image.toolkit.fluxcd.io
                version: v1beta2
                kind: ImageRepository
              metricNamePrefix: gotk
              metrics:
                - name: "resource_info"
                  help: "The Ready condition of FluxCD ImageRepository source resource. 1 indicates Ready/True, 0 indicates not Ready/False"
                  each:
                    type: Gauge
                    gauge:
                      path: [status, conditions, "[type=Ready]"]
                      valueFrom: [status]
                      labelsFromPath:
                        ready: [status]
                        reason: [reason]
                  commonLabels:
                    custom_metric: "true"
                    suspended: "false"
                    team: cloud-platform
                  labelsFromPath:
                    metadata_name: [metadata, name]
                    metadata_namespace: [metadata, namespace]
                    team: [metadata, labels, "tags.datadoghq.com/team"]
                    suspended: [spec, suspend]
                    canonical_image_name: [status, canonicalImageName]
                    latest_tag: [status, lastScanResult, latestTags, "-1"]
                    tag_count: [status, lastScanResult, tagCount]

            # ImagePolicy
            - groupVersionKind:
                group: image.toolkit.fluxcd.io
                version: v1beta2
                kind: ImagePolicy
              metricNamePrefix: gotk
              metrics:
                - name: "resource_info"
                  help: "The Ready condition of FluxCD ImagePolicy resource. 1 indicates Ready/True, 0 indicates not Ready/False"
                  each:
                    type: Gauge
                    gauge:
                      path: [status, conditions, "[type=Ready]"]
                      valueFrom: [status]
                      labelsFromPath:
                        ready: [status]
                        reason: [reason]
                  commonLabels:
                    custom_metric: "true"
                    suspended: "false"
                    team: cloud-platform
                  labelsFromPath:
                    metadata_name: [metadata, name]
                    metadata_namespace: [metadata, namespace]
                    team: [metadata, labels, "tags.datadoghq.com/team"]
                    suspended: [spec, suspend]
                    source_name: [spec, imageRepositoryRef, name]
                    latest_image: [status, latestImage]

            #ImageUpdateAutomation
            - groupVersionKind:
                group: image.toolkit.fluxcd.io
                version: v1beta2
                kind: ImageUpdateAutomation
              metricNamePrefix: gotk
              metrics:
                - name: "resource_info"
                  help: "The Ready condition of FluxCD ImageUpdateAutomation resource. 1 indicates Ready/True, 0 indicates not Ready/False"
                  each:
                    type: Gauge
                    gauge:
                      path: [status, conditions, "[type=Ready]"]
                      valueFrom: [status]
                      labelsFromPath:
                        ready: [status]
                        reason: [reason]
                  commonLabels:
                    custom_metric: "true"
                    suspended: "false"
                    team: cloud-platform
                  labelsFromPath:
                    metadata_name: [metadata, name]
                    metadata_namespace: [metadata, namespace]
                    team: [metadata, labels, "tags.datadoghq.com/team"]
                    suspended: [spec, suspend]
                    source_name: [spec, sourceRef, name]
            #--[ FluxCD Notifications ]----------------
            - groupVersionKind:
                group: notification.toolkit.fluxcd.io
                version: v1beta3
                kind: Provider
              metricNamePrefix: gotk
              metrics:
                - name: "resource_info"
                  help: "The Ready condition of FluxCD Notification Provider resource. 1 indicates Ready/True, 0 indicates not Ready/False"
                  each:
                    type: Gauge
                    gauge:
                      path: [status, conditions, "[type=Ready]"]
                      valueFrom: [status]
                      labelsFromPath:
                        ready: [status]
                        reason: [reason]
                  commonLabels:
                    custom_metric: "true"
                    suspended: "false"
                    team: cloud-platform
                  labelsFromPath:
                    metadata_name: [metadata, name]
                    metadata_namespace: [metadata, namespace]
                    team: [metadata, labels, "tags.datadoghq.com/team"]
                    suspended: [spec, suspend]
                    revision: [status, lastAppliedRevision]
                    source_ref_kind: [spec, sourceRef, kind]
                    source_ref_name: [spec, sourceRef, name]
            - groupVersionKind:
                group: notification.toolkit.fluxcd.io
                version: v1beta3
                kind: Receiver
              metricNamePrefix: gotk
              metrics:
                - name: "resource_info"
                  help: "The Ready condition of FluxCD Notification Receiver resource. 1 indicates Ready/True, 0 indicates not Ready/False"
                  each:
                    type: Gauge
                    gauge:
                      path: [status, conditions, "[type=Ready]"]
                      valueFrom: [status]
                      labelsFromPath:
                        ready: [status]
                        reason: [reason]
                  commonLabels:
                    custom_metric: "true"
                    suspended: "false"
                    team: cloud-platform
                  labelsFromPath:
                    metadata_name: [metadata, name]
                    metadata_namespace: [metadata, namespace]
                    team: [metadata, labels, "tags.datadoghq.com/team"]
                    suspended: [spec, suspend]
                    revision: [status, lastAppliedRevision]
                    source_ref_kind: [spec, sourceRef, kind]
                    source_ref_name: [spec, sourceRef, name]
```
