### ISSUE TITLE
[BUG] Scrubber can cause Agent to break its own config

### ISSUE THREAD

**Issue by aetimmes** [DataDog/datadog-agent#37876]
**Agent Environment**

Agent 7.65.2 - Commit: 0e9956bce2 - Serialization version: v5.0.145 - Go version: go1.23.8

**Describe what happened:**

Attempting to configure the APM agent to scrub `Authorization` from the curl.request_header tag as follows:

```
apm_config:
  replace_tags:
    - name: curl.request_header
       pattern: 'Authorization: token (.*)'
       repl: 'Authorization: ||--- SANITIZED ---||'
```

leads the agent to scrub its own config when the inventory agent [polls](https://github.com/DataDog/datadog-agent/blob/79a09a3a373c1c7eba9f1f9883a07a8d57416199/pkg/util/scrubber/default.go#L153-L163) the trace and process agent remotely:

```
replace_tags:
    - name: curl.request_header
      pattern: 'Authorization: "********"
      repl: 'Authorization: "********"
```

which is not valid YAML (since the trailing single quote got globbed and scrubbed), causing the inventory agent to fail when it attempts to read the config:

```
{"agent":"core","time":"2025-06-12 02:50:59 UTC","level":"ERROR","file":"comp/metadata/inventoryagent/inventoryagentimpl/inventoryagent.go","line":"213","func":"getCorrectConfig","msg":"Could not parse 'trace-agent' configuration: While parsing config: yaml: line 179: did not find expected key"}
```

We're currently working around this by doing:

```
            - name: curl.request_header
              pattern: '(?i)[Aa]uthorization: token (.*)'
              repl: '\x41uthorization: ||--- SANITIZED ---||'
```

which feels like a Not Nice Thing for me to leave behind for a colleague to stumble over later.

**Describe what you expected:**

The config to work as written/intended

**Steps to reproduce the issue:**

configure apm_config as above

**Additional environment details (Operating System, Cloud provider, etc):**

k8s, EKS, agents running on EC2 instances via daemonset; I can send a flare if y'all would like as well
