### ISSUE TITLE
Add `kube_image_pull_duration_seconds`

### ISSUE THREAD

**Issue by gnuletik** [DataDog/datadog-agent#38238]
Hi!

Since Kubernetes v1.30, kubelet exposes a metric named `image_pull_duration_seconds`:
See https://github.com/kubernetes/kubernetes/pull/121719

However, I don't see this metric exposed in the kubelet integration:
https://docs.datadoghq.com/integrations/kubelet/

Could you add support for this metric?

Thanks!

**Comment by jan-ludvik** [comment]
you can import this into confd under `openmetrics.yaml` to get those. Unfortunately this way you have to pay for it
```
init_config: null
instances:
  - openmetrics_endpoint: https://localhost:10250/metrics
    metrics:
      - kubelet_node_*
      - kubelet_pod_start_*
      - kubelet_image_*
    collect_counters_with_distributions: true
    send_distribution_buckets: true
    tls_verify: false
    tags:
      - team:<team_name>
      - service:kubelet
    auth_token:
      reader:
        type: file
        path: /var/run/secrets/kubernetes.io/serviceaccount/token
      writer:
        type: header
        name: Authorization
        value: Bearer <TOKEN>
```
