### ISSUE TITLE
Datadog agent doesn't collect logs when the pod is not ready

### ISSUE THREAD

**Issue by brennoo** [DataDog/datadog-agent#3866]
**Describe what happened:**
Datadog Agent (v6.10.1) doesn't collect the logs when the pod is not ready (readiness gates true)
If/When the pod becomes ready the docker tailer fetches the logs since the beginning correctly but the problem is when we have a startup error - eg. with a new deployment rollout - we would never get the logs into DD if the new containers don't get passed readiness gates.

**Describe what you expected:**
I expected that once the pod started producing logs the agent is tailing and DD ingesting.

**Steps to reproduce the issue:**
One can deploy this pod and check (not ready) logs are not being sent to DD, you can tweak it to make it pass readiness
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: readiness-logs
spec:
  containers:
  - name: readiness
    image: k8s.gcr.io/busybox
    args:
    - /bin/sh
    - -c
    - for i in `seq 1 10`; do echo $(date) - not ready; sleep 60; done; touch /tmp/r; for i in `seq 1 10`; do echo $(date) - ready && sleep 3; done; rm -rf /tmp/r; sleep 60
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/r
      initialDelaySeconds: 300
      periodSeconds: 30
```

**Additional environment details (Operating System, Cloud provider, etc):**
We are using public chart deployed on AWS EKS 1.12.7
