### ISSUE TITLE
dd.internal.entity_id isn't respected for UDS metrics

### ISSUE THREAD

**Issue by danopia** [DataDog/datadog-agent#3870]
### Describe what happened:
I am using a Kubernetes agent with UDS (Unix sockets). I have C# applications, where the C# dogstatsd library lacks UDS support. I added a socat sidecar container to my application pods, and pointed the application to `127.0.0.1:8125`.

The metrics make it through to Datadog. However, they are tagged with the socat container's tags (for example `image_name:alpine/socat`). I configured `DD_ENTITY_ID` which had no effect on the socat tags. It seems the UDS origin tags merge with (and possibly overwrite) `DD_ENTITY_ID` origin tags.

### Describe what you expected:
I expected the `entity_id` to override the UDS origin information if it was provided. I did not expect to see my application metrics origin-tagged as the socat proxy.

I also expected `entity_id` to provide container-level granularity (image version would be quite nice) though that may deserve a separate ticket.

### Steps to reproduce the issue:
Deploy a UDS kubernetes agent. Configure a UDP-dogstatsd pod with a socat proxy, and also an entity ID:

```yaml
        - name: app
          args:
            - dotnet
            - MyApp.dll
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Staging
            - name: DD_AGENT_HOST
              value: 127.0.0.1
            - name: DD_ENTITY_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          image: ....
          ......
        - name: udppipe
          args:
            - '-s'
            - '-u'
            - 'UDP-RECV:8125'
            - 'UNIX-SENDTO:/var/run/datadog/dsd.socket'
          image: alpine/socat
          volumeMounts:
            - mountPath: /var/run/datadog
              name: dsdsocket
              readOnly: true
```

### Workaround
I added a different socat proxy container to _the actual datadog agents_:

```yaml
      - args:
        - '-s'
        - '-u'
        - 'UNIX-RECV:/var/run/datadog/dsd-anon.socket'
        - 'UDP-SENDTO:127.0.0.1:8125'
        image: alpine/socat
        name: udppipe
        volumeMounts:
          - mountPath: /var/run/datadog
            name: dsdsocket
```

This listens on a _second_ 'anonymous' socket and pipes packets back to UDP to the localhost agent. I point my UDP applications to that alternative `dd-anon.socket`, which blocks Datadog Agent from reading the socat UDS origin. Now only the `DD_ENTITY_ID` origin tags are used.
