### ISSUE TITLE
[k8s] External HPA - Multiple metrics odd behavior

### ISSUE THREAD

**Issue by andysnowden** [DataDog/datadog-agent#3872]
**Describe what happened:**
While attempting to setup some custom HPAs using datadog external metrics we ran into a few weird conditions.  Specifically our use case is scaling up a StatefulSet when 2 or more rabbitMQ queues is above a threshold.

**Failure 1**
One HPA defined with 2 metrics with the same `metricName` but different `metricSelector`.

In this failure the cluster-agent sees both metrics when the HPA is created, but because the `metricName` is the same only one gets saved to the `datadog-custom-metrics` configmap.  Likewise when HPA attempts to poll the number it actually can't find either of them

HPA yaml:
```yaml
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: test-multi
spec:
  maxReplicas: 10
  metrics:
    - external:
        metricName: rabbitmq.queue.messages
        metricSelector:
          matchLabels:
            rabbitmq_queue: kemcho-low-prio-queue
        targetValue: 500
      type: External
    - external:
        metricName: rabbitmq.queue.messages
        metricSelector:
          matchLabels:
            rabbitmq_queue: dpc-go-http-error
        targetValue: 500
      type: External
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: test-multi
```

Custom Metrics ConfigMap Output:
```yaml
kubectl describe configmap/datadog-custom-metrics -n kube-system
Name:         datadog-custom-metrics
Namespace:    kube-system
Labels:       <none>
Annotations:  custom-metrics.datadoghq.com/last-updated: 2019-07-12T21:12:31Z

Data
====
external_metric-prod-test-multi-rabbitmq.queue.messages:
----
{"metricName":"rabbitmq.queue.messages","labels":{"rabbitmq_queue":"dpc-go-http-error"},"ts":1562965890,"hpa":{"name":"test-multi","namespace":"prod","uid":"3391b4bd-a4e8-11e9-b297-12235c4363da"},"value":469,"valid":true}
Events:  <none>
```

Likewise the cluster-agent status reports only 1 metric
```
  Custom Metrics Server
  =====================
    ConfigMap name: kube-system/datadog-custom-metrics
    
    External Metrics
    ----------------
      Total: 1
      Valid: 1
      hpa:
      - name: test-multi
      - namespace: prod
      - uid: 3391b4bd-a4e8-11e9-b297-12235c4363da
      labels:
      - rabbitmq_queue: dpc-go-http-error
      metricName: rabbitmq.queue.messages
      ts: 1.56296598e&#43;09
      valid: true
      value: 469
```

datadog-cluster-agent is only pulling 1 of the 2 defined metrics

**Failure/ish 2**
Like Failure 1 this is a HPA with 2 metrics, the difference here is there is another HPA defined with a single metric with a shared `metricName` and `matchLabels`.  In this case the first HPA will actually work as long as the second HPA is defined.

HPA(s) yaml:
```yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: test-multi
spec:
  maxReplicas: 10
  metrics:
    - external:
        metricName: rabbitmq.queue.messages
        metricSelector:
          matchLabels:
            rabbitmq_queue: kemcho-high-prio-queue
        targetValue: 500
      type: External
    - external:
        metricName: rabbitmq.queue.messages
        metricSelector:
          matchLabels:
            rabbitmq_queue: dpc-go-http-error
        targetValue: 500
      type: External
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: test-multi
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: v3-15-1-celery
spec:
  maxReplicas: 10
  metrics:
    - external:
        metricName: rabbitmq.queue.messages
        metricSelector:
          matchLabels:
            rabbitmq_queue: kemcho-high-prio-queue
        targetValue: 500
      type: External
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: v3-15-1-celery
```

Note: `kemcho-high-prio-queue` is the shared metric between the two HPAs.  In this failure/ish both metrics required by the first HPA exist in the configmap.

Custom Metrics ConfigMap Output:
```yaml
kubectl describe configmap/datadog-custom-metrics -n kube-system
Name:         datadog-custom-metrics
Namespace:    kube-system
Labels:       <none>
Annotations:  custom-metrics.datadoghq.com/last-updated: 2019-07-12T21:24:31Z

Data
====
external_metric-prod-test-multi-rabbitmq.queue.messages:
----
{"metricName":"rabbitmq.queue.messages","labels":{"rabbitmq_queue":"dpc-go-http-error"},"ts":1562966610,"hpa":{"name":"test-multi","namespace":"prod","uid":"e34eea57-a4ea-11e9-b297-12235c4363da"},"value":469,"valid":true}

external_metric-prod-v3-15-1-celery-rabbitmq.queue.messages:
----
{"metricName":"rabbitmq.queue.messages","labels":{"rabbitmq_queue":"kemcho-high-prio-queue"},"ts":1562966610,"hpa":{"name":"v3-15-1-celery","namespace":"prod","uid":"518a7de0-a4e1-11e9-b297-12235c4363da"},"value":55,"valid":true}
Events:  <none>
```

In this case both custom metrics are reported in the cluster-agent.

```
  Custom Metrics Server
  =====================
    ConfigMap name: kube-system/datadog-custom-metrics
    
    External Metrics
    ----------------
      Total: 2
      Valid: 2
      hpa:
      - name: test-multi
      - namespace: prod
      - uid: e34eea57-a4ea-11e9-b297-12235c4363da
      labels:
      - rabbitmq_queue: dpc-go-http-error
      metricName: rabbitmq.queue.messages
      ts: 1.56296691e&#43;09
      valid: true
      value: 469
      hpa:
      - name: v3-15-1-celery
      - namespace: prod
      - uid: 518a7de0-a4e1-11e9-b297-12235c4363da
      labels:
      - rabbitmq_queue: kemcho-high-prio-queue
      metricName: rabbitmq.queue.messages
      ts: 1.56296691e&#43;09
      valid: true
      value: 3
```

The "workaround" in my use case does not fix the problem.  I would have to define a secondary HPA to get my actual HPA to work and I have nothing for the secondary HPA to reference.

**Describe what you expected:**
I expected multiple-metric HPAs to work without having to need

**Steps to reproduce the issue:**
Define a HPA with 2 or more custom metrics that share the same `metricName` but different `metricSelector`

**Additional environment details (Operating System, Cloud provider, etc):**
Kubernetes Version: v1.12.9
Datadog-agent version: v6.10.1
Datadog-cluster-agent version: v1.2.0

Let me know if you need more details!
