### ISSUE TITLE
[cluster-agent] Getting kube-state-metrics via cluster-agent

### ISSUE THREAD

**Issue by coreypobrien** [DataDog/datadog-agent#3923]
What would it take to make the cluster-agent responsible for gathering kube-state-metrics instead of the node agent in a Kubernetes cluster?

The problem I'm trying to address is around scaling. Similar to why scaling improves with the cluster-agent being responsible for cluster-wide checks, the kube-state-metrics collection doesn't scale well with the node daemonset.

In a cluster with hundreds of nodes and thousands of pods, there is only 1 kube-state-metrics pod collecting data for the whole cluster. The only pod scraping and forwarding kube-state-metrics is the datadog agent on the same node as kube-state-metrics. This one datadog agent then requires a disproportionate amount of resources (e.g. memory) to process the kube-state-metrics for the whole cluster. However, because of the nature of a daemonset, the increased memory for processing the kube-state-metrics has to be reserved identically for every datadog agent on every node, even though only 1 agent is _actually_ processing that data.

Obviously there is some fancy deployment organization that could be done where there is a datadog agent deployed with a configuration _specifically_ to grab kube-state-metrics while the normal daemonset ignores them, etc. It feels like the right solution is to treat kube-state-metrics as the cluster-scoped (instead of node-scoped) metrics that they are and have the cluster-scoped agent scrape them instead of the node-scoped agent.

**Comment by CharlyF** [comment]
Hey @coreypobrien !

That's a great question. The KSM check is a python check and as the Cluster Agent does not embed a python interpreter we can't run python checks.

The way we solved this problem is by running the KSM check as a set of [Cluster Checks](https://docs.datadoghq.com/agent/autodiscovery/clusterchecks/). Here is a 3 steps procedure to get started with such a configuration. We are currently documenting this properly for what it's worth.

1st Step 
---

This means that you deploy your node agent DS as usual and you deploy the Cluster Agent with [the following option](https://gist.github.com/CharlyF/e0146aa4d8b9d4f57de00d2fc9882cb7#file-datadog_cluster_agent-yaml-L37-L42):
```
        - name: DD_CLUSTER_CHECKS_ENABLED
          value: "true"
        - name: DD_EXTRA_CONFIG_PROVIDERS
          value: "kube_services kube_endpoints"
        - name: DD_EXTRA_LISTENERS
          value: "kube_services kube_endpoints"
```
We are [using a secret](https://gist.github.com/CharlyF/e0146aa4d8b9d4f57de00d2fc9882cb7#file-datadog_cluster_agent-yaml-L43-L47) to store the key used to authenticate the calls between the node agents and the Cluster Agent, if you are using the manifests I am linking here, you can create the key by running this:
```
kubectl create secret generic datadog-auth-token --from-literal=token=$(openssl rand -hex 16)
```
Worth noting, if you are configuring the replicas of your node agent from the DS to interact with the Cluster Agent, make sure they are using the same token.

Also don't forget to add [your API KEY](https://gist.github.com/CharlyF/e0146aa4d8b9d4f57de00d2fc9882cb7#file-datadog_cluster_agent-yaml-L28).

2nd Step
--- 
Then, you can deploy a dedicated Deployment of the node agent with what we refer to as "Cluster Level Check Worker" configuration.
Here is [the deployment](https://gist.github.com/CharlyF/d3596ad6ffdace94971cb974ac4b6230)
Note the [following configuration](https://gist.github.com/CharlyF/d3596ad6ffdace94971cb974ac4b6230#file-datadog_cluster_check_worker-yaml-L42-L45):
```
        - name: DD_EXTRA_CONFIG_PROVIDERS
          value: "clusterchecks"
        - name: DD_CLUSTER_AGENT_ENABLED
          value: "true"
```
Enables the Cluster Level Check feature on the node agent, thus making the replicas query the Cluster Agent for Cluster Checks configs to run.

The [following option](https://gist.github.com/CharlyF/d3596ad6ffdace94971cb974ac4b6230#file-datadog_cluster_check_worker-yaml-L28-L29) is critical:
```
        - name: DD_ENABLE_METADATA_COLLECTION
          value: "false"
```
It will prevent the metadata submission, avoiding any conflicting metadata resolution in the backend. 

```
        - name: DD_ENABLE_STREAM_PAYLOAD_SERIALIZATION
          value: "true"
```
Is a feature that was designed to run this type of heavy checks, we have been using internally to reduce the memory footprint of the worker. It should be enabled by default but I figured it was worth pointing out.

Then we can increase the req/lim of the worker for it to be able to run the check. Depending on the size of your cluster and the number of objects you might need to vertically scale the replicas, but running large cluster, we have been seeing good results with:
```
          limits:
            cpu: "1"
            memory: 2500Mi
          requests:
            cpu: "1"
            memory: 2500Mi
```

We also don't want the cluster check worker to run the default checks, the quick solution is to simply override the default configurations folder:
```
        volumeMounts:
        - mountPath: /etc/datadog-agent
          name: datadog-agent-config
[...]
      volumes:
      - emptyDir: {}
        name: datadog-agent-config
```

Also don't forget to add [your API KEY](https://gist.github.com/CharlyF/d3596ad6ffdace94971cb974ac4b6230#file-datadog_cluster_check_worker-yaml-L47)
Worth noting we [update the health port](https://gist.github.com/CharlyF/d3596ad6ffdace94971cb974ac4b6230#file-datadog_cluster_check_worker-yaml-L38-L39) of the worker, as it will run on the same node as another agent we do not want to potentially conflict (this could happen if you are running the agents in hostNet).

3rd Step
--- 
Then, you can add annotations to KSM for the Cluster Agent to "autodiscover" the Cluster check configuration and schedule it on the worker. This happens at [the service level](https://gist.github.com/CharlyF/8af0177f28163d6be56af6002a2327c4#file-kubernetes_state_nodes-yaml-L4-L17):
```
    ad.datadoghq.com/service.check_names: '["kubernetes_state"]'
    ad.datadoghq.com/service.init_configs: '[{}]'
    ad.datadoghq.com/service.instances: |
      [
        {
          "kube_state_url": "http://%%host%%:8080/metrics",
          "prometheus_timeout": 30,
          "min_collection_interval": 30,
          "send_pod_phase_service_checks": false,
          "tags": ["datacenter:dog"],
          "telemetry": true
        }
      ]
```
But as you said, the node agent also runs the KSM check when they are located on the same node as the KSM pod using the image based autodiscovery.

There are 2 solutions: Either you add empty annotations to the deployment (they super-sed the image based autodiscovery). Or, as we [enable the telemetry here](https://gist.github.com/CharlyF/8af0177f28163d6be56af6002a2327c4#file-kubernetes_state_nodes-yaml-L60), you can [configure a prometheus check on the telemetry](https://gist.github.com/CharlyF/8af0177f28163d6be56af6002a2327c4#file-kubernetes_state_nodes-yaml-L46-L51).
```
        ad.datadoghq.com/kube-state-metrics.check_names: '["prometheus"]'
        ad.datadoghq.com/kube-state-metrics.init_configs: '[{}]'
        ad.datadoghq.com/kube-state-metrics.instances: '[{"prometheus_url": "http://%%host%%:8081/metrics",
          "namespace": "ksm-nodes-telemetry", "metrics": ["*"], "max_returned_metrics":
          50}]'
        ad.datadoghq.com/kube-state-metrics.logs: '[{"service":"kube-state-metrics"}]'
```
From my experience I see ~50 metrics but feel free to adjust the annotations if you have more in your case or if you want to rename the metrics namespace.

Worth noting: We also recommend splitting the collectors of KSM into 3 different deployments behind their respective services as follows:
```
        - --collectors=nodes
```
```
        - --collectors=pods
```
```
        - --collectors=configmaps,services,endpoints,daemonsets,deployments,cronjobs,statefulsets,horizontalpodautoscalers,limitranges,resourcequotas,secrets,namespaces,replicationcontrollers,resourcequotas,persistentvolumeclaims,persistentvolumes,jobs,replicasets
```

This is, from our experience, a good way to balance the size of the output exposed by KSM overall.

The one I linked here is the node one, but the others are similar. 

The consequence of doing this is that we effectively run 3 Cluster Checks (one for each collector, or group thereof) and we have 3 replicas of the worker. This alleviates the footprint of each worker and makes the monitoring of KSM much more resilient.

PS: my manifests are using service accounts and namespaces that might differ from your cluster, you might need to adjust that too.

I do hope that this helps and as always feel free to reach out if you have questions!
Best,
.C

**Comment by coreypobrien** [comment]
Awesome! I love the pattern, I'll give it a try with the current official helm chart. Do you have any objection to making this the default with the helm chart?

**Comment by CharlyF** [comment]
I think it'd be best indeed but the Cluster Agent is not part of the default deployment at the moment - Let me circle back with my team and we can get back to you.
More importantly, if you end up giving it a go and have feedback, please let us know :)

**Comment by coreypobrien** [comment]
Thanks! It looks like most of this is already supported by the official chart, just not enabled by default. A few questions about your recommendations:

1. Does the cluster level check worker scale horizontally? You've got 1 replica here (https://gist.github.com/CharlyF/d3596ad6ffdace94971cb974ac4b6230#file-datadog_cluster_check_worker-yaml-L10), but the official chart has 2 replicas by default (https://github.com/helm/charts/blob/df65ee1cfb5209b098fb53dcc1cb81acf1dd8810/stable/datadog/values.yaml#L639). Is there a leadership process or is there some intelligent division of labor between multiple agents?

2. It looks like the official KSM chart doesn't allow for service annotations so I opened https://github.com/helm/charts/pull/15864. I'll PR a bump to the official chart version after that merges.

3. For disabling the autodiscovery on KSM, is the telemetry just "something else"? In other words, there isn't a specific requirement that we check the telemetry right? Would it be just as effective to do something like this?
    ```
            [{
                "prometheus_url": "http://%%host%%:8080/metrics",
                "namespace": "kubernetes_state",
                "metrics": ["justnullifyeverything*"],
                "max_returned_metrics": "0"
              }]
    ```

4. You have both `kube_services` and `kube_endpoints` enabled in your cluster agent. Is there any downside to having both enabled? Asking since the official chart only has `kube_services`.

**Comment by CharlyF** [comment]
> Does the cluster level check worker scale horizontally

Yes, the logic to dispatch the cluster level checks is by round robin, we are working on a rebalancing logic at the moment. The workers are stateless in this case.

> the official KSM chart doesn't allow for service annotations

Neat, thanks!

> For disabling the autodiscovery on KSM, is the telemetry just "something else"

Indeed, not a requirement at all. It's simply that you can get data and achieve the same goal.

> You have both kube_services and kube_endpoints enabled in your cluster agent.

In this case, only `kube_service` is required, the `kube_endpoint` option is for endpoint checks (you use similar annotations, but the check is dispatched on the agent running on the same node as the endpoint. It's not a "Cluster check" per se, but is a nifty feature that we released very recently, see the official doc [here](https://docs.datadoghq.com/agent/autodiscovery/endpointschecks/). I'll chat with the team so we can add it to the chart.

**Comment by kivagant-ba** [comment]
@CharlyF, @hkaj after spending 2 days trying to make everything work together I also found important to:

1. Update DD Helm Chart dependency for kube-state-metrics from ~2.0.0 to ~2.2.0 to support https://github.com/helm/charts/pull/15864:
https://github.com/helm/charts/blob/master/stable/datadog/requirements.yaml#L3

2. I don't know if this is only problem for our setup but we found that the new metrics from cluster-agent come without the old `kubernetescluster` tag we had with older DD configuration. To fix that I added the following env variable to the Helm chart values:

```
# values.yaml

clusterAgent:

# ... other settings

  env:
# This also works but it's better not to break the default value 
# but add another one for backward compatibility
# - name: DD_CLUSTER_CHECKS_CLUSTER_TAG_NAME 
# value: "kubernetescluster" 
    - name: DD_CLUSTER_CHECKS_EXTRA_TAGS
      value: "kubernetescluster:my-lovely-cluster"
```

3. And as @CharlyF suggested in his commit I added the annotations to the Chart values:

```
# values.yaml
kube-state-metrics:

# ... other settings

  service:
    annotations:
      # https://github.com/DataDog/documentation/pull/5013/
      ad.datadoghq.com/service.check_names: '["kubernetes_state"]'
      ad.datadoghq.com/service.init_configs: '[{}]'
      ad.datadoghq.com/service.instances: |
        [
        {
            "kube_state_url": "http://%%host%%:8080/metrics",
            "prometheus_timeout": 30,
            "min_collection_interval": 30,
            "send_pod_phase_service_checks": false,
            "telemetry": true
        }
        ]

```

4. And after all of this I was able to increase resources for clustercheck:

```
# values.yaml
clusterchecksDeployment:

# ... other settings

  resources:
    requests:
      cpu: 200m
      memory: 756Mi
    limits:
      # cpu: 200m
      memory: 756Mi

```

Just in case if someone needs all Helm Chart settings together that differ from defaults, here they are:

```
datadog:
  apiKeyExistingSecret: "datadog-secret"
  clusterName: my-lovely-cluster
  dogstatsdOriginDetection: true
  nonLocalTraffic: true
  collectEvents: true
  leaderElection: true
  leaderLeaseDuration: 60
  logsEnabled: false # We use another log collector
  logsConfigContainerCollectAll: false
  apmEnabled: true
  processAgentEnabled: true
  volumes:
    # https://github.com/DataDog/datadog-agent/issues/1853#issuecomment-518718004
    # https://github.com/DataDog/documentation/pull/5013/files
    - name: empty-dir
      emptyDir: {}
  volumeMounts:
    # https://github.com/DataDog/datadog-agent/issues/1853#issuecomment-518718004
    # https://github.com/DataDog/documentation/pull/5013/files
    - name: empty-dir
      mountPath: /etc/datadog-agent/conf.d/kubernetes_state.d
      readOnly: true
  confd:
    # https://github.com/DataDog/datadog-agent/issues/1853#issuecomment-510263791
    kubernetes_state.yaml: ""
  resources: {} # configure

clusterAgent:
  enabled: true
  token: "RANDOM_TOKEN_IS_HERE"
  replicas: 2
  clusterChecks:
    enabled: true
  env:
    - name: DD_CLUSTER_CHECKS_EXTRA_TAGS
      value: "kubernetescluster:my-lovely-cluster"
  priorityClassName: system-cluster-critical
  resources: {} # configure

kube-state-metrics:
  resources: {} # configure
  service:
    annotations:
      # https://github.com/DataDog/documentation/pull/5013/
      ad.datadoghq.com/service.check_names: '["kubernetes_state"]'
      ad.datadoghq.com/service.init_configs: '[{}]'
      ad.datadoghq.com/service.instances: |
        [
        {
            "kube_state_url": "http://%%host%%:8080/metrics",
            "prometheus_timeout": 30,
            "min_collection_interval": 30,
            "send_pod_phase_service_checks": false,
            "telemetry": true
        }
        ]


daemonset:
  containers:
    agent:
      resources: {} # configure
    processAgent:
      resources: {} # configure
    traceAgent:
      resources: {} # configure
  useHostPort: true
  priorityClassName: system-node-critical


```
