### ISSUE TITLE
write udp connection refused

### ISSUE THREAD

**Issue by FelipeUmpierre** [DataDog/datadog-agent#3988]
**Output of the info page (if this is a bug)**
```
===============
Agent (v6.13.0)
===============

  Status date: 2019-08-08 15:21:22.500223 UTC
  Agent start: 2019-08-08 15:11:47.717626 UTC
  Pid: 332
  Go Version: go1.11.5
  Python Version: 2.7.16
  Check Runners: 4
  Log Level: INFO

  Paths
  =====
    Config File: /etc/datadog-agent/datadog.yaml
    conf.d: /etc/datadog-agent/conf.d
    checks.d: /etc/datadog-agent/checks.d

  Clocks
  ======
    NTP offset: -2.649ms
    System UTC time: 2019-08-08 15:21:22.500223 UTC

  Host Info
  =========
    bootTime: 2019-07-02 12:24:22.000000 UTC
    kernelVersion: 4.14.123-111.109.amzn2.x86_64
    os: linux
    platform: debian
    platformFamily: debian
    platformVersion: 10.0
    procs: 68
    uptime: 890h47m29s

  Hostnames
  =========
    hostname: ip-10-0-3-40.eu-central-1.compute.internal
    socket-fqdn: datadog-85bf59df65-m7c5h
    socket-hostname: datadog-85bf59df65-m7c5h
    host tags:
      [env:staging]
    hostname provider: container
    unused hostname providers:
      aws: unable to fetch EC2 API, status code 404 trying to fetch http://169.254.169.254/latest/meta-data/instance-id
      configuration/environment: hostname is empty
      gce: unable to retrieve hostname from GCE: status code 404 trying to GET http://169.254.169.254/computeMetadata/v1/instance/hostname

=========
Collector
=========



  Running Checks
  ==============

    cpu
    ---
      Instance ID: cpu [OK]
      Total Runs: 39
      Metric Samples: Last Run: 6, Total: 228
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s


    disk (2.4.0)
    ------------
      Instance ID: disk:e5dffb8bef24336f [OK]
      Total Runs: 38
      Metric Samples: Last Run: 182, Total: 6,916
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 110ms


    docker
    ------
      Instance ID: docker [OK]
      Total Runs: 38
      Metric Samples: Last Run: 806, Total: 30,540
      Events: Last Run: 0, Total: 1
      Service Checks: Last Run: 1, Total: 38
      Average Execution Time : 58ms


    file_handle
    -----------
      Instance ID: file_handle [OK]
      Total Runs: 38
      Metric Samples: Last Run: 5, Total: 190
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s


    io
    --
      Instance ID: io [OK]
      Total Runs: 38
      Metric Samples: Last Run: 39, Total: 1,455
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s


    kubelet (3.3.1)
    ---------------
      Instance ID: kubelet:d884b5186b651429 [ERROR]
      Total Runs: 38
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 3ms
      Error: Unable to detect the kubelet URL automatically.
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/base/checks/base.py", line 503, in run
          self.check(instance)
        File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/datadog_checks/kubelet/kubelet.py", line 179, in check
          raise CheckException("Unable to detect the kubelet URL automatically.")
      CheckException: Unable to detect the kubelet URL automatically.

    load
    ----
      Instance ID: load [OK]
      Total Runs: 38
      Metric Samples: Last Run: 6, Total: 228
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s


    memory
    ------
      Instance ID: memory [OK]
      Total Runs: 38
      Metric Samples: Last Run: 17, Total: 646
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 1ms


    network (1.11.0)
    ----------------
      Instance ID: network:e0204ad63d43c949 [OK]
      Total Runs: 38
      Metric Samples: Last Run: 152, Total: 5,776
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 3ms


    ntp
    ---
      Instance ID: ntp:b4579e02d1981c12 [OK]
      Total Runs: 38
      Metric Samples: Last Run: 1, Total: 38
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 38
      Average Execution Time : 0s


    uptime
    ------
      Instance ID: uptime [OK]
      Total Runs: 38
      Metric Samples: Last Run: 1, Total: 38
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s

========
JMXFetch
========

  Initialized checks
  ==================
    no checks

  Failed checks
  =============
    no checks

=========
Forwarder
=========

  Transactions
  ============
    CheckRunsV1: 38
    Dropped: 0
    DroppedOnInput: 0
    Events: 0
    HostMetadata: 0
    IntakeV1: 4
    Metadata: 0
    Requeued: 0
    Retried: 0
    RetryQueueSize: 0
    Series: 0
    ServiceChecks: 0
    SketchSeries: 0
    Success: 80
    TimeseriesV1: 38

  API Keys status
  ===============
    API key ending with 3f0ea: API Key valid

==========
Endpoints
==========
  https://app.datadoghq.com - API Key ending with:
      - 3f0ea

==========
Logs Agent
==========

  Logs Agent is not running

=========
Aggregator
=========
  Checks Metric Sample: 46,818
  Dogstatsd Metric Sample: 96
  Event: 2
  Events Flushed: 2
  Number Of Flushes: 38
  Series Flushed: 39,264
  Service Check: 458
  Service Checks Flushed: 492

=========
DogStatsD
=========
  Event Packets: 0
  Event Parse Errors: 0
  Metric Packets: 95
  Metric Parse Errors: 0
  Service Check Packets: 0
  Service Check Parse Errors: 0
  Udp Bytes: 5,263
  Udp Packet Reading Errors: 0
  Udp Packets: 96
  Uds Bytes: 0
  Uds Origin Detection Errors: 0
  Uds Packet Reading Errors: 0
  Uds Packets: 0
```

**Describe what happened:**
I have installed the agent in my Kubernetes cluster for a few days and it was normally working for us, sending the metrics and logs as expected. After we add the possibility of having custom tags for all the metrics in our helm chart configuration, we started to see errors os connection refused when trying to send the metrics though udp connection.

```
write udp [POD_IP]:50132-> [KUBERNETES_NODE_IP]:8125: write: connection refused
```

**Describe what you expected:**
The expected behaviour is to successfully send the metrics to Datadog.

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**
We are using EKS and our code uses [Opencensus](https://opencensus.io) exporter to send the metrics. Our agent endpoint is the `KUBERNETES_NODE_IP`

```
NAME                         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)
datadog                      ClusterIP   [IP]   <none>        8125/UDP
```

Helm configuration:

***version: 1.32.1***
```
datadog:
  apiKey: key
  clusterName: staging
  name: datadog
  tags:
    - env:staging
  dogstatsdOriginDetection: true
  nonLocalTraffic: true
  collectEvents: true
  logsEnabled: true
  logsConfigContainerCollectAll: true
  processAgentEnabled: true
  resources: {}
clusterAgent:
  enabled: true
  token: "token"
  replicas: 1
  metricsProvider:
    enabled: false
  clusterChecks:
    enabled: false
  resources: {}
rbac:
  create: true
  serviceAccountName: default
tolerations: []
kubeStateMetrics:
  enabled: true
kube-state-metrics:
  rbac:
    create: true
    serviceAccountName: default
daemonset:
  enabled: true
  useHostPort: true
  containers:
    agent:
      resources: {}
    processAgent:
      resources: {}
    traceAgent:
      resources: {}
deployment:
  enabled: true
  replicas: 1
```
