### ISSUE TITLE
Datadog StatsD is not listening on port 8125

### ISSUE THREAD

**Issue by renannprado** [DataDog/datadog-agent#4125]
So I'm trying to use the Datadog StatsD feature of the agent, however I'm not sure how to enable it.

Currently I have the following variables in my daemon set, but still there's nothing listening on port 8125. I also couldn't find in the documentation how to turn this on.

```yaml
- name: DD_API_KEY
  valueFrom:
    secretKeyRef:
      key: api-key
      name: datadog-secret
- name: DD_DOGSTATSD_PORT
  value: "8125"
- name: DD_USE_DOGSTATSD
  value: "true"
- name: DD_DOGSTATSD_NON_LOCAL_TRAFFIC
  value: "true"
- name: DD_EXTRA_CONFIG_PROVIDERS
  value: kube_services kubelet
- name: DD_EXTRA_LISTENERS
  value: kube_services kubelet
- name: DD_PROCESS_AGENT_ENABLED
  value: "true"
- name: DD_SITE
  value: datadoghq.com
- name: DD_COLLECT_KUBERNETES_EVENTS
  value: "true"
- name: DD_LEADER_ELECTION
  value: "true"
- name: KUBERNETES
  value: "true"
- name: DD_KUBERNETES_KUBELET_HOST
  valueFrom:
    fieldRef:
      apiVersion: v1
      fieldPath: status.hostIP
- name: DD_APM_ENABLED
  value: "true"
```

I'm using the latest version of `datadog/agent:latest`.
