### ISSUE TITLE
Using invalid metric names for k8s HPA with the cluster agent fails silently

### ISSUE THREAD

**Issue by jeroenj** [DataDog/datadog-agent#4271]
**Output of the info page (if this is a bug)**
```
Getting the status from the agent.
==============================
Datadog Cluster Agent (v1.3.2)
==============================

  Status date: 2019-10-09 12:01:51.753304 UTC
  Agent start:
  Pid: 1
  Check Runners: 4
  Log Level: debug

  Paths
  =====
    Config File: /etc/datadog-agent/datadog-cluster.yaml
    conf.d: /etc/datadog-agent/conf.d

  Clocks
  ======
    System UTC time: 2019-10-09 12:01:51.753304 UTC

  Hostnames
  =========
    host_aliases: [gke-production-002-support-1-b5b5e1bf-vzjp.prod-b9a0058f]
    hostname: gke-production-002-support-1-b5b5e1bf-vzjp.c.prod-b9a0058f.internal
    socket-fqdn: datadog-cluster-agent-697975d54f-k2jhq
    socket-hostname: datadog-cluster-agent-697975d54f-k2jhq
    hostname provider: gce
    unused hostname providers:
      configuration/environment: hostname is empty

  Leader Election
  ===============
    Leader Election Status:  Running
    Leader Name is: datadog-cluster-agent-697975d54f-k2jhq
    Last Acquisition of the lease: Tue, 08 Oct 2019 10:09:31 UTC
    Renewed leadership: Wed, 09 Oct 2019 12:01:38 UTC
    Number of leader transitions: 20 transitions

  Custom Metrics Server
  =====================
    ConfigMap name: monitoring/datadog-custom-metrics

    External Metrics
    ----------------
      Total: 15
      Valid: 0
      hpa:
      - name: ledger-import
      - namespace: production-001
      - uid: 256a3c7b-86ac-11e9-afff-42010a84011b
      labels:
      - env: production-001
      metricName: sf.production.sidekiq.queues.ledger_import.enqueued
      ts: 1.570622487e&#43;09
      valid: false
      value: 0
      hpa:
      - name: webhooks
      - namespace: production-001
      - uid: 25dbd67d-86ac-11e9-afff-42010a84011b
      labels:
      - env: production-001
      metricName: sf.production.sidekiq.queues.webhooks.enqueued
      ts: 1.570622487e&#43;09
      valid: false
      value: 0
      hpa:
      - name: background-syncing
      - namespace: production-001
      - uid: 250e7a84-86ac-11e9-afff-42010a84011b
      labels:
      - env: production-001
      metricName: sf.production.sidekiq.queues.background_syncing.enqueued
      ts: 1.570622487e&#43;09
      valid: false
      value: 0
      hpa:
      - name: exports
      - namespace: production-001
      - uid: 25464c55-86ac-11e9-afff-42010a84011b
      labels:
      - env: production-001
      metricName: sf.production.sidekiq.queues.exports.enqueued
      ts: 1.570622487e&#43;09
      valid: false
      value: 0
      hpa:
      - name: low-priority
      - namespace: production-001
      - uid: 25901b8f-86ac-11e9-afff-42010a84011b
      labels:
      - env: production-001
      metricName: sf.production.sidekiq.queues.low_priority.enqueued
      ts: 1.570622487e&#43;09
      valid: false
      value: 0
      hpa:
      - name: documents
      - namespace: production-001
      - uid: 25346870-86ac-11e9-afff-42010a84011b
      labels:
      - env: production-001
      metricName: sf.production.sidekiq.queues.documents.enqueued
      ts: 1.570622487e&#43;09
      valid: false
      value: 0
      hpa:
      - name: high-memory
      - namespace: production-001
      - uid: 2f85cbab-ea79-11e9-8661-42010a840fca
      labels:
      - env: production-001
      metricName: sf.production.sidekiq.queues.high-memory.enqueued
      ts: 1.570622487e&#43;09
      valid: false
      value: 0
      hpa:
      - name: insights
      - namespace: production-001
      - uid: 2c0e47a9-e9be-11e9-8661-42010a840fca
      labels:
      - env: production-001
      metricName: sf.production.sidekiq.queues.insights.enqueued
      ts: 1.570622487e&#43;09
      valid: false
      value: 0
      hpa:
      - name: manual-upload
      - namespace: production-001
      - uid: 25b5a103-86ac-11e9-afff-42010a84011b
      labels:
      - env: production-001
      metricName: sf.production.sidekiq.queues.manual_upload.enqueued
      ts: 1.570622487e&#43;09
      valid: false
      value: 0
      hpa:
      - name: default
      - namespace: production-001
      - uid: 2521ffbe-86ac-11e9-afff-42010a84011b
      labels:
      - env: production-001
      metricName: sf.production.sidekiq.queues.default.enqueued
      ts: 1.570622487e&#43;09
      valid: false
      value: 0
      hpa:
      - name: high-memory
      - namespace: production-001
      - uid: 2f85cbab-ea79-11e9-8661-42010a840fca
      labels:
      - env: production-001
      metricName: sf.production.sidekiq.queues.higg_memory.enqueued
      ts: 1.570622487e&#43;09
      valid: false
      value: 0
      hpa:
      - name: high-priority
      - namespace: production-001
      - uid: 2558aacc-86ac-11e9-afff-42010a84011b
      labels:
      - env: production-001
      metricName: sf.production.sidekiq.queues.high_priority.enqueued
      ts: 1.570622487e&#43;09
      valid: false
      value: 0
      hpa:
      - name: low-documents
      - namespace: production-001
      - uid: 257c2f67-86ac-11e9-afff-42010a84011b
      labels:
      - env: production-001
      metricName: sf.production.sidekiq.queues.low_documents.enqueued
      ts: 1.570622487e&#43;09
      valid: false
      value: 0
      hpa:
      - name: syncing
      - namespace: production-001
      - uid: 108f5979-cf14-11e9-8661-42010a840fca
      labels:
      - env: production-001
      metricName: sf.production.sidekiq.queues.syncing.enqueued
      ts: 1.570622487e&#43;09
      valid: false
      value: 0
      hpa:
      - name: zips
      - namespace: production-001
      - uid: 25eec777-86ac-11e9-afff-42010a84011b
      labels:
      - env: production-001
      metricName: sf.production.sidekiq.queues.zips.enqueued
      ts: 1.570622487e&#43;09
      valid: false
      value: 0

=========
Collector
=========

  Running Checks
  ==============

    kubernetes_apiserver
    --------------------
      Instance ID: kubernetes_apiserver [OK]
      Total Runs: 6,214
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 154, Total: 47,830
      Service Checks: Last Run: 4, Total: 24,836
      Average Execution Time : 1.122s

=========
Forwarder
=========

  Transactions
  ============
    CheckRunsV1: 6,213
    Dropped: 0
    DroppedOnInput: 0
    Events: 0
    HostMetadata: 0
    IntakeV1: 2,804
    Metadata: 0
    Requeued: 0
    Retried: 0
    RetryQueueSize: 0
    Series: 0
    ServiceChecks: 0
    SketchSeries: 0
    Success: 15,230
    TimeseriesV1: 6,213

  API Keys status
  ===============
    API key ending with 0222d: API Key valid

==========
Endpoints
==========
  https://app.datadoghq.com - API Key ending with:
      - 0222d
```

**Describe what happened:**

We are using Kubernetes `HorizontalPodAutoscaler`s with external metrics from Datadog (for Rails Sidekiq workers). Below is an example of one of the HPAs:

```yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: zips
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zips
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: External
    external:
      metricName: sf.production.sidekiq.queues.zips.enqueued
      targetValue: 2
      metricSelector:
        matchLabels:
          env: production-001
```

As you can see the metric name used is `sf.production.sidekiq.queues.zips.enqueued`. For one of the new workers the metric name was (incorrectly) set to `sf.production.sidekiq.queues.high-priority.enqueued` (this should have been `sf.production.sidekiq.queues.high_priority.enqueued` (`_` vs. `-`) as dashes are [not allowed](https://docs.datadoghq.com/developers/metrics/#naming-metrics) and also didn't exist (since we were correctly pushing metrics to `high_priority`.

When the HPA with the invalid metric name (`high-priority`) was added metrics for all HPA's started to fail (reporting `<unknown>` in the targets). Initially we thought this was the same issue as https://github.com/DataDog/datadog-agent/issues/2996 as it only occurred when adding the new HPA. However after further investigation we found out that the metric name was incorrect.

However, we at least expected to get some details about this in the debug logging of the cluster agent but it didn't:

```
# this is when the correct key was used
datadog-cluster-agent-697975d54f-twn9k datadog-cluster-agent 2019-10-09 10:17:19 UTC | CLUSTER | DEBUG | (pkg/clusteragent/custommetrics/provider.go:191 in GetExternalMetric) | External metrics returned: []external_metrics.ExternalMetricValue{external_metrics.ExternalMetricValue{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, MetricName:"sf.production.sidekiq.queues.zips.enqueued", MetricLabels:map[string]string{"env":"production-001"}, Timestamp:v1.Time{Time:time.Time{wall:0xbf5f8acbc7b5f9d8, ext:14583397549442, loc:(*time.Location)(0x2ea6b00)}}, WindowSeconds:(*int64)(nil), Value:resource.Quantity{i:resource.int64Amount{value:0, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"0", Format:"DecimalSI"}}}
datadog-cluster-agent-697975d54f-p79vc datadog-cluster-agent 2019-10-09 10:17:49 UTC | CLUSTER | DEBUG | (pkg/clusteragent/custommetrics/provider.go:191 in GetExternalMetric) | External metrics returned: []external_metrics.ExternalMetricValue{external_metrics.ExternalMetricValue{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, MetricName:"sf.production.sidekiq.queues.high_memory.enqueued", MetricLabels:map[string]string{"env":"production-001"}, Timestamp:v1.Time{Time:time.Time{wall:0xbf5f8ad34a4039fe, ext:86964793111826, loc:(*time.Location)(0x2ea6b00)}}, WindowSeconds:(*int64)(nil), Value:resource.Quantity{i:resource.int64Amount{value:1, scale:0}, d:resource.infDecAmount{Dec:(*inf.Dec)(nil)}, s:"1", Format:"DecimalSI"}}}

# this happened for all HPAs as soon as the incorrect key is used
datadog-cluster-agent-697975d54f-k2jhq datadog-cluster-agent 2019-10-09 10:18:49 UTC | CLUSTER | DEBUG | (pkg/clusteragent/custommetrics/provider.go:191 in GetExternalMetric) | External metrics returned: []external_metrics.ExternalMetricValue{}
```

**Describe what you expected:**

We expected some kind of error to be generated in these `GetExternalMetric` log lines. It's fine that it's swallowed _silently_ but it would have helped us a lot figuring out the issue if the (debug) logs at least showed some sign of something being invalid. This is also why we initially thought it was related to https://github.com/DataDog/datadog-agent/issues/2996 but according to https://github.com/DataDog/datadog-agent/issues/2996#issuecomment-467495475 it's because Datadog is returning errors with a HTTP 200 status code. I haven't digged deeper yet but I expect this to be the same issue.

**Steps to reproduce the issue:**

Set up a HPA which uses Datadog metrics but use an invalid metric name by e.g. including a dash in the name. (e.g. `foo.bar.foo-bar`)

**Additional environment details (Operating System, Cloud provider, etc):**

We're using GKE (v1.13.6-gke.13) on Google Cloud.
