### ISSUE TITLE
datadog-agent is randomly dying on startup

### ISSUE THREAD

**Issue by arodioukov** [DataDog/datadog-agent#4284]
**Output of the info page (if this is a bug)**
```
(Paste the output of the info page here)
```

**Describe what happened:**
Since upgrading to 6.14.1, datadog-agent sporadically fails to start. We run datadog-agent as a sidecar alongside a bunch of other containers in AWS Beanstalk multicontainer configuration. We use `datadog/agent:latest` image. I'm attaching a log from one of the recent failed launches. 

```
$ docker images | grep datadog
datadog/agent                                                            latest                  b96c197cac5c        2 weeks ago         404MB
```

Relevant bits from the log appear to be the following:
```
panic: assignment to entry in nil map

goroutine 102 [running]:
github.com/DataDog/datadog-agent/pkg/autodiscovery/providers.(*DockerConfigProvider).listen(0xc00086c4b0)
        /.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/autodiscovery/providers/docker.go:114 +0x3d0
created by github.com/DataDog/datadog-agent/pkg/autodiscovery/providers.(*DockerConfigProvider).Collect
        /.omnibus/src/datadog-agent/src/github.com/DataDog/datadog-agent/pkg/autodiscovery/providers/docker.go:60 +0x1b5
AGENT EXITED WITH CODE 2, SIGNAL 0, KILLING CONTAINER
2019-10-10 20:39:00 UTC | PROCESS | CRITICAL | (pkg/process/util/signal_nowindows.go:21 in HandleSignals) | Caught signal 'terminated'; terminating.
```

**Describe what you expected:**
Agent running.

**Steps to reproduce the issue:**
New deployment, restarting containers, etc. Note that as described above, the agent container randomly fails to start. Once the agent is running, it seems to continue running.

**Additional environment details (Operating System, Cloud provider, etc):**
Relevant bits from Dockerrun.aws.json:
```
  "volumes": [
    {
      "name": "cgroup",
      "host": {
        "sourcePath": "/cgroup/"
      }
    },
    {
      "name": "datadog_checks",
      "host": {
        "sourcePath": "/etc/datadog-agent/checks.d/"
      }
    },
    {
      "name": "datadog_conf",
      "host": {
        "sourcePath": "/etc/datadog-agent/conf.d/"
      }
    },
    {
      "name": "datadog_run",
      "host": {
        "sourcePath": "/opt/datadog-agent/run/"
      }
    },
    {
      "name": "datadog_yaml",
      "host": {
        "sourcePath": "/etc/datadog-agent/datadog.yaml"
      }
    },
    {
      "name": "docker_sock",
      "host": {
        "sourcePath": "/var/run/docker.sock"
      }
    },
    {
      "name": "proc",
      "host": {
        "sourcePath": "/proc/"
      }
    },
  ],
...
 "containerDefinitions": [
    {
      "name": "datadog-agent",
      "image": "datadog/agent:latest",
      "memory": 256,
      "mountPoints": [
        {
          "sourceVolume": "cgroup",
          "containerPath": "/host/sys/fs/cgroup",
          "readOnly": true
        },
        {
          "sourceVolume": "datadog_checks",
          "containerPath": "/checks.d",
          "readOnly": true
        },
        {
          "sourceVolume": "datadog_conf",
          "containerPath": "/config.d",
          "readOnly": true
        },
        {
          "sourceVolume": "datadog_run",
          "containerPath": "/opt/datadog-agent/run",
          "readOnly": false
        },
        {
          "sourceVolume": "datadog_yaml",
          "containerPath": "/etc/datadog-agent/datadog.yaml",
          "readOnly": true
        },
        {
          "sourceVolume": "docker_sock",
          "containerPath": "/var/run/docker.sock",
          "readOnly": false
        },
        {
          "sourceVolume": "proc",
          "containerPath": "/host/proc",
          "readOnly": true
        }
      ]
    }
  ]
```
datadog.yaml:
```
---
hostname: some-hostname
listeners:
  - name: docker
config_providers:
  - name: docker
    polling: true
ac_include: []
ac_exclude: ["name:ecs-agent", "image:datadog/agent"]
apm_config:
  enabled: true
  apm_non_local_traffic: true
dogstatsd_non_local_traffic: true
jmx_use_cgroup_memory_limit: true
logs_enabled: true
logs_config:
  container_collect_all: true
process_config:
  enabled: true
docker_env_as_tags:
  ENVIRONMENT_NAME: env
  OUTPACE_STAGE: outpace.stage
  OUTPACE_CLIENT: outpace.client
  OUTPACE_STACK: outpace.stack
docker_labels_as_tags:
  com.outpace.service.name: outpace.service
```

```
$ uname -a
Linux some-hostname 4.14.62-65.117.amzn1.x86_64 #1 SMP Fri Aug 10 20:03:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
[datadog-dead.log](https://github.com/DataDog/datadog-agent/files/3714648/datadog-dead.log)
