### ISSUE TITLE
Datadog Cluster Agent: Doesn't validate if metric is valid.

### ISSUE THREAD

**Issue by uthark** [DataDog/datadog-agent#5282]
**Describe what happened:**
If HPA is configured incorrectly, then all HPAs that use external metrics from datadog are broken.

Example: if HPA is invalid:
```
  - external:
      metric:
        name: truth_service.http_requests_total
        selector:
          matchLabels:
            kube_cluster: '"pod19"' # <- our tooling inserted extra quotes.
            kube_project: truth-service
```

Resulting request contained 

`avg:truth_service.http_requests_total{kube_cluster:"pod19",kube_project:truth-service}.rollup(30)`
among other HPA. The whole request failed.

**Describe what you expected:**
Only HPA that has incorrect metrics configuration should fail.

**Steps to reproduce the issue:**
1. Create HPA that uses valid metric value.
1. Create HPA that uses invalid metric value.

MEtrics for HPA with valid metric will not be retrieved.

**Additional environment details (Operating System, Cloud provider, etc):**

Either client should validate before submitting or server should ignore bad metrics and return results for good metrics.

Logs from DCA:
```
datadog-cluster-agent-7b749f864f-dgl6w datadog-cluster-agent 2020-04-05 00:49:46 UTC | CLUSTER | ERROR | (pkg/util/kubernetes/autoscalers/datadogexternal.go:84 in queryDatadogExternal) | Error while executing metric query XXX: : API returned error: Error parsing query:
```
