### ISSUE TITLE
[Feature Request] allow metrics expressions in the metricsProvider

### ISSUE THREAD

**Issue by aleixrm-scopely** [DataDog/datadog-agent#5748]
We are interested in use datadog complex metrics expressions in the HPA in order to base our scale target in metrics arithmetics, something like this HPA metrics configuration example:

```
[...]
metrics:
    - type: External
      external:
        metricName: >-
          ewma_10((max:docker.cpu.usage{account:staging,kube_container_name:app,kube_service:serviceX}|max:kubernetes.cpu.requests{account:staging,kube_container_name:app,kube_service:serviceX}))
        targetValue: 80
```
that will base the scale on the ratio between the cpu usage and the requested cpu. 

It is possible to query expressions like that (that are available through the API) into the metricsProvider? If not it would be a great feature to implement.

We're currently using a custom metrics provider that queries the datadog API and serves those metrics queries as an external metrics provider for the HPA, but we're interested on using the official datadog-agent for doing that. If you think that this feature is interesting to implement in the agent, we will gladly adapt our code into the datadog-agent.
