### ISSUE TITLE
[cluster-agent] AWS metrics don't appear in external.metrics.k8s.io

### ISSUE THREAD

**Issue by luizavladislavna** [DataDog/datadog-agent#5783]
<!--
If you suspect your issue is a bug, please attach the output of the Agent status page,
see https://docs.datadoghq.com/agent/faq/agent-commands/#agent-information
-->

**Output of the info page (if this is a bug)**
```
root@datadog-cluster-agent-8cf67b9d9-9hbr7:/# datadog-cluster-agent status
Getting the status from the agent.
==============================
Datadog Cluster Agent (v1.5.2)
==============================

  Status date: 2020-06-19 20:58:46.278981 UTC
  Agent start: 
  Pid: 1
  Go Version: 
  Build arch: 
  Check Runners: 4
  Log Level: info

  Paths
  =====
    Config File: /etc/datadog-agent/datadog-cluster.yaml
    conf.d: /etc/datadog-agent/conf.d

  Clocks
  ======
    System UTC time: 2020-06-19 20:58:46.278981 UTC

  Hostnames
  =========
    ec2-hostname: ip-192-168-61-61.ec2.internal
    hostname: i-0b18c398ce11dca49
    instance-id: i-0b18c398ce11dca49
    socket-fqdn: datadog-cluster-agent-8cf67b9d9-9hbr7
    socket-hostname: datadog-cluster-agent-8cf67b9d9-9hbr7
    hostname provider: aws
    unused hostname providers:
      configuration/environment: hostname is empty
      gce: unable to retrieve hostname from GCE: status code 404 trying to GET http://169.254.169.254/computeMetadata/v1/instance/hostname

  Metadata
  ========

Leader Election
===============
  Leader Election Status:  Running
  Leader Name is: datadog-cluster-agent-8cf67b9d9-9hbr7
  Last Acquisition of the lease: Fri, 05 Jun 2020 17:04:20 UTC
  Renewed leadership: Fri, 19 Jun 2020 20:58:42 UTC
  Number of leader transitions: 37 transitions
 Custom Metrics Server
 =====================
   ConfigMap name: devops/datadog-custom-metrics
   
   External Metrics
   ----------------
     Total: 1
     Valid: 0
     
   * horizontal pod autoscaler: devops/devops-demo-hpa-aws-applicationelb
     Metric name: aws.applicationelb.request_count
     Labels:
     - env: pcn-qa3
     Value: 3.7142857142857144
     Timestamp: 2020-06-19 20:58:27.000000 UTC
     Valid: false

=========
Collector
=========

  Running Checks
  ==============
    
    kubernetes_apiserver
    --------------------
      Instance ID: kubernetes_apiserver [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/kubernetes_apiserver.d/conf.yaml.default
      Total Runs: 81,584
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 19,480
      Service Checks: Last Run: 4, Total: 326,312
      Average Execution Time : 2.202s
      
=========
Forwarder
=========

  Transactions
  ============
    CheckRunsV1: 81,583
    Dropped: 0
    DroppedOnInput: 0
    Events: 0
    HostMetadata: 0
    IntakeV1: 14,507
    Metadata: 0
    Requeued: 0
    Retried: 0
    RetryQueueSize: 0
    Series: 0
    ServiceChecks: 0
    SketchSeries: 0
    Success: 177,673
    TimeseriesV1: 81,583

  API Keys status
  ===============
    API key ending with 13814: API Key valid

==========
Endpoints
==========
  https://app.datadoghq.com - API Key ending with:
      - 13814

```

**Describe what happened:**
We have an HPA created with target as AWS-ApplicationLoadBalancer metric.
Unfortunately, it does not work. As you can see above 'Valid: false'.
```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: devops-demo-hpa-aws-applicationelb
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devops-demo
  metrics:
    - type: External
      external:
        metricName: aws.applicationelb.request_count
        metricSelector:
          matchLabels:
            env: pcn-qa3
        targetAverageValue: 10
```
But it works with other metrics, that produced with code inside the cluster. F.e. `gunicorn.requests` metric (https://docs.datadoghq.com/integrations/gunicorn/) 

**Describe what you expected:**
Enabled autoscaling with external metrics from AWS

**Steps to reproduce the issue:**
- Cluster Agent configured according to the existed documentation
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog-cluster-agent
  namespace: devops
spec:
  selector:
    matchLabels:
      app: datadog-cluster-agent
  template:
    metadata:
      labels:
        app: datadog-cluster-agent
      name: datadog-cluster-agent
      annotations:
        ad.datadoghq.com/datadog-cluster-agent.check_names: '["prometheus"]'
        ad.datadoghq.com/datadog-cluster-agent.init_configs: '[{}]'
        ad.datadoghq.com/datadog-cluster-agent.instances: '[{"prometheus_url": "http://%%host%%:5000/metrics","namespace": "datadog.cluster_agent","metrics": ["go_goroutines","go_memstats_*","process_*","api_requests","datadog_requests","external_metrics", "cluster_checks_*"]}]'
    spec:
      serviceAccountName: datadog-cluster-agent
      containers:
      - image: datadog/cluster-agent:1.5.2
        name: datadog-cluster-agent
        imagePullPolicy: Always
        ports:
          - containerPort: 5005
            name: agentport
            protocol: TCP
          - containerPort: 8127
            name: metricsapi
            protocol: TCP
        env:
          - name: DD_API_KEY
            value: <DD_API_KEY>
          - name: DD_APP_KEY
            value: <DD_APP_KEY>
          - name: DD_COLLECT_KUBERNETES_EVENTS
            value: "true"
          - name: DD_LEADER_ELECTION
            value: "true"
          - name: DD_CLUSTER_AGENT_AUTH_TOKEN
            value: "<THIRTY_2_CHARACTERS_LONG_TOKEN>"
          - name: DD_EXTERNAL_METRICS_PROVIDER_ENABLED
            value: 'true'
          - name: DD_EXTERNAL_METRICS_PROVIDER_PORT
            value: "8127"
```
- Cluster Agent flare case id #364155
```
root@datadog-cluster-agent-8cf67b9d9-9hbr7:/# datadog-cluster-agent flare
Please enter your email: 
devops@anyclip.com
Asking the Cluster Agent to build the flare archive.
/tmp/datadog-agent-2020-06-19-20-51-39.zip is going to be uploaded to Datadog
Are you sure you want to upload a flare? [Y/N]
Y
Your logs were successfully uploaded. For future reference, your internal case id is 364155
```


===========================================================================
UPDATE:
- HPA status "unable to get external metric "
```
~ k describe hpa                                                                                                                                                                                                                            [k8-devops.k8s.local|devops]
Name:               devops-demo-hpa-aws-applicationelb
Namespace:          devops
Labels:             <none>
Annotations:        autoscaling.alpha.kubernetes.io/conditions:
                      [{"type":"AbleToScale","status":"True","lastTransitionTime":"2020-06-19T20:44:11Z","reason":"SucceededGetScale","message":"the HPA control...
                    autoscaling.alpha.kubernetes.io/metrics:
                      [{"type":"External","external":{"metricName":"aws.applicationelb.request_count","metricSelector":{"matchLabels":{"env":"pcn-qa3"}},"target...
                    kubectl.kubernetes.io/last-applied-configuration:
                      {"apiVersion":"autoscaling/v2beta1","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"name":"devops-demo-hpa-aws-applicatione...
CreationTimestamp:  Fri, 19 Jun 2020 23:43:41 +0300
Reference:          Deployment/devops-demo
Min replicas:       1
Max replicas:       3
Deployment pods:    1 current / 0 desired
Events:
  Type     Reason                        Age                   From                       Message
  ----     ------                        ----                  ----                       -------
  Warning  FailedComputeMetricsReplicas  31m (x13 over 37m)    horizontal-pod-autoscaler  failed to get aws.applicationelb.request_count external metric: unable to get external metric devops/aws.applicationelb.request_count/&LabelSelector{MatchLabels:map[string]string{env: pcn-qa3,},MatchExpressions:[],}: no metrics returned from external metrics API
  Warning  FailedGetExternalMetric       2m38s (x71 over 37m)  horizontal-pod-autoscaler  unable to get external metric devops/aws.applicationelb.request_count/&LabelSelector{MatchLabels:map[string]string{env: pcn-qa3,},MatchExpressions:[],}: no metrics returned from external metrics API
```

- cluster-agent status above show us that "Value" exist but "Valid:false"
```
     Value: 3.7142857142857144
     Timestamp: 2020-06-19 20:58:27.000000 UTC
     Valid: false
```

- external.metrics.k8s.io/ API response
```
~ k get --raw "/apis/external.metrics.k8s.io/v1beta1" | jq .                                                                                                                                                                                [k8-devops.k8s.local|devops]
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "external.metrics.k8s.io/v1beta1",
  "resources": []
}
~ 
```
