### ISSUE TITLE
datadog agent consul autodiscovery integration config with acl token

### ISSUE THREAD

**Issue by fizzamahdi** [DataDog/datadog-agent#5877]
**Describe what happened:**
Datadog agent consul check returns 403 forbidden, even when ACL token is set in autodiscovery integration config. I've exec'd into the datadog agent container and manually run a curl command with the token header set and it is able to authenticate to Consul so I know the token has the necessary permissions.

**Describe what you expected:**
datadog agent would be able to authenticate to consul using acl token provided in autodiscovery integration config

**Steps to reproduce the issue:**

- Deploy Consul agents (clients and server) to k8s cluster
- Deploy datadog agent to k8s cluster
- Add annotations to spec.template.metadata of Consul server statefulset and Consul client daemonset:
```yaml
  annotations:
    ad.datadoghq.com/consul.check_names: '["consul"]'
    ad.datadoghq.com/consul.init_configs: '[{}]'
    ad.datadoghq.com/consul.instances: '[{"url": "http://%%host%%:8500","acl_token": "<my_super_permissive_bootstrap_token>"}]'
```
- after consul pods have restarted, restart the datadog agent pods

**Additional environment details (Operating System, Cloud provider, etc):**

-  running all containers on AWS EKS
-  Consul is setup to use ACLs
-  tested using the bootstrap ACL token for datadog agent to authenticate since that token has access to everything

I could be missing something in my configuration, but didn't see anything specific in the docs. I saw this snippet in the example configuration file (etc/datadog-agent/conf.d/consul.d/conf.yaml.example) in the datadog agent and decided to set the ACL token because of that:

```
    ## @param acl_token - string - optional
    ## ACL token to use for authentication.
    #
    # acl_token: '<TOKEN>'
```

Another team manages the datadog agent in our clusters, so I told them another option for us is to configure consul to push data to the agent through DogStatsD instead of using datadog's autodiscovery, but before going that route I would like to figure out how to get the autodiscovery to work with ACLs.

Thank you in advance for any help!
