### ISSUE TITLE
Docker agent conflict with existing Redis container

### ISSUE THREAD

**Issue by edno** [DataDog/datadog-agent#5978]
Datadog docker agent failed to start when included in a `docker-compose.yml` that contains a `redis` container.

**Output of the info page (if this is a bug)**
```
datadog            | 2020-07-16 15:54:35 UTC | CORE | ERROR | (pkg/collector/runner/runner.go:292 in work) | Error running check redisdb: [{"message": "Timeout connecting to server", "traceback": "Traceback (most recent call last):\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/connection.py\", line 539, in connect\n    sock = self._connect()\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/connection.py\", line 596, in _connect\n    raise err\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/connection.py\", line 584, in _connect\n    sock.connect(socket_address)\nsocket.timeout: timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py\", line 822, in run\n    self.check(instance)\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/redisdb/redisdb.py\", line 495, in check\n    self._check_db()\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/redisdb/redisdb.py\", line 194, in _check_db\n    info = conn.info()\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/client.py\", line 1036, in info\n    return self.execute_command('INFO')\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/client.py\", line 836, in execute_command\n    conn = self.connection or pool.get_connection(command_name, **options)\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/connection.py\", line 1073, in get_connection\n    connection.connect()\n  File \"/opt/datadog-agent/embedded/lib/python3.8/site-packages/redis/connection.py\", line 541, in connect\n    raise TimeoutError(\"Timeout connecting to server\")\nredis.exceptions.TimeoutError: Timeout connecting to server\n"}]
```

**Describe what happened:**
Datadog docker agent failed to start when included in a `docker-compose.yml` that contains a `redis` container.

**Describe what you expected:**
Datadog docker agent should use its internal Redis db, and not try to connect to other Redis db.

**Steps to reproduce the issue:**
Create a `docker-compose.yml` with following definition:
```yaml
version: "3.7"

services:
  datadog:
    image: datadog/agent:latest
    ports:
      - "8125:8125/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
      - DD_SITE=${DD_SITE}
      - DD_API_KEY=${DD_API_KEY}
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=1
    container_name: datadog

  redis:
    image: bitnami/redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redis_password
    volumes:
      - /tmp/redis:/bitnami/redis/data
````

Start the containers with `docker-compose up`
