### ISSUE TITLE
kubelet python collector failed on Windows node pool on AKS

### ISSUE THREAD

**Issue by JiandongRuan** [DataDog/datadog-agent#6027]
**Output of the info page (if this is a bug)**
```
Getting the status from the agent.

===============
Agent (v7.20.2)
===============

  Status date: 2020-07-22 01:41:35.568093 GMT
  Agent start: 2020-07-22 00:16:01.191078 GMT
  Pid: 12328
  Go Version: go1.13.8
  Python Version: 3.8.1
  Build arch: amd64
  Check Runners: 4
  Log Level: info

  Paths
  =====
    Config File: C:\ProgramData\Datadog\datadog.yaml
    conf.d: C:\ProgramData\Datadog\conf.d
    checks.d: C:\ProgramData\Datadog\checks.d

  Clocks
  ======
    NTP offset: 1.455ms
    System UTC time: 2020-07-22 01:41:35.568093 GMT

  Host Info
  =========
    bootTime: 2020-07-13 18:32:24.000000 GMT
    os: windows
    platform: Windows Server 2019 Datacenter
    platformFamily: Windows Server 2019 Datacenter
    platformVersion: 10.0 Build 17763
    procs: 22
    uptime: 197h44m15s

  Hostnames
  =========
    host_aliases: [87702f81-e4ad-4039-a239-ab54c57623a2 akswin000004]
    hostname: akswin000004
    socket-fqdn: datadog-win-agent-2c4sd
    socket-hostname: datadog-win-agent-2c4sd
    host tags:
      kube_node_role:agent
    hostname provider: container
    unused hostname providers:
      aws: not retrieving hostname from AWS: the host is not an ECS instance and other providers already retrieve non-default hostnames
      configuration/environment: hostname is empty
      gce: unable to retrieve hostname from GCE: status code 404 trying to GET http://169.254.169.254/computeMetadata/v1/instance/hostname

  Metadata
  ========
    cloud_provider: Azure
    hostname_source: container

=========
Collector
=========

  Running Checks
  ==============

    cpu
    ---
      Instance ID: cpu [OK]
      Configuration Source: file:C:\ProgramData\Datadog\conf.d\cpu.d\conf.yaml.default
      Total Runs: 340
      Metric Samples: Last Run: 7, Total: 2,374
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 0, Total: 0
      Average Execution Time : 0s
      Last Execution Date : 2020-07-22 01:41:33.000000 GMT
      Last Successful Execution Date : 2020-07-22 01:41:33.000000 GMT


    docker
    ------
      Instance ID: docker [OK]
      Configuration Source: file:C:\ProgramData\Datadog\conf.d\docker.d\conf.yaml.default
      Total Runs: 113
      Metric Samples: Last Run: 286, Total: 35,954
      Events: Last Run: 0, Total: 10
      Service Checks: Last Run: 1, Total: 113
      Average Execution Time : 33.481s
      Last Execution Date : 2020-07-22 01:40:56.000000 GMT
      Last Successful Execution Date : 2020-07-22 01:40:56.000000 GMT


    kubelet (4.1.0)
    ---------------
      Instance ID: kubelet:d884b5186b651429 [ERROR]
      Configuration Source: file:C:\ProgramData\Datadog\conf.d\kubelet.d\conf.yaml.default
      Total Runs: 169
      Metric Samples: Last Run: 45, Total: 8,076
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 4, Total: 676
      Average Execution Time : 19.896s
      Last Execution Date : 2020-07-22 01:41:22.000000 GMT
      Last Successful Execution Date : Never
      Error: HTTPSConnectionPool(host='10.144.1.155', port=10250): Read timed out. (read timeout=10.0)
      Traceback (most recent call last):
        File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\site-packages\urllib3\connectionpool.py", line 426, in _make_request
          six.raise_from(e, None)
        File "<string>", line 3, in raise_from
        File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\site-packages\urllib3\connectionpool.py", line 421, in _make_request
          httplib_response = conn.getresponse()
        File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\http\client.py", line 1322, in getresponse
          response.begin()
        File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\http\client.py", line 303, in begin
          version, status, reason = self._read_status()
        File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\http\client.py", line 264, in _read_status
          line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
        File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\socket.py", line 669, in readinto
          return self._sock.recv_into(b)
        File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\ssl.py", line 1241, in recv_into
          return self.read(nbytes, buffer)
        File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\ssl.py", line 1099, in read
          return self._sslobj.read(len, buffer)
      socket.timeout: The read operation timed out

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\site-packages\requests\adapters.py", line 439, in send
          resp = conn.urlopen(
        File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\site-packages\urllib3\connectionpool.py", line 724, in urlopen
          retries = retries.increment(
        File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\site-packages\urllib3\util\retry.py", line 403, in increment
          raise six.reraise(type(error), error, _stacktrace)
        File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\site-packages\urllib3\packages\six.py", line 735, in reraise
          raise value
        File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
          httplib_response = self._make_request(
        File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\site-packages\urllib3\connectionpool.py", line 428, in _make_request
          self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
        File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\site-packages\urllib3\connectionpool.py", line 335, in _raise_timeout
          raise ReadTimeoutError(
      urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='10.144.1.155', port=10250): Read timed out. (read timeout=10.0)

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\site-packages\datadog_checks\base\checks\base.py", line 822, in run
          self.check(instance)
        File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\site-packages\datadog_checks\kubelet\kubelet.py", line 359, in check
          self.process(self.kubelet_scraper_config, metric_transformers=self.transformers)
        File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\site-packages\datadog_checks\base\checks\openmetrics\mixins.py", line 480, in proce
ss
          for metric in self.scrape_metrics(scraper_config):
        File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\site-packages\datadog_checks\base\checks\openmetrics\mixins.py", line 420, in scrap
e_metrics
          response = self.poll(scraper_config)
        File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\site-packages\datadog_checks\base\checks\openmetrics\mixins.py", line 681, in poll
          response = self.send_request(endpoint, scraper_config, headers)
        File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\site-packages\datadog_checks\base\checks\openmetrics\mixins.py", line 707, in send_
request
          return http_handler.get(endpoint, stream=True, **kwargs)
        File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\site-packages\datadog_checks\base\utils\http.py", line 283, in get
          return self._request('get', url, options)
        File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\site-packages\datadog_checks\base\utils\http.py", line 325, in _request
          return getattr(requests, method)(url, **new_options)
        File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\site-packages\requests\api.py", line 75, in get
          return request('get', url, params=params, **kwargs)
        File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\site-packages\requests\api.py", line 60, in request
          return session.request(method=method, url=url, **kwargs)
        File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\site-packages\requests\sessions.py", line 533, in request
          resp = self.send(prep, **send_kwargs)
        File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\site-packages\requests\sessions.py", line 646, in send
          r = adapter.send(request, **kwargs)
        File "C:\Program Files\Datadog\Datadog Agent\embedded3\lib\site-packages\requests\adapters.py", line 529, in send
          raise ReadTimeout(e, request=request)
      requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='10.144.1.155', port=10250): Read timed out. (read timeout=10.0)


   memory
   ------
     Instance ID: memory [OK]
     Configuration Source: file:C:\ProgramData\Datadog\conf.d\memory.d\conf.yaml.default
     Total Runs: 339
     Metric Samples: Last Run: 17, Total: 5,763
     Events: Last Run: 0, Total: 0
     Service Checks: Last Run: 0, Total: 0
     Average Execution Time : 0s
     Last Execution Date : 2020-07-22 01:41:24.000000 GMT
     Last Successful Execution Date : 2020-07-22 01:41:24.000000 GMT


   ntp
   ---
     Instance ID: ntp:d884b5186b651429 [OK]
     Configuration Source: file:C:\ProgramData\Datadog\conf.d\ntp.d\conf.yaml.default
     Total Runs: 6
     Metric Samples: Last Run: 1, Total: 6
     Events: Last Run: 0, Total: 0
     Service Checks: Last Run: 1, Total: 6
     Average Execution Time : 1.172s
     Last Execution Date : 2020-07-22 01:31:48.000000 GMT
     Last Successful Execution Date : 2020-07-22 01:31:48.000000 GMT


   openmetrics (1.7.0)
   -------------------
     Instance ID: openmetrics:myservice:440f461b729cf4a9 [OK]
     Configuration Source: kubelet:docker://cc646ed10d20ce3e42eba72be2cf7a4a7dd76c55424e7396420d1fe8b5b931cc
     Total Runs: 27
     Metric Samples: Last Run: 54, Total: 1,380
     Events: Last Run: 0, Total: 0
     Service Checks: Last Run: 1, Total: 27
     Average Execution Time : 30ms
     Last Execution Date : 2020-07-22 01:41:20.000000 GMT
     Last Successful Execution Date : 2020-07-22 01:41:20.000000 GMT

     Instance ID: openmetrics:myservice:7f321741f7ccc85a [OK]
     Configuration Source: kubelet:docker://4ec13ea9b4328495e3af3b2265de8d8d1d2e42bb6467c1cee267010698eaa5a5
     Total Runs: 31
     Metric Samples: Last Run: 51, Total: 1,581
     Events: Last Run: 0, Total: 0
     Service Checks: Last Run: 1, Total: 31
     Average Execution Time : 28ms
     Last Execution Date : 2020-07-22 01:41:28.000000 GMT
     Last Successful Execution Date : 2020-07-22 01:41:28.000000 GMT

     Instance ID: openmetrics:myservice:f989f80a4d1174cf [OK]
     Configuration Source: kubelet:docker://fbe008830e10d5662ece4181bf9b0fa5b0cd7bb58635d5b3f5bba11cc0e3d2cd
     Total Runs: 21
     Metric Samples: Last Run: 51, Total: 1,071
     Events: Last Run: 0, Total: 0
     Service Checks: Last Run: 1, Total: 21
     Average Execution Time : 27ms
     Last Execution Date : 2020-07-22 01:41:27.000000 GMT
     Last Successful Execution Date : 2020-07-22 01:41:27.000000 GMT


   uptime
   ------
     Instance ID: uptime [OK]
     Configuration Source: file:C:\ProgramData\Datadog\conf.d\uptime.d\conf.yaml.default
     Total Runs: 339
     Metric Samples: Last Run: 1, Total: 339
     Events: Last Run: 0, Total: 0
     Service Checks: Last Run: 0, Total: 0
     Average Execution Time : 0s
     Last Execution Date : 2020-07-22 01:41:31.000000 GMT
     Last Successful Execution Date : 2020-07-22 01:41:31.000000 GMT

=======
MXFetch
=======

 Initialized checks
 ==================
   no checks

 Failed checks
 =============
   no checks

========
orwarder
========

 Transactions
 ============
   CheckRunsV1: 339
   Connections: 0
   Containers: 0
   Dropped: 0
   DroppedOnInput: 0
   Events: 0
   HostMetadata: 0
   IntakeV1: 27
   Metadata: 0
   Pods: 0
   Processes: 0
   RTContainers: 0
   RTProcesses: 0
   Requeued: 0
   Retried: 0
   RetryQueueSize: 0
   Series: 0
   ServiceChecks: 0
   SketchSeries: 338
   Success: 1,043
   TimeseriesV1: 339

 API Keys status
 ===============
   API key ending with xxxxx: API Key valid

=========
ndpoints
=========
 https://app.datadoghq.com - API Key ending with:
     - xxxxx

=========
ogs Agent
=========

   Sending compressed logs in HTTPS to agent-http-intake.logs.datadoghq.com on port 443
   BytesSent: 3.8419e+06
   EncodedBytesSent: 299023
   LogsProcessed: 3572
   LogsSent: 3572

 container_collect_all
 ---------------------
   Type: docker
   Status: OK
   Inputs: 4ec13ea9b4328495e3af3b2265de8d8d1d2e42bb6467c1cee267010698eaa5a5 cd9e2f6e11283b16a4a98346ada2d8ecc67a365f20229c5fe10652a3b944a2ca fbe00883
e10d5662ece4181bf9b0fa5b0cd7bb58635d5b3f5bba11cc0e3d2cd c3d90b28be051dff7ec0680ba74b5a31b1c7c48ff30f5c73bf38363386297bcc cc646ed10d20ce3e42eba72be2cf
a4a7dd76c55424e7396420d1fe8b5b931cc 40dc0ab62740ac0acc15e5c97f18e3a19f08a411e5b6be35891de2c461d336a6 2ce09b93f553f65a5d1361f593f77c05469c5e676fbabed7
09bc7becd47b7a9

========
PM Agent
========
 Status: Not running or unreachable on localhost:8126.
 Error: Get http://localhost:8126/debug/vars: dial tcp [::1]:8126: connectex: No connection could be made because the target machine actively refused
it.

========
ggregator
========
 Checks Metric Sample: 129,005
 Dogstatsd Metric Sample: 1
 Event: 11
 Events Flushed: 11
 Number Of Flushes: 339
 Series Flushed: 124,249
 Service Check: 4,761
 Service Checks Flushed: 5,090
 Sketches Flushed: 3,693
 Checks Histogram Bucket Metric Sample: 782,692

========
ogStatsD
========
 Event Packets: 0
 Event Parse Errors: 0
 Metric Packets: 0
 Metric Parse Errors: 0
 Service Check Packets: 0
 Service Check Parse Errors: 0
 Udp Bytes: 0
 Udp Packet Reading Errors: 0
 Udp Packets: 1
 Uds Bytes: 0
 Uds Origin Detection Errors: 0
 Uds Packet Reading Errors: 0
 Uds Packets: 0

```

kubelet (4.1.0) collector always failed on Winodws node on AKS. See the above info page for the failure call stack.

pod level tags are missing in the metrics collected by openmetrics.

**Describe what you expected:**

kubelet shouldn't fail.
pod level tags should be present in the metrics.

**Steps to reproduce the issue:**

Use the following k8s manifest file to deploy into an Windows node pool on AKS

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: datadog-win-agent
    name: datadog-win-agent
  name: datadog-win-agent
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: datadog-win-agent
  template:
    metadata:
      labels:
        app: datadog-win-agent
      name: datadog-win-agent
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows
      serviceAccountName: datadog-agent
      containers:
      - image: datadog/agent@sha256:bfe51d57cfebfe249294cf1cd889d0a8d2038f09e4d9abb3f5539d01904cb794
        imagePullPolicy: Always
        name: datadog-win-agent
        ports:
        - containerPort: 8125
          hostPort: 8125
          name: dogstatsdport
          protocol: UDP
        - containerPort: 8126
          hostPort: 8126
          name: traceport
          protocol: TCP
        envFrom:
        - secretRef:
            name: datadog-agent
        env:
        - {name: DD_AC_EXCLUDE, value: "name:datadog-win-agent name:.*-test"}
        - {name: KUBERNETES, value: "true"}
        - {name: DD_DOGSTATSD_NON_LOCAL_TRAFFIC, value: "true" }
        - {name: DD_HEALTH_PORT, value: "5555"}
        - {name: DD_COLLECT_KUBERNETES_EVENTS, value: "true" }
        - {name: DD_LEADER_ELECTION, value: "false" }
        - {name: DD_APM_ENABLED, value: "false" }
        - {name: DD_APM_NON_LOCAL_TRAFFIC, value: "false"}
        - {name: DD_LOGS_ENABLED, value: "true"}
        - {name: DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL, value: "true"}
        - {name: DD_KUBELET_TLS_VERIFY, value: "false"}
        - name: DD_KUBERNETES_KUBELET_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_HOST_AGENT
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_KUBERNETES_POD_LABELS_AS_TAGS
          value: '{"app":"app"}'
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "2048Mi"
            cpu: "200m"
        volumeMounts:
        - {name: logpodpath, mountPath: /var/log/pods}
        - {name: logcontainerpath, mountPath: /var/lib/docker/containers}
        - {name: logcontainerpath2, mountPath: /ProgramData/docker/containers}
        - {name: dockershim, mountPath: /var/lib/dockershim}
        - {name: dockerengine, mountPath: '\\.\pipe\docker_engine'}
      volumes:
      - {name: logpodpath, hostPath: {path: /var/log/pods}}
      - {name: logcontainerpath, hostPath: {path: /var/log/containers}}
      - {name: logcontainerpath2, hostPath: {path: /ProgramData/docker/containers}}
      - {name: dockershim, hostPath: {path: /var/lib/dockershim}}
      - {name: dockerengine, hostPath: {path: '\\.\pipe\docker_engine'}}
```

**Additional environment details (Operating System, Cloud provider, etc):**
Azure AKS with both Linux and Windows node pools
