### ISSUE TITLE
datadog dockerfile is lack of file datadog-cluster-agent.arm64

### ISSUE THREAD

**Issue by tulid** [DataDog/datadog-agent#6037]
- question:
https://github.com/DataDog/datadog-agent/tree/master/Dockerfiles/cluster-agent/arm64
In the directory, there is one statement “COPY datadog-cluster-agent.arm64 opt/datadog-agent/bin/datadog-cluster-agent” that is lack of ’datadog-cluster-agent.arm64‘
- ideal
The file ’datadog-cluster-agent.arm64‘ can be found.

- asking
Pls tell me the file  ’datadog-cluster-agent.arm64‘ where it can be found, tks.

**Comment by mx-psi** [comment]
Hi @tulid! That Dockerfile is meant to be built in our CI environment, so it needs some previous setup before you can `docker build` it. If you are curious, you can get that binary by 
1. installing the dependencies on `requirements.txt`,
2. running the task `ARCH=arm64 inv -e cluster-agent.build` and
3. renaming the output to `datadog-cluster-agent.arm64`.

You don't have to build the image yourself unless you want to contribute to the project or create a custom image. If you just want to use the Cluster Agent you can [follow these steps](https://docs.datadoghq.com/agent/cluster_agent/setup/).

**Comment by iagomelanias** [comment]
Cluster agent arm64 images are not being pushed to [Docker Hub repository](https://hub.docker.com/r/datadog/cluster-agent/tags). Is there any other repo where we can find these images?

**Comment by mx-psi** [comment]
@iagomelanias @jordiprats as of `1.11.0` the Datadog Cluster Agent Docker images are released both on the amd64 and arm64 architectures. Upgrading to this version should solve your issues. 

Since we released this new version I am closing this issue, feel free to comment/open a new one if you encounter further problems.

**Comment by jordiprats** [comment]
It might be released for arm64 but using the following values on the helm chart you get the error @iagomelanias mentions 

```
clusterAgent:
  enabled: true
  image:
    name: cluster-agent-arm64
    tag: 1.11.0
agents:
  enabled: true
  image:
    name: agent-arm64
    tag: 7.26.0
clusterChecksRunner:
  enabled: false
  image:
    name: agent-arm64
    tag: 7.26.0
```
