### ISSUE TITLE
Datadog Custom Metric (CRD backed) reporting incorrect value to HPA

### ISSUE THREAD

**Issue by buildmaster** [DataDog/datadog-agent#6121]
**Describe what happened:**
I have the following DatadogMetric set up
```
apiVersion: datadoghq.com/v1alpha1
kind: DatadogMetric
metadata:
  name: app-response-time
spec:
  query: max:trace.hapi.request.duration.by_service{env:dev,service:jrny/app}
```

and the following HPA
```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
  name: app-hpa
spec:
  metrics:
    - type: External
      external:
        metricName: "datadogmetric@jrny:app-response-time"
        targetAverageValue: 1.5
```

When I describe the CustomMetric the following is output

```
Name:         app-response-time
Namespace:    jrny
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  ...
API Version:  datadoghq.com/v1alpha1
Kind:         DatadogMetric
Metadata:
  Creation Timestamp:  2020-08-04T02:04:39Z
  Generation:          5
  Resource Version:    87044183
  Self Link:           /apis/datadoghq.com/v1alpha1/namespaces/jrny/datadogmetrics/engine-response-time
  UID:                 b7c92368-0070-4076-929e-740b54c01b52
Spec:
  Query:  max:trace.hapi.request.duration.by_service{env:dev,service:jrnyai/app}
Status:
  Conditions:
    Last Transition Time:  2020-08-04T02:05:02Z
    Last Update Time:      2020-08-04T05:42:50Z
    Status:                True
    Type:                  Active
    Last Transition Time:  2020-08-04T04:24:00Z
    Last Update Time:      2020-08-04T05:42:50Z
    Status:                True
    Type:                  Valid
    Last Transition Time:  2020-08-04T02:05:02Z
    Last Update Time:      2020-08-04T05:42:50Z
    Status:                True
    Type:                  Updated
    Last Transition Time:  2020-08-04T04:24:00Z
    Last Update Time:      2020-08-04T05:42:50Z
    Status:                False
    Type:                  Error
  Current Value:           0.2257813811302185
Events:                    <none>
```
The HPA however reports the current value as 
```
Name:                                                                app-hpa
Namespace:                                                           jrny
Labels:                                                              ...
                                                                     helm.sh/chart=app-0.1.0
Annotations:                                                         ...
CreationTimestamp:                                                   Tue, 04 Aug 2020 14:04:39 +1200
Reference:                                                           Deployment/app
Metrics:                                                             ( current / target )
  "datadogmetric@jrny:app-response-time" (target average value):  215m / 1
Min replicas:                                                        1
Max replicas:                                                        20
Deployment pods:                                                     1 current / 1 desired
Conditions:
  Type            Status  Reason              Message
  ----            ------  ------              -------
  AbleToScale     True    ReadyForNewScale    recommended size matches current size
  ScalingActive   True    ValidMetricFound    the HPA was able to successfully calculate a replica count from external metric datadogmetric@jrny:app-response-time(nil)
  ScalingLimited  False   DesiredWithinRange  the desired count is within the acceptable range
```

the raw metrics endpoint reports
```
{"kind":"ExternalMetricValueList","apiVersion":"external.metrics.k8s.io/v1beta1","metadata":{"selfLink":"/apis/external.metrics.k8s.io/v1beta1/namespaces/jrny/datadogmetric@jrny:app-response-time"},"items":[{"metricName":"datadogmetric@jrny:app-response-time","metricLabels":null,"timestamp":"2020-08-04T05:43:20Z","value":"6156495n"}]}
```
**Describe what you expected:**
I would expect the HPA to have the current value of 0.225xx as reported by the DatadogMetric rather than the 215m that it it showing

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**
