### ISSUE TITLE
Enabling the Oracle check on Windows crashes the DataDog Agent service

### ISSUE THREAD

**Issue by ismaelhamed** [DataDog/datadog-agent#6246]
**Describe what happened:**
On a perfectly fine instance of DataDog Agent Manager running on Windows, after enabling the Oracle check the DataDog Agent service crashes. Upon removing the oracle check the service works again.

**Describe what you expected:**
A gracefully stop of the service at least, not a crash. Also, some traces with a hint to the problem (could not find anything on `agent.log` or `trace-agent.log`)

**Steps to reproduce the issue:**
Just enable the Oracle check with this configuration:

```
init_config:

instances:

    ## @param server - string - required
    ## The IP address or hostname of the Oracle Database Server.
    #
  - server: localhost:1521

    ## @param service_name - string - required
    ## The Oracle Database service name. To view the services available on your server,
    ## run the following query: `SELECT value FROM v$parameter WHERE name='service_names'`
    #
    service_name: XE

    ## @param user - string - required
    ## The username for the user account.
    #
    user: datadog

    ## @param password - string - required
    ## The password for the user account.
    #
    password: oracle

    ## @param only_custom_queries - string - optional - default: false
    ## Set this parameter to `true` if you want to skip default system, process, and
    ## tablespace metrics checks.
    #
    # only_custom_queries: false

    ## @param jdbc_driver_path - string - optional
    ## Set this parameter if you are not using the oracle native client.
    ## You can also add it to your $CLASSPATH instead.
    #
    jdbc_driver_path: "C:\\Tools\\ojdbc8.jar"
```

I guess it has to do with how the `jdbc_driver_path` is set.

**Additional environment details (Operating System, Cloud provider, etc):**
Windows 10, 2004. 
Oracle-XE 11g running on a container.
