### ISSUE TITLE
Issue with DatadogMetric through CRD - ExternalMetric does not follow DatadogMetric format

### ISSUE THREAD

**Issue by moxli** [DataDog/datadog-agent#6331]
**Output of the info page (if this is a bug)**
```
==============================
Datadog Cluster Agent (v1.7.0)
==============================

  Status date: 2020-09-07 13:10:56.727207 UTC
  Agent start: 2020-09-04 23:30:07.726983 UTC
  Pid: 1
  Go Version: go1.13.11
  Build arch: amd64
  Agent flavor: cluster_agent
  Check Runners: 4
  Log Level: info

  Paths
  =====
    Config File: /etc/datadog-agent/datadog-cluster.yaml
    conf.d: /etc/datadog-agent/conf.d

  Clocks
  ======
    System UTC time: 2020-09-07 13:10:56.727207 UTC

  Hostnames
  =========
    host_aliases: 
    hostname: 
    socket-fqdn: 
    socket-hostname: 
    hostname provider: gce
    unused hostname providers:
      configuration/environment: hostname is empty

  Metadata
  ========

Leader Election
===============
  Leader Election Status:  Running
  Leader Name is: datadog-cluster-agent-c845f9558-gm8lc
  Last Acquisition of the lease: Fri, 04 Sep 2020 23:31:19 UTC
  Renewed leadership: Mon, 07 Sep 2020 13:10:50 UTC
  Number of leader transitions: 34 transitions

Custom Metrics Server
=====================
  External metrics provider uses DatadogMetric - Check status directly from Kubernetes with: `kubectl get datadogmetric`


Cluster Checks Dispatching
==========================
  Status: Leader, serving requests
  Active nodes: 4
  Check Configurations: 3
    - Dispatched: 3
    - Unassigned: 0

Admission Controller
====================
  Disabled: The admission controller is not enabled on the Cluster Agent


=========
Collector
=========

  Running Checks
  ==============

    kubernetes_apiserver
    --------------------
      Instance ID: kubernetes_apiserver [OK]
      Configuration Source: file:/etc/datadog-agent/conf.d/kubernetes_apiserver.yaml
      Total Runs: 14,804
      Metric Samples: Last Run: 0, Total: 0
      Events: Last Run: 0, Total: 3,136
      Service Checks: Last Run: 4, Total: 59,196
      Average Execution Time : 1.957s
      Last Execution Date : 2020-09-07 13:10:56.000000 UTC
      Last Successful Execution Date : 2020-09-07 13:10:56.000000 UTC

=========
Forwarder
=========

  Transactions
  ============
    CheckRunsV1: 14,803
    Connections: 0
    Containers: 0
    Dropped: 0
    DroppedOnInput: 0
    Events: 0
    HostMetadata: 0
    IntakeV1: 1,858
    Metadata: 0
    Pods: 0
    Processes: 0
    RTContainers: 0
    RTProcesses: 0
    Requeued: 0
    Retried: 0
    RetryQueueSize: 0
    Series: 0
    ServiceChecks: 0
    SketchSeries: 0
    Success: 31,464
    TimeseriesV1: 14,803

==========
Endpoints
==========
  https://app.datadoghq.com - API Key ending with:
      -
```

**Describe what happened:**

I am trying to autoscale with a HPA using the apache busy worker metric.

My Datadog Metric:
```
kind: DatadogMetric
apiVersion: datadoghq.com/v1alpha1
metadata:
  name: apache-busy-workers
  namespace: $(CS_ENVIRONMENT_NAME)
spec:
  query: max:apache.performance.busy_workers{cs_env:$(CS_ENVIRONMENT_NAME),project:$(CS_PROJECT_ID),kube_container_name:doccreator-authproxy-apache}.rollup(max, 60)
```
The variables are inserted during the deploy by templating tool.

And my HPA:
```
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: doccreator-authproxy-autoscaler
  namespace: $(CS_ENVIRONMENT_NAME)
spec:
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: External
    external:
      metricName: "datadogmetric@tst:apache-busy-workers.external.metrics.k8s.io"
      targetAverageValue: 40
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: doccreator-authproxy-deployment
```

From the HPA I do get the following events:
```
Events:
  Type     Reason                        Age                      From                       Message
  ----     ------                        ----                     ----                       -------
  Warning  FailedGetExternalMetric       5m33s (x887 over 3h50m)  horizontal-pod-autoscaler  unable to get external metric tst/datadogmetric@tst:apache-busy-workers.external.metrics.k8s.io/nil: unable to fetch metrics from external metrics API: Internal error occurred: ExternalMetric does not follow DatadogMetric format
  Warning  FailedComputeMetricsReplicas  27s (x907 over 3h50m)    horizontal-pod-autoscaler  failed to get datadogmetric@tst:apache-busy-workers.external.metrics.k8s.io external metric: unable to get external metric tst/datadogmetric@tst:apache-busy-workers.external.metrics.k8s.io/nil: unable to fetch metrics from external metrics API: Internal error occurred: ExternalMetric does not follow DatadogMetric format
```

From the Datadog Metric:
describe:
```
Error from server (InternalError): Internal error occurred: DatadogMetric is invalid, err: <nil>
```
and
```
Name:         apache-busy-workers
Namespace:    tst
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"datadoghq.com/v1alpha1","kind":"DatadogMetric","metadata":{"annotations":{},"name":"apache-busy-workers","namespace":"tst"}...
API Version:  datadoghq.com/v1alpha1
Kind:         DatadogMetric
Metadata:
  Creation Timestamp:  2020-09-07T10:01:59Z
  Generation:          1
  Resource Version:    256266925
  Self Link:           /apis/datadoghq.com/v1alpha1/namespaces/tst/datadogmetrics/apache-busy-workers
  UID:                
Spec:
  Query:  max:apache.performance.busy_workers{cs_env:tst,project:doccreator-pre-prd,kube_container_name:doccreator-authproxy-apache}.rollup(max, 60)
Status:
  Conditions:
    Last Transition Time:  2020-09-07T10:01:59Z
    Last Update Time:      2020-09-07T10:01:59Z
    Status:                False
    Type:                  Active
    Last Transition Time:  2020-09-07T10:01:59Z
    Last Update Time:      2020-09-07T10:01:59Z
    Status:                False
    Type:                  Valid
    Last Transition Time:  2020-09-07T10:01:59Z
    Last Update Time:      2020-09-07T10:01:59Z
    Status:                True
    Type:                  Updated
    Last Transition Time:  2020-09-07T10:01:59Z
    Last Update Time:      2020-09-07T10:01:59Z
    Status:                False
    Type:                  Error
  Current Value:           0
Events:                    <none>
```

I followed [this guide](https://docs.datadoghq.com/agent/cluster_agent/external_metrics/) to setup the CRD.
```
mdorner@lt01858  ~  k get apiservices.apiregistration.k8s.io | grep datadog
v1alpha1.datadoghq.com                 Local                                 True        2d14h
v1beta1.external.metrics.k8s.io        infra/datadog-custom-metrics-server   True        3d1h
```

**Describe what you expected:**

I expected to get the value to my HPA, just like through the UI.
![image](https://user-images.githubusercontent.com/26149616/92395405-92f68400-f123-11ea-92e7-9818e26484ff.png)

**Steps to reproduce the issue:**

Setup the Datadog CRD with this guide: https://docs.datadoghq.com/agent/cluster_agent/external_metrics/
And use the Apache Busy Worker metric for a HPA.

**Additional environment details (Operating System, Cloud provider, etc):**

- Operating System: COS
- Cloud Provider: GKE / Google Cloud
