### ISSUE TITLE
trace-agent: Add tags-based filtering

### ISSUE THREAD

**Issue by deadok22** [DataDog/datadog-agent#7050]
trace-agent only offers trace [filtering by Resource](https://github.com/DataDog/datadog-agent/blob/0b2da02e66907776a252e6e7a635d5652b1ab30a/pkg/trace/agent/agent.go#L180). Implement filtering by tags.

One use-case is enforcing trace tagging to enable attribution of Datadog APM usage to business units. We could do that by discarding all traces that do not have the appropriate tags.

**Comment by andrewsouthard1** [comment]
Hey @deadok22 - have you taken a look at using Retention Filters in the app? This gives you the ability to filter traces by tags. https://docs.datadoghq.com/tracing/trace_retention_and_ingestion/#retention-filters

**Comment by deadok22** [comment]
Hi @andrewsouthard1! Thanks for sharing that. Yeah, I'm aware of that feature, but it doesn't quite address the scenario I have in mind. Let me elaborate.

We are considering switching to Datadog from a different tracing vendor and we'd like to ensure we can benefit from [Usage Attribution](https://app.datadoghq.com/account/usage_attribution) functionality. To do that, we need to have all of the submitted traces to have tags indicating a business unit. It seems the most practical way to do that for an organization with hundreds of services would be to simply discard all traces that are not tagged appropriately.

Retention filters are applied after the data was ingested, which means the trace data that's not tagged appropriately will be made available in the UI. That, in turn, will not give engineers any motivation to add the tags.

I hope this is clearer now

**Comment by knusbaum** [comment]
@deadok22 
For this we should be precise about how users will configure tag filtering before we start.

Do we just filter based on the presence of keys?
For example:
```yaml
apm_config:
  filter_tags:
    require_keys: ["required.key.1", "required.key.2"]
    forbid_keys: ["forbidden.key.1", "forbidden.key.2"]
```

Do we need to specify required value formats?
```yaml
apm_config:
  filter_tags:
    require_keys:
      required.key.1: "must-match-rexex.*"
      required.id: "[0-9]{2}-[a-zA-Z0-9]*"
    forbid_keys: ["forbidden.key.1", "forbidden.key.2"]
```

It should be noted that tag filtering would only apply to the root span of a trace, same as resource filtering. It's too expensive to iterate through every span of every trace to check tags.

Please let me know your thoughts.

**Comment by deadok22** [comment]
@knusbaum I believe the following two types of filtering should suffice:
* Tag key presence-based type that works like what you described in the first example
* Key-value based to implement rules like "discard everything tagged with app:that-misbehaving-app"

As for regex-based filtering, I have no use-cases for it at the moment. Regex-based filtering is also going to be more resource-intensive compared to string comparison. However, I won't be surprised if somebody requests this capability later on.

Filtering on the root spans' tags only should work well enough.

**Comment by gbbr** [comment]
There is quite a bit of discrepancy between the two: reject and required. May I suggest an alternative which allows to expand on in the future?

```yaml
apm_config:
    filter_tags:
        require: ["outcome:success", "db"],
        reject: ["bad", "app:sql"],
```

In the above case, we allow setting both key and value and also only key. To describe what happens using the above config:

* Traces are ignored if they don't have the tag `outcome` with the value `success` and the tag `db` with _any value_.
* Traces are ignored if they have the tag `bad` with any value or the tag `app` with value `sql`.

I think this allows for more versatility. If someone in the future requires it, the current proposal will be harder to adapt.
