### ISSUE TITLE
Datadog agent not correctly using cmd_port

### ISSUE THREAD

**Issue by ju2wheels** [DataDog/datadog-agent#7223]
Im using version `4.4.0` of the chef-datadog Chef cookbook to deploy agent version 7 with the following overrides:

```
default['datadog']['agent_major_version']           = '7'
default['datadog']['agent_package_action']          = 'install'
default['datadog']['agent_version']                 = '7.20.2'
default['datadog']['disk']['file_system_blacklist'] = [
  'nsfs',
  'shm',
  'tracefs'
]
default['datadog']['disk']['mount_point_blacklist'] = []
override['datadog']['hostname']                     = node.name.split('.').first
override['datadog']['cmd_port']                                = 5501
override['datadog']['disk']['mount_point_blacklist']           = [
  '/srv/docker/containers/.*',
  '/srv/docker/devicemapper/.*'
]
```

The main configuration change here that Im concerned with is changing the default cmd_port from 5000 to 5501 because we have another service that needs to use port 5000.

The Chef cookbook applies the config correctly as the datadog configuration yaml shows the following:

```
---
api_key: <redacted>
hostname: <redacted>
bind_host: localhost
additional_endpoints: {}
tags: []
dogstatsd_non_local_traffic: false
histogram_aggregates:
- max
- median
- avg
- count
histogram_percentiles:
- '0.95'
use_dogstatsd: true
log_level: INFO
cmd_port: 5501
log_file: "/var/log/datadog/agent.log"
process_config:
  enabled: 'false'
  intervals: {}
  blacklist_patterns: []
  scrub_args: true
  custom_sensitive_words: []
  process_dd_url: https://process.datadoghq.com
apm_config:
  apm_non_local_traffic: false

```

However when the agent starts, it ends up using both port 5000 and 5501 if datadog starts before the service using port 5000, otherwise if datadog starts after the service then it only comes up with 5501 as the other port is in use by the other service. Therefore its basically a race condition for port 5000 and im not sure if this port being used by the other service is causing the datadog agent any other issues.

How can I fix this race condition on the port?
