### ISSUE TITLE
Wrong binary on a arm64 container

### ISSUE THREAD

**Issue by jordiprats** [DataDog/datadog-agent#7589]
Hi,
Looks like you are mixing binaries from different architectures:

```
kubectl logs datadog-sv8dk -n datadog -c init-volume
standard_init_linux.go:211: exec user process caused "exec format error"
```

Appears to be the same as in [6037](https://github.com/DataDog/datadog-agent/issues/6037) but it is related to the initcontainer init-volume which is just using a cp launching a bash:

```
  initContainers:
  - args:
    - cp -r /etc/datadog-agent /opt
    command:
    - bash
    - -c
    image: gcr.io/datadoghq/agent-arm64:7.26.0
    imagePullPolicy: Always
    name: init-volume
```
