### ISSUE TITLE
Using OpenJDK 11+ but profiling is not enabled

### ISSUE THREAD

**Issue by khauser** [DataDog/datadog-agent#7603]
Using the docker image "adoptopenjdk/openjdk11-openj9:jre-11.0.10_9_openj9-0.24.0-alpine" as base image in Azure AKS I get the following WARNING:

```
[dd.trace 2021-03-07 20:11:25:046 +0000] [main] INFO datadog.trace.agent.core.StatusLogger - DATADOG TRACER CONFIGURATION {"version":"0.75.0~e75ffb95d","os_name":"Linux","os_version":"5.4.0-1035-azure","architecture":"amd64","lang":"jvm","lang_version":"11.0.10","jvm_vendor":"AdoptOpenJDK","jvm_version":"openj9-0.24.0","java_class_version":"55.0","http_nonProxyHosts":"null","http_proxyHost":"null","enabled":true,"service":"iste-execution","agent_url":"http://10.240.0.5:8126","agent_error":false,"debug":false,"analytics_enabled":false,"sampling_rules":[{},{}],"priority_sampling_enabled":true,"logs_correlation_enabled":true,"profiling_enabled":true,"dd_version":"0.75.0~e75ffb95d","health_checks_enabled":true,"configuration_file":"no config file present","runtime_id":"6e99c0fd-2f32-4e6d-9559-4d8533bbc90b","logging_settings":{"levelInBrackets":false,"dateTimeFormat":"'[dd.trace 'yyyy-MM-dd HH:mm:ss:SSS Z']'","logFile":"System.err","configurationFile":"simplelogger.properties","showShortLogName":false,"showDateTime":true,"showLogName":true,"showThreadName":true,"defaultLogLevel":"INFO","warnLevelString":"WARN","embedException":false}}
[dd.trace 2021-03-07 20:11:25:055 +0000] [main] WARN com.datadog.profiling.agent.ProfilingAgent - Not enabling profiling; it requires OpenJDK 11+, Oracle Java 11+, or Zulu Java 8 (1.8.0_212+).
```

Datadog agent status:
```
===============
Agent (v7.26.0)
===============

  Status date: 2021-03-07 20:17:40.529258 UTC
  Agent start: 2021-03-06 17:15:43.471628 UTC
  Pid: 1
  Go Version: go1.14.12
  Python Version: 3.8.5
  Build arch: amd64
  Agent flavor: agent
  Check Runners: 4
  Log Level: INFO

  Paths
  =====
    Config File: /etc/datadog-agent/datadog.yaml
    conf.d: /etc/datadog-agent/conf.d
    checks.d: /etc/datadog-agent/checks.d

  Clocks
  ======
    NTP offset: -5.358ms
    System UTC time: 2021-03-07 20:17:40.529258 UTC

  Host Info
  =========
    bootTime: 2021-01-27 06:54:13.000000 UTC
    kernelArch: x86_64
    kernelVersion: 5.4.0-1035-azure
    os: linux
    platform: debian
    platformFamily: debian
    platformVersion: bullseye/sid
    procs: 209
    uptime: 922h21m35s
    virtualizationRole: host
    virtualizationSystem: kvm

  Hostnames
  =========
    host_aliases: [91bcbb7a-3a32-4aed-a9de-21f20a39c491 aks-initial-24545083-1-iste-test-aks]
    hostname: aks-initial-24545083-1
    socket-fqdn: datadog-4r27r
    socket-hostname: datadog-4r27r
    host tags:
      kube_cluster_name:iste-test-aks
      cluster_name:iste-test-aks
      kube_node_role:agent
    hostname provider: container
    unused hostname providers:
      aws: not retrieving hostname from AWS: the host is not an ECS instance and other providers already retrieve non-default hostnames
      configuration/environment: hostname is empty
      gce: unable to retrieve hostname from GCE: status code 404 trying to GET http://169.254.169.254/computeMetadata/v1/instance/hostname

  Metadata
  ========
    cloud_provider: Azure
    hostname_source: container
```

I use gradle:

```
    compile group: 'com.datadoghq', name: 'java-dogstatsd-client', version: "2.11.0"
    compile group: 'com.datadoghq', name: 'dd-trace-api', version: "0.75.0"
    dd_agent group: 'com.datadoghq', name: 'dd-java-agent', version: "0.75.0"
```

plus kubernetes deployment:

```
          {{- if  .Values.datadog.enabled }}
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          - name: DD_ENV
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/env']
          - name: DD_SERVICE
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['tags.datadoghq.com/service']
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_PROFILING_ENABLED
            value: "true"
          {{- end }}
```

Thanks for help
