### ISSUE TITLE
Spam in logs from Failed pods

### ISSUE THREAD

**Issue by therc** [DataDog/datadog-agent#8377]
I have seen these in 7.27.0 and in 7.28.1.

```log
WARN | (pkg/util/kubernetes/kubelet/containers.go:165 in parseContainerNetworkAddresses) | Unable to parse host IP:  for pod: FOO
[...]
WARN | (pkg/util/log/log.go:541 in func1) | Unable to parse host IP:  for pod: FOO
```

It seems to be triggered here:

https://github.com/DataDog/datadog-agent/blob/140a4ee164261ef2245340c50371ba989fbeb038/pkg/util/kubernetes/kubelet/containers.go#L165

I spot checked a few of the many pods that trigger these messages. They all lack the HostIP field and they seem to be all in phase:Failed / reason:DeadlineExceeded. See below:

```yaml
status:
  containerStatuses:
  - containerID: docker://1e76b619af3311e69ce45115949237b9b6ca393af12cbd61383451c17b2c12aa
    lastState: {}
    name: FOO
    ready: false
    restartCount: 0
    state:
      running:
        startedAt: "2021-06-05T02:07:37Z"
  message: Pod was active on the node longer than the specified deadline
  phase: Failed
  podIP: 10.1.173.41
  podIPs:
  - ip: 10.1.173.41
  qosClass: Guaranteed
  reason: DeadlineExceeded
  startTime: "2021-06-05T02:07:36Z"
```
For what it's worth, kubelet.go ignores the pod when it sees the same in GetNodeInfo(). Maybe containers.go could ignore it as well or it could emit the log only if phase!=Failed.
