### ISSUE TITLE
[AD] Not discovering new containers with container_exclude_metrics: image:.*

### ISSUE THREAD

**Issue by ryzr** [DataDog/datadog-agent#8888]
**Describe what happened:**
I am trying to exclude metric collection and ONLY collect logs for my containers. If I start the agent, it tails logs from sibling containers fine, however if they change status (e.g. existing containers stopped, or new containers started), the datadog-agent does not notice this.

**Describe what you expected:**
I expect that the agent would still discover containers starting up or spinning down, but not report any metric/event collection to Datadog (I just want logs).

**Steps to reproduce the issue:**

Using config:
```
site: datadoghq.com
dd_url: https://app.datadoghq.com

cloud_provider_metadata:
  - "aws"

collect_ec2_tags: true

logs_enabled: true

listeners:
  - name: docker

container_exclude_metrics:
  - image:.*

apm_config:
  enabled: false

process_config:
  enabled: "disabled"

use_dogstatsd: false

autoconfig_exclude_features:
  - cloudfoundry
  - cri
  - ecsfargate
  - eksfargate
  - kubernetes
  - orchestratorexplorer
```

With log config at `/etc/datadog-agent/conf.d/logging.d/conf.yaml`

```
logs:
  - type: file
    path: "/var/log/host/messages"
    source: "custom"
    service: "messages"
  - type: file
    path: "/var/log/host/secure"
    source: "custom"
    service: "secure"
  - type: file
    path: "/var/log/host/audit/audit.log"
    source: "custom"
    service: "audit"
  - type: file
    path: "/var/log/datadog/*.log"
    source: "custom"
    service: "datadog"
```

Start the agent on a host with containers running.
--> See that logs are ingested into Datadog correctly

Start a new container
-->  See that logs for the new container are NOT ingested

Stop an existing container a new container
Run `agent configcheck`
-->  See that stopped container still appears in the autodiscovery list, and that the new container does not

**Additional environment details (Operating System, Cloud provider, etc):**
Using datadog/agent 7.30.0

Deployed to ECS. Relevant task definition json:
```{
  "containerDefinitions": [
    {
      "name": "datadog-agent",
      "essential": true,
      "mountPoints": [
        {
          "readOnly": true,
          "containerPath": "/var/run/docker.sock",
          "sourceVolume": "docker_sock"
        },
        {
          "readOnly": true,
          "containerPath": "/host/sys/fs/cgroup",
          "sourceVolume": "cgroup"
        },
        {
          "readOnly": true,
          "containerPath": "/host/proc",
          "sourceVolume": "proc"
        },
        {
          "readOnly": true,
          "containerPath": "/var/lib/docker/containers",
          "sourceVolume": "containers_root"
        },
        {
          "readOnly": false,
          "containerPath": "/opt/datadog-agent/run",
          "sourceVolume": "pointdir"
        },
        {
          "readOnly": true,
          "containerPath": "/var/log/host",
          "sourceVolume": "logs"
        }
      ],
      "healthCheck": {
        "retries": 3,
        "command": [
          "CMD-SHELL",
          "agent health"
        ],
        "timeout": 5,
        "interval": 30,
        "startPeriod": 15
      }
    }
  ],
  "compatibilities": [
    "EXTERNAL",
    "EC2"
  ],
  "volumes": [
    {
      "name": "cgroup",
      "host": {
        "sourcePath": "/sys/fs/cgroup/"
      }
    },
    {
      "name": "pointdir",
      "host": {
        "sourcePath": "/opt/datadog-agent/run"
      }
    },
    {
      "name": "containers_root",
      "host": {
        "sourcePath": "/var/lib/docker/containers"
      }
    },
    {
      "name": "proc",
      "host": {
        "sourcePath": "/proc/"
      }
    },
    {
      "name": "docker_sock",
      "host": {
        "sourcePath": "/var/run/docker.sock"
      }
    },
    {
      "name": "logs",
      "host": {
        "sourcePath": "/var/log/"
      }
    }
  ]
}
```
