### ISSUE TITLE
Cannot discovery docker containers

### ISSUE THREAD

**Issue by greatbody** [DataDog/datadog-agent#8889]
**Describe what happened:**
I have a host running Ubuntu, and have docker installed.

I started an docker agent to track server status.

I was expecting to see all containers running on this machine, however, I cannot see any container in Container tab.

**Describe what you expected:**
I was expecting to see all containers running on this machine, however, I cannot see any container in Container tab.

**Steps to reproduce the issue:**

Set up docker agent of datadog

docker-compose file of datadog docker agent
```yml
services:
  dd-agent:
    container_name: dd-agent-app
    environment:
      DD_API_KEY: <key>
      DD_SITE: "datadoghq.com"
      DD_HOSTNAME: "pi"
      DD_TAGS: "host:pi"
      DD_PROCESS_AGENT_ENABLED: "true"
      DD_DOCKER_LABELS_AS_TAGS: "{\"<LABEL_NAME>\": \"<TAG_KEY>\"}"
      SD_BACKEND: "docker"
      DD_LOGS_ENABLED: "true"
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: "true"
    image: gcr.io/datadoghq/agent:latest
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /var/lib/docker/containers:/var/lib/docker/containers:ro
    - /proc/:/host/proc/:ro
    - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
version: '3'
```

**Additional environment details (Operating System, Cloud provider, etc):**

os : GNU/Linux
kernel_name : Linux
processor : aarch64
kernel_release : 5.11.0-1015-raspi
kernel_version : #16-Ubuntu SMP PREEMPT Wed Jul 14 11:04:58 UTC 2021
machine : aarch64
hardware_platform : aarch64

Docker version 20.10.8, build 3967b7d
