### ISSUE TITLE
SNMP for Dell idRac no longer collecting after upgrading agent from 7.29.1 to 7.30.0

### ISSUE THREAD

**Issue by KoenDG** [DataDog/datadog-agent#8916]
**Output of the info page (if this is a bug)**
```
    snmp
    ----
      Instance ID: snmp:464901764d02cb45 [ERROR]
      Configuration Source: file:/etc/datadog-agent/conf.d/snmp.d/conf.yaml
      Total Runs: 13
      Metric Samples: Last Run: 4, Total: 52
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 13
      Average Execution Time : 10.674s
      Last Execution Date : 2021-08-18 12:43:48 UTC (1629290628000)
      Last Successful Execution Date : Never
      Error: failed to fetch values: failed to fetch scalar oids with batching: failed to fetch scalar oids: fetch scalar: error getting oids `[1.3.6.1.2.1.1.3.0 1.3.6.1.4.1.674.10892.2.3.1.9.0 1.3.6.1.4.1.674.10892.2.3.1.1.0 1.3.6.1.4.1.674.10892.2.3.1.5.0 1.3.6.1.4.1.674.10892.2.3.1.4.0]`: request timeout (after 3 retries)
      No traceback
```

**Describe what happened:**

I tested adding SNMP for a Ubuntu 18.04 VM running on a machine that has an idRac. This worked fine.

A few days later I do it on an other VM on the same machine and it gives me this error:

```
2021-08-18 12:40:10 UTC | CORE | ERROR | (pkg/collector/runner/runner.go:302 in work) | Error running check snmp: failed to fetch values: failed to fetch oids with batching: failed to fetch column oids: fetch column: failed getting oids `[1.3.6.1.4.1.343.2.7.2.2.1.3.1.4 1.3.6.1.4.1.343.2.7.2.2.1.3.1.5 1.3.6.1.4.1.343.2.7.2.2.1.3.1.6 1.3.6.1.4.1.343.2.7.2.2.1.3.1.7 1.3.6.1.4.1.343.2.7.2.2.1.3.1.8]` using GetBulk: request timeout (after 3 retries)
```
I noticed the difference was the most recent install uses agent version 7.30.0 and the first one uses 7.29.1

I tried downgrading and that fixed it, both VMs now gather the metrics just fine and report no error for SNMP. Switching back to 7.30.0 brings the error back. Switching to 7.29.1 fixes it.

Content of the conf file:

```
init_config:
    loader: core
instances:
-   community_string: public
    ip_address: <REMOVED>
```

**Describe what you expected:**

SNMP to work as previously on the other VM.

**Steps to reproduce the issue:**

Just default install with the conf file as mentioned above.

**Additional environment details (Operating System, Cloud provider, etc):**

Ubuntu 18.04 VM, deployed using the datadog role from ansible galaxy.

**Comment by AlexandreYang** [comment]
@KoenDG Thanks for reporting this. 

Could you try to use those configs using 7.30 and comment here if it works or not ?

Setup 1/ oid_batch_size: 1  (get less snmp OID values per call)
```
init_config:
    loader: core
    oid_batch_size: 1
instances:
-   community_string: public
    ip_address: <REMOVED>
```

Setup 2/ oid_batch_size: 60 (this is the value used in 7.29.1)
```
init_config:
    loader: core
    oid_batch_size: 60
instances:
-   community_string: public
    ip_address: <REMOVED>
```

I would like to check if the issue is related to too many values being requested.

---

We did made a change related to `oid_batch_size` (https://github.com/DataDog/datadog-agent/pull/8575) to reduce the likely wood of sending requests that are are too large for the device to handle, but it should have the opposite effect as you described here.
