### ISSUE TITLE
enabling runtime_security_config leads to auth_token unreadable

### ISSUE THREAD

**Issue by sfuerte** [DataDog/datadog-agent#9064]
Enabling the `runtime_security` makes `auth_token` readable by `root` only

**Output of the info page (if this is a bug)**
```sh
$ sudo datadog-agent status
Getting the status from the agent.

===============
Agent (v7.30.1)
===============

  Status date: 2021-09-02 22:41:30.315 UTC (1630622490315)
  Agent start: 2021-09-02 22:00:20.529 UTC (1630620020529)
  Pid: 2639
  Go Version: go1.15.13
  Python Version: 3.8.10
  Build arch: amd64
  Agent flavor: agent
  Check Runners: 4
  Log Level: info

  Paths
  =====
    Config File: /etc/datadog-agent/datadog.yaml
    conf.d: /etc/datadog-agent/conf.d
    checks.d: /etc/datadog-agent/checks.d

  Clocks
  ======
    NTP offset: 30.338ms
    System time: 2021-09-02 22:41:30.315 UTC (1630622490315)

  Host Info
  =========
    bootTime: 2021-09-02 21:55:56 UTC (1630619756000)
    kernelArch: x86_64
    kernelVersion: 5.10.0-0.bpo.8-cloud-amd64
    os: linux
    platform: debian
    platformFamily: debian
    platformVersion: 10.10
    procs: 101
    uptime: 4m36s
    virtualizationRole: guest
    virtualizationSystem: kvm

  Hostnames```

**Describe what happened:**
```sh
ls -l /etc/datadog-agent/
total 120
-rw-------   1 root     root        64 Sep  2 21:56 auth_token
...
```

**Describe what you expected:**
```sh
$ ls -l /etc/datadog-agent/
total 120
-rw-------   1 dd-agent root        64 Sep  2 21:56 auth_token
drwxr-xr-x   2 dd-agent dd-agent  4096 Aug 19 16:32 checks.d
drwxr-xr-x   2 dd-agent dd-agent  4096 Sep  2 19:23 compliance.d
...
```

**Steps to reproduce the issue:**

```yml
# /etc/datadog-agent/security-agent.yaml
# Managed by Ansible
runtime_security_config:
  enabled: true
# BEGIN ANSIBLE MANAGED BLOCK
compliance_config:
  enabled: true
# END ANSIBLE MANAGED BLOCK
```

```yml
# /etc/datadog-agent/system-probe.yaml
# Managed by Ansible
system_probe_config:
  sysprobe_socket: /opt/datadog-agent/run/sysprobe.sock
network_config:
  enabled: true
runtime_security_config:
  enabled: true
```

**Additional environment details (Operating System, Cloud provider, etc):**

```sh
$ lsb_release -d
Description:	Debian GNU/Linux 10 (buster)
```
