### ISSUE TITLE
TCP checks not available / running

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [DataDog/datadog-agent#9146]
**Describe what happened:**

Unable to get cluster agent to fetch tcp metrics. 

**Describe what you expected:**

See metrics related to tcp checks

**Steps to reproduce the issue:**

I am following the official instructions about how to install the agent on `kubernetes`

> To install the chart with a custom release name, RELEASE_NAME (e.g. datadog-agent):
> - Install Helm.
> - Add Datadog Helm repository: helm repo add datadog https://helm.datadoghq.com.
> - Add stable repository (for kube-state-metrics chart): helm repo add stable https://charts.helm.sh/stable.
> - Fetch latest version of newly added charts: helm repo update.
> - Download the Datadog values.yaml configuration file.
> - Deploy the Datadog Agent ...

I deployed both cluster and node agents with the following configuration (this is a snippet from `values.yaml` used during `helm install` )

```
  confd:
    tcp_check.yaml: |-
      cluster_check: true
      init_config:
      instances:
        - name: A TCP check
          host: some.end.point.com
          port: 12345
          collect_response_time: true
    http_check.yaml: |-
      cluster_check: true
      init_config:
      instances:
        - collect_response_time: true
          min_collection_interval: 60
          name: an HTTP check
          tags:
            - service:my_service
          timeout: 10
          url: https://another.end.point.com
```

The `network.tcp.can_connect` metric for example never reaches DD.

What is more:

```
$ datadog-cluster-agent status

  Loading Errors
  ==============
    tcp_check
    ---------
      Core Check Loader:
        Check tcp_check not found in Catalog
```

**Additional environment details (Operating System, Cloud provider, etc):**

Using

```
Datadog Cluster Agent (v1.11.0)
```

on GKE 1.22
