### ISSUE TITLE
Does this support custom checks for the cluster agent?

### ISSUE THREAD

**Issue by winjer** [DataDog/datadog-agent#9384]
In the Helm chart for the agent I can see that it is possible to implement custom checks as python code. This is in the default values.yaml:

```
# datadog.checksd -- Provide additional custom checks as python code
  ## Each key becomes a file in /checks.d
  ## ref: https://github.com/DataDog/datadog-agent/tree/main/Dockerfiles/agent#optional-volumes
  checksd: {}
  #   service.py: |-
```

There isn't something equivalent for the cluster agent runner, there is only support for confd:

```
  # clusterAgent.confd -- Provide additional cluster check configurations
  ## Each key will become a file in /conf.d
  ## ref: https://docs.datadoghq.com/agent/autodiscovery/
  confd: {}
  #   mysql.yaml: |-
  #     cluster_check: true
  #     instances:
  #       - server: '<EXTERNAL_IP>'
  #         port: 3306
  #         user: datadog
  #         pass: '<YOUR_CHOSEN_PASSWORD>'
```

Is it possible to use custom checks with the cluster agent?

**Comment by vboulineau** [comment]
The Cluster Agent is not capable of running Python checks as it's not shipped with Python.

However you can use Cluster Checks to achieve the same purpose (running a single/few instances of a check): https://docs.datadoghq.com/agent/cluster_agent/clusterchecks/

The Cluster Agent will take care of dispatching these cluster checks to some Agents (or dedicated Cluster Check Runner instances if you have any).

**Comment by bajaj6** [comment]
@vboulineau to run custom checks just once:
I should just define the python file in `checksd:` of datadog-agent and then define the `.yaml.` config file in the  `confd:` of cluster-agent?

**Comment by vboulineau** [comment]
Yes, you have an example of `confd` with `cluster_check: true`:
https://docs.datadoghq.com/containers/cluster_agent/clusterchecks/?tab=helm#configuration-from-configuration-files

**Comment by bajaj6** [comment]
So I am using argocd to deploy datadog on kubernetes.
how can I get the custom check python code from a different file.

This doesn't work
```
      - name: datadog.checksd.custom_kubecost\.py
        value: {{ .Files.Get "custom_kubecost.py" }}
```

`chart.yaml` file
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog-chart
  namespace: argocd
spec:
  project: default
  source:
    chart: datadog
    repoURL: https://helm.datadoghq.com
    targetRevision: 2.30.10
    helm:
      releaseName: datadog
      parameters:
      - name: registry
        value: public.ecr.aws/datadog
      - name: datadog.processAgent.processCollection
        value: "true"
      - name: datadog.prometheusScrape.enabled
        value: "true"
      - name: datadog.prometheusScrape.serviceEndpoints
        value: "true"
      - name: datadog.podLabelsAsTags.workflows\.argoproj\.io\/workflow
        value: "argo_workflow_name"
      - name: datadog.checksd.custom_kubecost\.py
        value: {{ .Files.Get "custom_kubecost.py" }}
```
