### ISSUE TITLE
[ntp] Undefined behaviour with multiple instances

### ISSUE THREAD

**Issue by masci** [DataDog/datadog-agent#942]
**Describe what happened:**

If you list multiple instances in the config file of the `ntp` check, the check would be run once per instance with metrics and service checks posted without any tag, see https://github.com/DataDog/datadog-agent/blob/master/pkg/collector/corechecks/network/ntp.go#L146

**Describe what you expected:**

To be able to distinguish which value is coming from which NTP server.

**Comment by ls339** [comment]
**Test**
Configure `3` ntp instances in `conf.d/ntp.d/check.yaml` 

```
init_config:

instances:
  - offset_threshold: 60
    host: 0.asia.pool.ntp.org

  - offset_threshold: 60
    host: 0.north-america.pool.ntp.org

  - offset_threshold: 60
    host: localhost # We expect this to fail  
```

**Result**
We can't distinguish between instances if more than one instance is configured in the ntp check. Metric `ntp.offset` and service check `ntp.in_sync` will be submitted once per instance run with only a _host tag_ so we will not be able to differentiate between the metric value and the service check _status_.
It's not recommended to specify more than `1` instance in an ntp check because the service check  `ntp.in_sync` may flap if one of the configured instances does not respond. In our test, we see that _instance 2_ has a status of `3` (unknown) causing our monitor to flap. 

_instance 0_
```
Service Checks:
[
  {
    "check": "ntp.in_sync",
    "host_name": "ntpinvestigation",
    "timestamp": 1514998223,
    "status": 0,
    "message": "",
    "tags": null
  }
]
```

_instance 1_
```
Service Checks:
[
  {
    "check": "ntp.in_sync",
    "host_name": "ntpinvestigation",
    "timestamp": 1514998224,
    "status": 0,
    "message": "",
    "tags": null
  }
]
```

_instance 2_
```
Service Checks:
[
  {
    "check": "ntp.in_sync",
    "host_name": "ntpinvestigation",
    "timestamp": 1514998224,
    "status": 3,
    "message": "",
    "tags": null
  }
]
```

<img width="1130" alt="image 2018-01-03 at 12 03 28 pm" src="https://user-images.githubusercontent.com/13461090/34530812-4a20bf00-f07e-11e7-999b-b6972db28f5b.png">
