### ISSUE TITLE
Don't works com.datadoghq.ad.logs in service->deploy->labels on docker swarm

### ISSUE THREAD

**Issue by 4n70w4** [DataDog/datadog-agent#9465]
**Describe what happened:**

Don't works label `com.datadoghq.ad.logs` if defined in `service->deploy->labels`.

But works if defined in `service->labels`.

It looks strange.

For example, traefik and many other services work with labels from the `deploy` section.

**Steps to reproduce the issue:**

```yaml
version: '3.8'
services:
 
  traefik:
    image: traefik
  
    deploy:
      labels:
        traefik.enable: 'true'
        traefik.dashboard.frontend.rule: Host:{{ traefik_domain }}
        traefik.dashboard.port: 8080

        com.datadoghq.ad.logs: '[{"source": "something", "service": "balancer"}]'
```
