### ISSUE TITLE
Issue with MySQL Connector

### ISSUE THREAD

**Issue by igorhrq** [DataDog/datadog-agent#9587]
**Output of the info page (if this is a bug)**
```
Check Initialization Errors
  ===========================

    
      mysql (3.0.1)
      -------------

      instance 0:

        could not invoke 'mysql' python check constructor. New constructor API returned:
Traceback (most recent call last):
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/mysql/mysql.py", line 74, in __init__
    self._config = MySQLConfig(self.instance)
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/mysql/config.py", line 35, in __init__
    self.configuration_checks()
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/mysql/config.py", line 53, in configuration_checks
    raise ConfigurationError("Mysql host and user or a defaults_file are needed.")
datadog_checks.base.errors.ConfigurationError: Mysql host and user or a defaults_file are needed.
Deprecated constructor API returned:
__init__() got an unexpected keyword argument 'agentConfig'
  Loading Errors
  ==============
    mysql
    -----
      Core Check Loader:
        Check mysql not found in Catalog
        
      JMX Check Loader:
        check is not a jmx check, or unable to determine if it's so
        
      Python Check Loader:
        could not configure check instance for python check mysql: could not invoke 'mysql' python check constructor. New constructor API returned:
Traceback (most recent call last):
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/mysql/mysql.py", line 74, in __init__
    self._config = MySQLConfig(self.instance)
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/mysql/config.py", line 35, in __init__
    self.configuration_checks()
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/mysql/config.py", line 53, in configuration_checks
    raise ConfigurationError("Mysql host and user or a defaults_file are needed.")
datadog_checks.base.errors.ConfigurationError: Mysql host and user or a defaults_file are needed.
Deprecated constructor API returned:
__init__() got an unexpected keyword argument 'agentConfig'
        

```

**Describe what happened:**
when i try restart the datadog agent, for this specific feature, this not start correct, i will provide my conf.yaml for mysql.d below.

**Describe what you expected:**
```
init_config:

instances:
  - host: 127.0.0.1
    username: datadog
    pass: "MYPASSWORDHERE" # from the CREATE USER step earlier
    port: "3306" # e.g. 3306
    options:
      replication: false
      galera_cluster: true
      extra_status_metrics: true
      extra_innodb_metrics: true
      extra_performance_metrics: true
      schema_size_metrics: false
      disable_innodb_metrics: false
logs:
  - type: file
    path: "/var/log/mysqld.log"
    source: mysql
    service: "mysql-homolog-br"

  - type: file
    path: "/var/lib/mysql/homolog-slow.log"
    source: mysql
    service: "mysql-homolog-br"
    log_processing_rules:
      - type: multi_line
        name: new_slow_query_log_entry
        pattern: "# Time:"
```

**Steps to reproduce the issue:**
just try start the datadog-agent and i will see the error on daemon of datadog-agent.service and on datadog-agent status

**Additional environment details (Operating System, Cloud provider, etc):**

CentOS 7.9
Percona Server 5.6.45-86.1
