### ISSUE TITLE
%%hostname%% AutoDiscovery template variable should template as the Kubernetes Pod's name

### ISSUE THREAD

**Issue by icelynjennings** [DataDog/datadog-agent#9910]
**Describe what happened:**

I had written the following pod autodiscovery configuration:

```yaml
annotations:
  ad.datadoghq.com/nats.check_names: '["gnatsd"]'
  ad.datadoghq.com/nats.init_configs: '[{}]'
  ad.datadoghq.com/nats.instances: |
    [{
      "host": "http://%%host%%",
      "port": "%%port_monitor%%",
      "server_name": "%%hostname%%"
    }]
```

1. `%%hostname%%` did not template into the Pod's name.
2. `gnatsd` community integration did not appear in the agent's check list when running `agent status`

On the other hand when `server_name` above is manually hardcoded to the Pod's name:
1. `gnatsd` integration works as expected, appears in checks list
2. `gnatsd` metrics appear on Datadog.

Datadog docs specify that `%%hostname%%` is [not currently supported on Kubernetes](https://docs.datadoghq.com/agent/faq/template_variables/). Related issue: https://github.com/DataDog/datadog-agent/issues/4025

**Describe what you expected:**

`%%hostname%%` autodiscovery variable should template into the Kubernetes Pod's name. From K8S docs:

> Currently when a pod is created, its hostname is the Pod's metadata.name value.
>
> (...)
>
> The hostname of a Container is the name of the Pod in which the Container is running. It is available through the hostname command or the gethostname function call in libc.

**Steps to reproduce the issue:**

Use `%%hostname%%` AutoDiscovery template variable in any autodiscovery annotation which requires templating the annotated Pod's name.

**Additional environment details (Operating System, Cloud provider, etc):**

Kubernetes (EKS)
